# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 08:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=64, null=True)),
                ('licence_sequence', models.IntegerField(blank=True, default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_renewable', models.NullBooleanField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holder', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=64)),
                ('act', models.CharField(blank=True, max_length=256)),
                ('statement', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=64)),
                ('is_renewable', models.BooleanField(default=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licence.LicenceType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='licence',
            name='licence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licence.LicenceType'),
        ),
        migrations.AlterUniqueTogether(
            name='licence',
            unique_together=set([('licence_number', 'licence_sequence')]),
        ),
    ]
