# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='licence',
            name='created',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='licencetype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='licencetype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='licencetype',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='licencetype',
            name='modifier',
        ),
        migrations.AddField(
            model_name='licencetype',
            name='keywords',
            field=models.ManyToManyField(to='licence.Keyword'),
        ),
    ]
