# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencetype',
            name='short_name',
            field=models.CharField(blank=True, help_text='The display name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='licencetype',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='licencetype',
            unique_together=set([('short_name', 'version')]),
        ),
    ]
