# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_auto_20160801_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='short_name',
            field=models.CharField(blank=True, help_text='The display name that will show in the dashboard', max_length=30, null=True),
        ),
    ]
