# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 06:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_auto_20160322_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='licencetype',
            name='keywords',
        ),
        migrations.AddField(
            model_name='licencetype',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
