# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_auto_20160323_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='expire_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='address',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='status',
        ),
        migrations.AddField(
            model_name='licence',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
