# Generated by Django 2.1.7 on 2019-04-24 00:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_auto_20160802_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
