# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0005_auto_20160503_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencetype',
            name='is_renewable',
            field=models.BooleanField(default=True),
        ),
    ]
