# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0007_licence_is_renewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='licence_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='licence_sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='licence',
            name='licence_no',
        ),
        migrations.AlterUniqueTogether(
            name='licence',
            unique_together=set([('licence_number', 'licence_sequence')]),
        ),
    ]
