# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licence', '0009_auto_20160525_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licence',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
