# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
