# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='system',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
