# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
