# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
