# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20160802_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
