# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0007_auto_20170106_1600'),
        ('invoice', '0005_auto_20160802_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBPAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpay.BpayTransaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
