# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoicebpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
