# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
