# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_parkstay_rebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice'),
        ),
    ]
