# Generated by Django 2.1.7 on 2019-04-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_previous_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='previous_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoicebpay',
            name='bpay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpay.BpayTransaction'),
        ),
        migrations.AlterField(
            model_name='invoicebpay',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoice'),
        ),
    ]
