# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-19 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_previous_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
