# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Credit Card'), (1, 'BPAY'), (2, 'Monthly Invoicing'), (3, 'Other')], default=0),
        ),
    ]
