# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:31
from __future__ import unicode_literals

from django.db import migrations

def update_contenttypes(apps, schema_editor):
    """
    Updates content types.
    We want to have the same content type id, when the model is moved and renamed.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    #Invoice
    invoice_qs = ContentType.objects.using(db_alias).filter(app_label='invoice')
    invoice_qs.update(app_label='payments')

class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_auto_20170329_1131'),
        ('invoice', '0009_auto_20170317_0802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Invoice',
            table='payments_invoice'
        ),
        migrations.AlterModelTable(
            name='InvoiceBPAY',
            table='payments_invoicebpay'
        ),
        migrations.RunPython(update_contenttypes),
    ]

