# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0011_auto_20170331_1300'),
        ('invoice', '0010_auto_20170329_1131'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='invoicebpay',
            name='bpay',
        ),
        migrations.RemoveField(
            model_name='invoicebpay',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceBPAY',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
