# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-11 08:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInvoiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/view/', location='/data/data/projects/ledger_xzzy/private-media'), upload_to='oracleinvoice/%Y/%m/%d')),
                ('name', models.CharField(max_length=256)),
                ('extension', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='oracle_invoice_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='oracle_invoice_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oracle_invoice_file', to='invoice.OracleInvoiceDocument'),
        ),
    ]
