# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-18 06:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20250618_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidinvoice',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='unpaidinvoice',
            name='system',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
