# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-18 09:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20250618_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unpaidinvoice',
            old_name='status',
            new_name='due_status',
        ),
    ]
