# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-18 09:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20250618_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='unpaidinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
