# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-17 07:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20250618_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidinvoice',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
