# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-30 12:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_auto_20250717_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='voided_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
