# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0003_auto_20180307_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mooringarea',
            old_name='campground_type',
            new_name='mooring_type',
        ),
    ]
