# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-19 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0004_auto_20180403_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringarea',
            name='vessel_size_limit',
            field=models.IntegerField(default=0),
        ),
    ]
