# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0005_mooringarea_vessel_size_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mooringareastayhistory',
            old_name='campground',
            new_name='mooringarea',
        ),
    ]
