# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-15 03:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0006_auto_20180509_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wkb_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='mooring_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Online'), (1, 'Not Bookable Online'), (2, 'Public'), (3, 'Unpublished')], default=3),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='price_level',
            field=models.SmallIntegerField(choices=[(0, 'Marine Park level'), (1, 'Mooringsite Class level'), (2, 'Mooringsite level')], default=0),
        ),
    ]
