# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0007_auto_20180615_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'Campground'), (1, 'Mooringsite'), (2, 'Not Linked')], default=-1),
        ),
    ]
