# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0008_region_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinepark',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
        migrations.AlterField(
            model_name='region',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
    ]
