# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0034_auto_20180807_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='type',
            field=models.CharField(choices=[('vessel', 'Vessel')], max_length=10),
        ),
    ]
