# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-08 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0035_auto_20180807_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='vehicles',
            new_name='vessels',
        ),
    ]
