# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooring', '0036_auto_20180808_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('editable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overridden_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='override_reason_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='price_level',
            field=models.SmallIntegerField(choices=[(0, 'Mooring level'), (1, 'Mooringsite Class level')], default=0),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='site_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Per Site'), (1, 'Bookable Per Site Type')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='override_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.DiscountReason'),
        ),
    ]
