# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0036_auto_20180808_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringarea',
            name='price_level',
            field=models.SmallIntegerField(choices=[(0, 'Mooring level'), (1, 'Mooringsite Class level')], default=0),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='site_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Per Site'), (1, 'Bookable Per Site Type')], default=0),
        ),
    ]
