# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0037_auto_20180814_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='adult',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='child',
            field=models.DecimalField(decimal_places=2, default='2.20', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='concession',
            field=models.DecimalField(decimal_places=2, default='6.60', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='infant',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8, null=True),
        ),
    ]
