# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0037_auto_20180815_1253'),
        ('mooring', '0037_auto_20180814_1433'),
    ]

    operations = [
    ]
