# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0039_admissionsbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='expiryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
