# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0040_admissionsbooking_expirytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsbooking',
            name='warningReferenceNo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
