# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0041_booking_send_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringarea',
            name='vessel_draft_limit',
            field=models.IntegerField(default=0),
        ),
    ]
