# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0041_auto_20180821_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionsbooking',
            old_name='noOfChidlren',
            new_name='noOfChildren',
        ),
    ]
