# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0044_auto_20180823_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='bookingType',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'In-complete booking')], default=0),
        ),
        migrations.AddField(
            model_name='admissionsbooking',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
