# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-24 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0046_admissionsoraclecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionsbooking',
            old_name='bookingType',
            new_name='booking_type',
        ),
    ]
