# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0047_auto_20180824_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsBookingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('admissions_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='mooring.AdmissionsBooking')),
            ],
        ),
    ]
