# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0048_admissionsbookinginvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('adult_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('concession_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('children_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('infant_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
