# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0049_admissionsrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsrate',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
