# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0040_updateviews'),
        ('mooring', '0050_auto_20180828_0839'),
    ]

    operations = [
    ]
