# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0051_merge_20180830_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsrate',
            name='family_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='admissionsrate',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
