# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0052_auto_20180831_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsrate',
            name='reason',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mooring.PriceReason'),
            preserve_default=False,
        ),
    ]
