# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-04 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0054_auto_20180831_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('editable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='admissionsrate',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.AdmissionsReason'),
        ),
    ]
