# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0055_auto_20180904_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsreason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closurereason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountreason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maximumstayreason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openreason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricereason',
            name='detailRequired',
            field=models.BooleanField(default=False),
        ),
    ]
