# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0057_auto_20180906_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringarea',
            name='mooring_class',
            field=models.SmallIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=0),
        ),
        migrations.AddField(
            model_name='mooringarea',
            name='mooring_physical_type',
            field=models.SmallIntegerField(choices=[(0, 'Mooring'), (1, 'Jetty Pen')], default=0),
        ),
        migrations.AddField(
            model_name='mooringarea',
            name='vessel_beam_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mooringarea',
            name='vessel_draft_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mooringarea',
            name='vessel_weight_limit',
            field=models.IntegerField(default=0),
        ),
    ]
