# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0059_auto_20180907_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingperiod',
            name='booking_period',
        ),
        migrations.AddField(
            model_name='bookingperiod',
            name='booking_period',
            field=models.ManyToManyField(related_name='booking_period_options', to='mooring.BookingPeriodOption'),
        ),
    ]
