# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0060_auto_20180907_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiodoption',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bookingperiodoption',
            name='medium_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bookingperiodoption',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
    ]
