# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0066_mooringsitebooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringarea',
            name='mooring_class',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=0, max_length=20),
        ),
    ]
