# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0067_auto_20181003_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredVessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego_no', models.CharField(max_length=200)),
                ('vessel_size', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_draft', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_beam', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('vessel_weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('sticker_l', models.IntegerField(default=0)),
                ('sticker_au', models.IntegerField(default=0)),
                ('sticker_an', models.IntegerField(default=0)),
                ('expiry_l', models.DateField(blank=True, null=True)),
                ('expiry_au', models.DateField(blank=True, null=True)),
                ('expiry_an', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
