# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-06 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0069_auto_20181103_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvessels',
            name='sticker_an',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registeredvessels',
            name='sticker_au',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registeredvessels',
            name='sticker_l',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
