# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0070_mooringsitebooking_booking_period_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringarea',
            name='mooring_physical_type',
            field=models.SmallIntegerField(choices=[(0, 'Mooring'), (1, 'Jetty Pen'), (2, 'Beach Pen')], default=0),
        ),
    ]
