# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0071_auto_20181127_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiodoption',
            name='option_description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
    ]
