# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0073_overridereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringarea',
            name='admission_fee_required',
            field=models.BooleanField(default=False),
        ),
    ]
