# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0074_mooringarea_admission_fee_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverrideReason',
        ),
    ]
