# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0076_remove_mooringarea_admission_fee_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='old_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.Booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'Temporary reservation'), (4, 'Cancelled Booking'), (5, 'Changed Booking')], default=0),
        ),
        migrations.AlterField(
            model_name='mooringsitebooking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'Temporary reservation'), (4, 'Cancelled Booking'), (5, 'Changed Booking')], default=0),
        ),
    ]
