# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0077_auto_20181207_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='old_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.Booking'),
        ),
    ]
