# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0079_auto_20181214_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admission_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.AdmissionsBooking'),
        ),
    ]
