# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0081_refundpriceperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='refundpriceperiod',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='refundpriceperiod',
            name='calulation_type',
            field=models.SmallIntegerField(choices=[(0, 'Percentage'), (1, 'Fixed Price')], default=0),
        ),
        migrations.AddField(
            model_name='refundgroup',
            name='refund_period',
            field=models.ManyToManyField(related_name='refund_period_options', to='mooring.RefundPricePeriod'),
        ),
    ]
