# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0082_auto_20181218_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiodoption',
            name='refund_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.RefundGroup'),
        ),
    ]
