# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0083_bookingperiodoption_refund_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelPricePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calulation_type', models.SmallIntegerField(choices=[(0, 'Percentage'), (1, 'Fixed Price')], default=0)),
                ('percentage', models.FloatField()),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('days', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cancelgroup',
            name='cancel_period',
            field=models.ManyToManyField(related_name='cancel_period_options', to='mooring.CancelPricePeriod'),
        ),
    ]
