# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0084_auto_20181219_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiodoption',
            name='cancel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.CancelGroup'),
        ),
    ]
