# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0086_mooringsiteratelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooringsiteratelog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
