# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0088_mooringsiteratelog_change_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueSeqId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_seq', models.IntegerField(default=1)),
            ],
        ),
    ]
