# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0090_updateviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueSeqId',
        ),
    ]
