# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0092_auto_20190102_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SmallIntegerField(choices=[(0, 'Non Online Booking Fee'), (1, 'Max Stay'), (2, 'Max Advance Booking'), (3, 'Max Length Small'), (4, 'Max Length Medium'), (5, 'Max Length Large'), (6, 'Max Draft Small'), (7, 'Max Draft Medium'), (8, 'Max Draft Large'), (9, 'Max Beam Small'), (10, 'Max Beam Medium'), (11, 'Max Beam Large'), (12, 'Max Weight Small'), (13, 'Max Weight Medium'), (14, 'Max Weight Large')])),
                ('value', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='globalsettings',
            unique_together=set([('group', 'key')]),
        ),
    ]
