# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-03 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0094_auto_20190103_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredvessels',
            options={'verbose_name_plural': 'Registered Vessels'},
        ),
    ]
