# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-04 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0095_auto_20190103_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='group',
            new_name='mooring_group',
        ),
        migrations.AlterUniqueTogether(
            name='globalsettings',
            unique_together=set([('mooring_group', 'key')]),
        ),
    ]
