# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0097_admissionsrate_mooring_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsoraclecode',
            name='mooring_group',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, to='mooring.MooringAreaGroup'),
            preserve_default=False,
        ),
    ]
