# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0099_auto_20190110_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('mooring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup')),
            ],
        ),
    ]
