# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0101_admissionsline_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionslocation',
            name='key',
            field=models.CharField(default='ria', max_length=5),
            preserve_default=False,
        ),
    ]
