# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0102_admissionslocation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionslocation',
            name='key',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
