# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0103_auto_20190114_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsline',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.AdmissionsLocation'),
        ),
    ]
