# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0104_auto_20190114_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelpriceperiod',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changepriceperiod',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
