# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0106_auto_20190115_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsbooking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'In-complete booking'), (4, 'Cancelled booking')], default=0),
        ),
    ]
