# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0107_auto_20190116_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinepark',
            name='distance_radius',
            field=models.IntegerField(default=25),
        ),
    ]
