# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-18 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0108_marinepark_distance_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsreason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='closurereason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='discountreason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='district',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='marinepark',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='maximumstayreason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='openreason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='pricereason',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='promoarea',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
        migrations.AddField(
            model_name='region',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
    ]
