# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0112_auto_20190118_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepriceperiod',
            name='percentage',
            field=models.FloatField(blank=True),
        ),
    ]
