# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-25 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0114_auto_20190124_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingperiodoption',
            name='mooring_group',
        ),
        migrations.AddField(
            model_name='bookingperiod',
            name='mooring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.MooringAreaGroup'),
        ),
    ]
