# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-01 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0115_auto_20190125_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Refund Completed')], default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_refund', to='mooring.Booking')),
            ],
        ),
    ]
