# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0117_auto_20190201_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.AdmissionsLocation'),
        ),
    ]
