# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-07 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0118_admissionsbooking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundfailed',
            name='admission_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooring.AdmissionsBooking'),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_refund', to='mooring.Booking'),
        ),
    ]
