# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0119_auto_20190307_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiodoption',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
