# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0120_bookingperiodoption_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperiodoption',
            name='caption',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
