# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-02 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooring', '0123_admissionsbooking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='cancelation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionsbooking',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_bookings_admissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
