# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0124_auto_20190402_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringarea',
            name='vessel_beam_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='vessel_draft_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='vessel_size_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='vessel_weight_limit',
            field=models.FloatField(default=0),
        ),
    ]
