# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0125_auto_20190404_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooringarea',
            name='additional_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mooringarea',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
