# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0126_auto_20190410_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundfailed',
            name='basket_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
