# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0127_refundfailed_basket_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbookinginvoice',
            name='system_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='system_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
