# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-15 09:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0128_auto_20190611_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsbooking',
            name='override_lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='override_lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
