# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 08:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wildlifelicence_document'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='licence_type',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.WildlifeLicenceType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrow',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='additional_data_descriptors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
