# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 08:58
from __future__ import unicode_literals

import os

from django.db import migrations
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))


def load_fixture(apps, schema_editor):
    # call_command('loaddata', os.path.join(fixture_dir, 'returns.json'))
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
