# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0003_communicationslogentry'),
        ('wl_returns', '0002_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wl_main.CommunicationsLogEntry')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wl_returns.Return')),
            ],
            bases=('wl_main.communicationslogentry',),
        ),
    ]
