# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wildlifelicence_document'),
        ('returns', '0002_auto_20160524_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='licence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.WildlifeLicence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='return_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='returns.ReturnType'),
            preserve_default=False,
        ),
    ]
