# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_auto_20160525_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='due_date',
            field=models.DateField(default=datetime.date(2016, 5, 25)),
            preserve_default=False,
        ),
    ]
