# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0003_returnlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='return_templates'),
        ),
    ]
