# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_return_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returns.Return')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='returnrow',
            old_name='additional_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='returnrow',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='returnrow',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='returnrow',
            name='species',
        ),
        migrations.RemoveField(
            model_name='returnrow',
            name='species_count',
        ),
        migrations.RemoveField(
            model_name='returntype',
            name='additional_data_descriptors',
        ),
        migrations.AddField(
            model_name='returntype',
            name='data_descriptor',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrow',
            name='return_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='returns.ReturnTable'),
            preserve_default=False,
        ),
    ]
