# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0004_returntype_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='return',
            name='nil_return',
            field=models.BooleanField(default=False),
        ),
    ]
