# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_auto_20160530_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='month_frequency',
            field=models.IntegerField(choices=[(-1, 'One off'), (1, 'Monthy'), (3, 'Quarterly'), (6, 'Twice-Yearly'), (12, 'Yearly')], default=-1),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=20),
        ),
    ]
