# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0005_auto_20160822_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
