# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_auto_20160530_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='lodgement_sequence',
        ),
        migrations.AlterField(
            model_name='returntype',
            name='month_frequency',
            field=models.IntegerField(choices=[(-1, 'One off'), (1, 'Monthly'), (3, 'Quarterly'), (6, 'Twice-Yearly'), (12, 'Yearly')], default=-1),
        ),
    ]
