# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0006_auto_20160823_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntype',
            name='template',
        ),
    ]
