# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_returns', '0007_remove_returntype_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAmendmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('reason', models.TextField()),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('future', 'Future'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('amendment_required', 'Amendment Required'), ('amended', 'Amended'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='future', max_length=20),
        ),
        migrations.AddField(
            model_name='returnamendmentrequest',
            name='ret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wl_returns.Return'),
        ),
    ]
