# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('returns', '0007_auto_20160531_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='proxy_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
