# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0008_return_proxy_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('future', 'Future'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='future', max_length=20),
        ),
    ]
