# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 09:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleAccountCode',
            fields=[
                ('active_receivables_activities', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'payments_account_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OracleOpenPeriod',
            fields=[
                ('period_name', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('closing_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'payments_open_periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OracleInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('activity_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('line_item', models.TextField(blank=True, null=True)),
                ('status_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OracleInterfaceRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OracleInterfaceSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=10)),
                ('system_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OracleParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('date_parsed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OracleParserInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.OracleParser')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Cash'), (2, 'Bpoint'), (3, 'Bpay')])),
                ('refund_id', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='oracleinterfacerecipient',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='payments.OracleInterfaceSystem'),
        ),
    ]
