# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    database_operations = [
        migrations.CreateModel(
            name='OracleInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('activity_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('line_item', models.TextField(blank=True, null=True)),
                ('status_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedBpointToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('DVToken', models.CharField(max_length=128)),
            ],
        ),
        
    ]
    state_operations = [
        migrations.CreateModel(
            name='OracleInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('activity_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('line_item', models.TextField(blank=True, null=True)),
                ('status_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedBpointToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('DVToken', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelTable(
            name='bpayaccountrecord',
            table='payments_bpayaccountrecord',
        ),
        migrations.AlterModelTable(
            name='bpayaccounttrailer',
            table='payments_bpayaccounttrailer',
        ),
        migrations.AlterModelTable(
            name='bpayfile',
            table='payments_bpayfile',
        ),
        migrations.AlterModelTable(
            name='bpayfiletrailer',
            table='payments_bpayfiletrailer',
        ),
        migrations.AlterModelTable(
            name='bpaygrouprecord',
            table='payments_bpaygrouprecord',
        ),
        migrations.AlterModelTable(
            name='bpaygrouptrailer',
            table='payments_bpaygrouptrailer',
        ),
        migrations.AlterModelTable(
            name='bpaytransaction',
            table='payments_bpaytransaction',
        ),
        migrations.AlterModelTable(
            name='bpointtoken',
            table='payments_bpointtoken',
        ),
        migrations.AlterModelTable(
            name='bpointtransaction',
            table='payments_bpointtransaction',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='payments_invoice',
        ),
        migrations.AlterModelTable(
            name='invoicebpay',
            table='payments_invoicebpay',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=database_operations
        ),
    ]
