# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import ledger.payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterface',
            name='receipt_number',
            field=models.IntegerField(blank=True, default=ledger.payments.models.increment_receipt_number, null=True),
        ),
    ]
