# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170331_1308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bpayaccountrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpayaccounttrailer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpayfile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpayfiletrailer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpaygrouprecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpaygrouptrailer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpaytransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpointtoken',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bpointtransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invoicebpay',
            table=None,
        ),
    ]
