# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20171011_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage',
        ),
    ]
