# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170331_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterfaceRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OracleInterfaceSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=10)),
                ('system_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='oracleinterfacerecipients',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='payments.OracleInterfaceSystem'),
        ),
    ]
