# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170410_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OracleInterfaceRecipients',
            new_name='OracleInterfaceRecipient',
        ),
    ]
