# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20170410_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleparserinvoice',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.OracleParser'),
        ),
    ]
