# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_oracleinterfacesystem_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
