# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-03 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_oracleinterfacesystem_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterface',
            name='method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oracleinterface',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
