# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_update_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleAccountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_receivables_activities', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'payments_account_codes',
                'managed': False,
            },
        ),
    ]
