# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20180503_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
