# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_oracleaccountcode'),
        ('payments', '0008_cashtransaction_details'),
    ]

    operations = [
    ]
