# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20180530_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterface',
            name='method',
            field=models.CharField(default='Other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oracleinterface',
            name='source',
            field=models.CharField(default='Other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oracleinterfacesystem',
            name='method',
            field=models.CharField(default='Other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oracleinterfacesystem',
            name='source',
            field=models.CharField(default='Other', max_length=30),
            preserve_default=False,
        ),
    ]
