# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 01:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20180612_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='percentage_entrance_fee',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
