# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_oracleinterfacesystem_percentage_entrance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='percentage_account_code_entrance_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
