# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_refunduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefundUser',
            new_name='TrackRefund',
        ),
    ]
