# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 05:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_oracleinterfacesystem_percentage_account_code_entrance_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterfaceEntryfee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_entrance_fee', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('percentage_account_code_entrance_fee', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage_account_code_entrance_fee',
        ),
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage_entrance_fee',
        ),
        migrations.AddField(
            model_name='oracleinterfaceentryfee',
            name='entry_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance', to='payments.OracleInterfaceSystem'),
        ),
    ]
