# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20181019_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracleinterfaceentryfee',
            name='entry_fee',
        ),
        migrations.AddField(
            model_name='oracleinterfaceentryfee',
            name='oisystem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='OI_system', to='payments.OracleInterfaceSystem'),
            preserve_default=False,
        ),
    ]
