# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20170524_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackrefund',
            name='details',
            field=models.TextField(default='details'),
            preserve_default=False,
        ),
    ]
