# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 03:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20181022_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oracleinterfacededuction',
            old_name='percentage_account_code_entrance_fee',
            new_name='entrance_fee_account_code',
        ),
        migrations.RemoveField(
            model_name='oracleinterfacededuction',
            name='percentage_entrance_fee',
        ),
        migrations.AddField(
            model_name='oracleinterfacededuction',
            name='entrance_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
