# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_oracleopenperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='movement_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('reversal', 'reversal'), ('move_in', 'Move Funds In'), ('move_out', 'Move Funds out')], max_length=8),
        ),
    ]
