# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20181022_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracleinterfacededuction',
            name='entrance_fee',
        ),
        migrations.RemoveField(
            model_name='oracleinterfacededuction',
            name='entrance_fee_account_code',
        ),
        migrations.AlterField(
            model_name='oracleinterfacededuction',
            name='oisystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payments.OracleInterfaceSystem'),
        ),
    ]
