# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import ledger.payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20170927_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterface',
            name='receipt_number',
            field=models.IntegerField(blank=True, default=ledger.payments.models.increment_receipt_number, null=True),
        ),
    ]
