# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 11:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20181022_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracleinterfacededuction',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='oracleinterfacededuction',
            name='percentage_account_code',
        ),
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='percentage_account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
