# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20171010_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage',
        ),
    ]
