# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20181023_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterfaceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('percentage_account_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='oracleinterfacesystem',
            name='percentage_account_code',
        ),
        migrations.AddField(
            model_name='oracleinterfacededuction',
            name='oisystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payments.OracleInterfaceSystem'),
        ),
    ]
