# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 08:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20181023_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacededuction',
            name='destination_account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oracleinterfacededuction',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
