# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20181026_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oracleinterfacededuction',
            unique_together=set([('oisystem', 'percentage_account_code', 'destination_account_code')]),
        ),
    ]
