# Generated by Django 2.1.7 on 2019-04-24 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20181030_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterfacededuction',
            name='oisystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='payments.OracleInterfaceSystem'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacerecipient',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='payments.OracleInterfaceSystem'),
        ),
        migrations.AlterField(
            model_name='oracleparserinvoice',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.OracleParser'),
        ),
        migrations.AlterField(
            model_name='trackrefund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
