# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_oracleinterfacesystem_oracle_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(max_length=1000)),
                ('booking_reference', models.CharField(max_length=1000)),
                ('booking_reference_linked', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInvoiceGroupIncrementer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.OracleInterfaceSystem')),
            ],
        ),
        migrations.AddField(
            model_name='linkedinvoice',
            name='invoice_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.LinkedInvoiceGroupIncrementer'),
        ),
        migrations.AddField(
            model_name='linkedinvoice',
            name='system_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.OracleInterfaceSystem'),
        ),
    ]
