# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20211102_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinvoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedinvoicegroupincrementer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
