# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 07:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0025_auto_20211103_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=1000)),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Refund Completed')], default=0)),
                ('basket_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_failed_invoice_group', to='payments.LinkedInvoiceGroupIncrementer')),
                ('system_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.OracleInterfaceSystem')),
            ],
        ),
    ]
