# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_refundfailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterfaceReportReceipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_recipients', to='payments.OracleInterfaceSystem')),
            ],
        ),
    ]
