# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-29 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_paymenttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttotal',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
