# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_paymenttotal_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterfacePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting to disable permission')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracle_interface_permission_recipients', to='payments.OracleInterfaceSystem')),
            ],
        ),
    ]
