# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_oracleinterfacepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacepermission',
            name='access_type',
            field=models.IntegerField(blank=True, choices=[('all_access', 'Full access to all Financial Tools'), ('view_ledger_tools', 'View Ledger Payment Tools'), ('manage_ledger_tool', 'Manage Ledger Payment Tools')], default=None, null=True),
        ),
    ]
