# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_auto_20240228_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterfacepermission',
            name='access_type',
            field=models.CharField(blank=True, choices=[('all_access', 'Full access to all Financial Tools'), ('view_ledger_tools', 'View Ledger Payment Tools'), ('manage_ledger_tool', 'Manage Ledger Payment Tools'), ('view_payment_totals', 'View Payment Totals')], default=None, max_length=100, null=True),
        ),
    ]
