# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_auto_20240228_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('textarea', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
