# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_auto_20240702_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleinterfacepermission',
            name='access_type',
            field=models.CharField(blank=True, choices=[('all_access', 'Full access to all Financial Tools'), ('view_ledger_tools', 'View Ledger Payment Tools'), ('manage_ledger_tool', 'Manage Ledger Payment Tools'), ('view_payment_totals', 'View Payment Totals'), ('reports_access', 'Reports Access')], default=None, max_length=100, null=True),
        ),
    ]
