# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_oracleinterfacesystem_abn'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleAccountCodeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_code', models.CharField(max_length=50, unique=True)),
                ('tax_type', models.CharField(blank=True, choices=[('tax_exempt', 'Tax Exempt'), ('tax_gst', '10% GST Tax')], default=None, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
