# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-23 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_oracleaccountcodetax'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='send_debtor_report',
            field=models.NullBooleanField(default=False),
        ),
    ]
