# Generated by Django 5.2.9 on 2026-05-22 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_oracleinterfacesystem_send_debtor_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oracleinterfacesystem',
            name='payment_gateway_type',
            field=models.CharField(blank=True, choices=[('direct_api', 'DIRECT API'), ('hpp_redirect', 'HPP Redirect')], default='direct_api', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linkedinvoice',
            name='invoice_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linked_invoice_group', to='payments.linkedinvoicegroupincrementer'),
        ),
        migrations.AlterField(
            model_name='linkedinvoice',
            name='system_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='linkedinvoicegroupincrementer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linkedinvoicegroupincrementer',
            name='system_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='oracleaccountcodetax',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterface',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacededuction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacededuction',
            name='oisystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deductions', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacepermission',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='oracle_interface_permission_recipients', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacerecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacerecipient',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacereportreceipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacereportreceipient',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_recipients', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacesystem',
            name='bpoint_test',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='oracleinterfacesystem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleinterfacesystem',
            name='send_debtor_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oracleparser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleparserinvoice',
            name='details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='oracleparserinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oracleparserinvoice',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='payments.oracleparser'),
        ),
        migrations.AlterField(
            model_name='paymentinformationlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenttotal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenttotal',
            name='oracle_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_total_oracle_system', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='basket_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_failed_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='invoice_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_failed_invoice_group', to='payments.linkedinvoicegroupincrementer'),
        ),
        migrations.AlterField(
            model_name='refundfailed',
            name='system_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_failed_system_identifier', to='payments.oracleinterfacesystem'),
        ),
        migrations.AlterField(
            model_name='trackrefund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackrefund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_tracking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
