# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpointTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('reversal', 'reversal'), ('preauth', 'preauth'), ('capture', 'capture')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cardtype', models.CharField(blank=True, choices=[('AX', 'American Express'), ('DC', 'Diners Club'), ('JC', 'JCB Card'), ('MC', 'MasterCard'), ('VC', 'Visa')], max_length=2, null=True)),
                ('crn1', models.CharField(help_text='Reference for the order that the transaction was made for', max_length=50)),
                ('response_code', models.CharField(max_length=50)),
                ('response_txt', models.CharField(max_length=128)),
                ('receipt_number', models.CharField(max_length=50)),
                ('processed', models.DateTimeField()),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('callcentre', 'callcentre'), ('cardpresent', 'cardpresent'), ('ecommerce', 'ecommerce'), ('internet', 'internet'), ('ivr', 'ivr'), ('mailorder', 'mailorder'), ('telephoneorder', 'telephoneorder')], max_length=50)),
                ('txn_number', models.CharField(help_text='Transaction number used by BPOINT to identify a transaction', max_length=128, unique=True)),
                ('original_txn', models.ForeignKey(blank=True, help_text='Transaction number stored                                            if current transaction depends on a previous transaction                                            in the case where the action is a refund, reversal or capture', null=True, on_delete=django.db.models.deletion.CASCADE, to='bpoint.BpointTransaction', to_field='txn_number')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
