# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpointToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DVToken', models.CharField(max_length=128)),
                ('masked_card', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpoint_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
