# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0002_bpointtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpointtoken',
            name='card_type',
            field=models.CharField(blank=True, choices=[('AX', 'American Express'), ('DC', 'Diners Club'), ('JC', 'JCB Card'), ('MC', 'MasterCard'), ('VC', 'Visa')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bpointtoken',
            name='masked_card',
            field=models.CharField(max_length=50),
        ),
    ]
