# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0003_auto_20160726_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpointtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
