# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0004_auto_20160728_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set([('user', 'DVToken', 'masked_card', 'expiry_date', 'card_type')]),
        ),
    ]
