# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0005_auto_20160919_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set([('user', 'masked_card', 'expiry_date', 'card_type')]),
        ),
    ]
