# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


def content_forward(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    bpoint_qs = ContentType.objects.using(db_alias).filter(app_label='bpoint', model__in=('usedbpointtoken', 'bpointtoken', 'bpointtransaction'))
    bpoint_qs.update(app_label='payments')


def content_reverse(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    bpoint_qs = ContentType.objects.using(db_alias).filter(app_label='payments', model__in=('usedbpointtoken', 'bpointtoken', 'bpointtransaction'))
    bpoint_qs.update(app_label='bpoint')


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0007_usedbpointtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpointtransaction',
            name='dvtoken',
            field=models.CharField(blank=True, help_text='Stored card dv token', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bpointtransaction',
            name='last_digits',
            field=models.CharField(blank=True, help_text='Last four digits of card used during checkout', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='bpointtransaction',
            name='action',
            field=models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('unmatched_refund', 'unmatched_refund'), ('reversal', 'reversal'), ('preauth', 'preauth'), ('capture', 'capture')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='UsedBpointToken',
            table='payments_usedbpointtoken',
        ),
        migrations.AlterModelTable(
            name='BpointToken',
            table='payments_bpointtoken',
        ),
        migrations.AlterModelTable(
            name='BpointTransaction',
            table='payments_bpointtransaction',
        ),
        #migrations.RunPython(
        #    code=content_forward,
        #    reverse_code=content_reverse,
        #),

    ]
