# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0008_auto_20170316_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpointtransaction',
            name='action',
            field=models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('unmatched_refund', 'unmatched_refund'), ('reversal', 'reversal'), ('preauth', 'preauth'), ('capture', 'capture')], max_length=20),
        ),
    ]
