# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0008_parkstay_rebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpointtransaction',
            name='test_transaction',
            field=models.BooleanField(default=False, help_text='Transaction is in test mode'),
        ),
    ]
