# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:31
from __future__ import unicode_literals

from django.db import migrations

def update_contenttypes(apps, schema_editor):
    """
    Updates content types.
    We want to have the same content type id, when the model is moved and renamed.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    # Bpoint
    bpoint_qs = ContentType.objects.using(db_alias).filter(app_label='bpoint')
    bpoint_qs.update(app_label='payments')

class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0009_auto_20170321_1316'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='BpointToken',
            table='payments_bpointtoken'
        ),
        migrations.AlterModelTable(
            name='BpointTransaction',
            table='payments_bpointtransaction'
        ),
        migrations.RunPython(update_contenttypes),
    ]

