# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0009_bpointtransaction_test_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpointtransaction',
            old_name='test_transaction',
            new_name='is_test',
        ),
    ]
