# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0010_auto_20170329_1131'),
    ]

    state_operations = [
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bpointtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bpointtransaction',
            name='original_txn',
        ),
        migrations.DeleteModel(
            name='UsedBpointToken',
        ),
        migrations.DeleteModel(
            name='BpointToken',
        ),
        migrations.DeleteModel(
            name='BpointTransaction',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ] 
