# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0010_auto_20171026_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpointtransaction',
            name='original_txn',
            field=models.CharField(blank=True, help_text='Transaction number stored                                            if current transaction depends on a previous transaction                                            in the case where the action is a refund, reversal or capture', max_length=128, null=True),
        ),
    ]
