# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-25 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0012_bpointtransaction_original_crn1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpointtransaction',
            name='integrity_check',
            field=models.BooleanField(default=False),
        ),
    ]
