# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0013_bpointtransaction_integrity_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpointtransaction',
            name='integrity_check',
            field=models.NullBooleanField(default=False),
        ),
    ]
