# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-17 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bpoint', '0014_auto_20200930_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpointtoken',
            name='ois',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set([('user', 'masked_card', 'expiry_date', 'card_type', 'ois')]),
        ),
    ]
