# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-17 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bpoint', '0015_auto_20211217_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set([('user', 'masked_card', 'expiry_date', 'card_type')]),
        ),
    ]
