# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-19 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bpoint', '0018_auto_20211217_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpointTokenPrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bpoint_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpoint_token_primary', to='bpoint.BpointToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_primary_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
