# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-19 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0019_bpointtokenprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpointtokenprimary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_primary_card', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
