# Generated by Django 5.2.15 on 2026-07-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpoint', '0021_auto_20221019_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bpointtoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bpointtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bpointtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stored_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bpointtokenprimary',
            name='bpoint_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpoint_token_primary', to='bpoint.bpointtoken'),
        ),
        migrations.AlterField(
            model_name='bpointtokenprimary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bpointtokenprimary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_primary_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bpointtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bpointtransaction',
            name='integrity_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usedbpointtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
