# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160323_1350'),
        ('applications', '0002_auto_20160322_1727'),
        ('licence', '0004_make_licence_types')
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='licence_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licence.LicenceType'),
            preserve_default=False,
        ),
    ]
