# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0002_auto_20160610_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customlogentry',
            name='applicationlogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='emaillogentry',
            name='applicationlogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='amendmentrequest',
            name='applicationlogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='text',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='applicationlogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='idrequest',
            name='applicationlogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='returnsrequest',
            name='applicationlogentry_ptr',
        ),
    ]
