# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20160323_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='state',
            new_name='status',
        ),
    ]
