# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0004_auto_20160623_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_last_reminded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
