# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0004_auto_20160623_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_last_reminded',
            field=models.DateField(default=datetime.datetime(2016, 8, 8, 5, 34, 47, 803790, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
