# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0005_auto_20160801_1450'),
        ('wl_applications', '0005_assessment_date_last_reminded'),
    ]

    operations = [
    ]
