# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='order_number',
        ),
        migrations.AddField(
            model_name='application',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
