# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20160329_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lodged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
