# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0006_auto_20160815_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='processing_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('new', 'New'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('ready_for_action', 'Ready for Action'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('issued', 'Issued'), ('declined', 'Declined')], default='temp', max_length=30, verbose_name='Processing Status'),
        ),
    ]
