# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0007_auto_20160810_0951'),
        ('wl_applications', '0007_auto_20160822_1147'),
    ]

    operations = [
    ]
