# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_application_lodged_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_assessment', 'Awaiting Assessment'), ('assessed', 'Assessed')], max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assessorcomment',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='character_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_checked', max_length=20, verbose_name='Character Check Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='id_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_update', 'Awaiting Update'), ('updated', 'Updated'), ('checked', 'Checked')], default='not_checked', max_length=20, verbose_name='Identification Check Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_reviewed', max_length=20, verbose_name='Review Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('ready_for_action', 'Ready for Action'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='assessments',
            field=models.ManyToManyField(related_name='Assessments', through='applications.Assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessorcomment',
            name='assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.Assessment'),
            preserve_default=False,
        ),
    ]
