# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_licence_amendment',
            field=models.BooleanField(default=False),
        ),
    ]
