# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20160406_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status'),
        ),
    ]
