# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20160406_1519'),
        ('applications', '0010_amendmentrequest_status'),
    ]

    operations = [
    ]
