# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='lodged_date',
            new_name='lodgement_date',
        ),
        migrations.AddField(
            model_name='application',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='application',
            name='lodgement_sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
