# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160404_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0011_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='amendmentrequest',
            name='application',
        ),
        migrations.RemoveField(
            model_name='amendmentrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='amendmentrequest',
            name='text',
        ),
        migrations.RemoveField(
            model_name='application',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assessorcomment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessorcomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assessorcomment',
            name='text',
        ),
        migrations.CreateModel(
            name='AssessmentRequest',
            fields=[
                ('applicationlogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationLogEntry')),
                ('status', models.CharField(choices=[('awaiting_assessment', 'Awaiting Assessment'), ('assessed', 'Assessed')], default='awaiting_assessment', max_length=20, verbose_name='Status')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('applications.applicationlogentry',),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Document'),
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='applicationlogentry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationLogEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessorcomment',
            name='applicationlogentry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationLogEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessorcomment',
            name='assessment_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.AssessmentRequest'),
            preserve_default=False,
        ),
    ]
