# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20160411_1401'),
        ('applications', '0012_auto_20160412_0919'),
    ]

    operations = [
    ]
