# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_emaillogentry'),
        ('applications', '0013_merge'),
    ]

    operations = [
    ]
