# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160413_1355'),
        ('applications', '0014_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant_persona',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
