# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0015_applicationdeclineddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('new licence', 'New Licence'), ('amendment', 'Amendment'), ('renewal', 'Renewal')], default='new licence', max_length=40, verbose_name='Application Type'),
        ),
    ]
