# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assessordepartment'),
        ('applications', '0015_auto_20160413_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentrequest',
            name='assessor',
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='assessor_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.AssessorDepartment'),
            preserve_default=False,
        ),
    ]
