# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20160414_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='conditions',
        ),
    ]
