# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0017_migrate_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_licence_amendment',
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('new', 'New'), ('ready_for_action', 'Ready for Action'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('issued', 'Issued'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='temp', max_length=30, verbose_name='Processing Status'),
        ),
    ]
