# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20160420_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentRequest',
            new_name='Assessment',
        ),
    ]
