# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20160420_1008'),
        ('applications', '0020_auto_20160420_1612'),
    ]

    operations = [
    ]
