# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20160421_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='lodgement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
