# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20160428_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcondition',
            name='acceptance_status',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='not_specified', max_length=20, verbose_name='Acceptance Status'),
        ),
    ]
