# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_assessmentcondition_acceptance_status'),
        ('applications', '0025_auto_20160502_1217'),
    ]

    operations = [
    ]
