# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20160503_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
