# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20160504_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
                ('applicationlogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationLogEntry')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject / Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('applications.applicationlogentry',),
        ),
    ]
