# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_customlogentry'),
        ('applications', '0030_auto_20160503_1231'),
    ]

    operations = [
    ]
