# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_auto_20160511_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='license',
            new_name='licence',
        ),
    ]
