# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160517_1735'),
        ('applications', '0035_auto_20160511_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hard_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hard_copy', to='accounts.Document'),
        ),
    ]
