# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_application_hard_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsRequest',
            fields=[
                ('applicationlogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationLogEntry')),
                ('reason', models.CharField(choices=[('outstanding', 'There are currently outstanding returns for the previous licence'), ('other', 'Other')], default='outstanding', max_length=30, verbose_name='Reason')),
            ],
            options={
                'abstract': False,
            },
            bases=('applications.applicationlogentry',),
        ),
        migrations.AddField(
            model_name='application',
            name='returns_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_completion', 'Awaiting Completion'), ('completed', 'Completion'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Return Check Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('id_required', 'Identification Required'), ('return_completion_required', 'Return Completion Required'), ('amendment_required', 'Amendment Required'), ('id_and_amendment_required', 'Identification/Amendments Required'), ('id_and_returns_required', 'Identification/Returns Required'), ('returns_and_amendment_required', 'Returns/Amendments Required'), ('id_and_returns_and_amendment_required', 'Identification/Returns/Amendments Required'), ('approved', 'Approved'), ('declined', 'Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
    ]
