# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_auto_20160602_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='returns_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_returns', 'Awaiting Returns'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Return Check Status'),
        ),
    ]
