# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsiterate',
            name='rate_child',
            field=models.DecimalField(decimal_places=2, default='2.20', max_digits=8),
        ),
        migrations.AddField(
            model_name='campsiterate',
            name='rate_concession',
            field=models.DecimalField(decimal_places=2, default='6.60', max_digits=8),
        ),
        migrations.AddField(
            model_name='campsiterate',
            name='rate_infant',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
        migrations.AlterField(
            model_name='campgroundfeature',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
