# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='max_people',
        ),
    ]
