# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0002_auto_20161104_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrange',
            name='range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrange',
            name='range_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
