# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0002_auto_20160920_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsiterate',
            old_name='cost_per_day',
            new_name='rate_adult',
        ),
    ]
