# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0003_auto_20160920_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='features',
        ),
        migrations.AddField(
            model_name='campsiteclass',
            name='allow_campervan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsiteclass',
            name='allow_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsiteclass',
            name='allow_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsiteclass',
            name='parking_spaces',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campsiteclass',
            name='tents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CampsiteFeature',
        ),
    ]
