# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0003_auto_20161108_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 10, 0, 32, 47, 223622, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
