# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0004_auto_20160922_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='policies_disclaimers',
        ),
    ]
