# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0004_bookingrange_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrange',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 11, 5, 2, 50, 443881, tzinfo=utc), help_text='Used to check if the start and end dated were changed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrange',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Closed due to natural disaster'), (2, 'Closed for maintenance'), (3, 'Other')], default=0),
        ),
    ]
