# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0004_auto_20161019_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='check_in',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='campground',
            name='check_out',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
