# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0005_remove_campground_policies_disclaimers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='checkin_times',
            new_name='rules',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='mappinglink',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='metadescription',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='metatitle',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='timestamp',
        ),
    ]
