# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0005_auto_20161111_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingRange',
            new_name='CampgroundBookingRange',
        ),
    ]
