# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0006_auto_20160922_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='airports',
            new_name='fees',
        ),
    ]
