# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0007_campsitebookingrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='dog_permitted',
        ),
        migrations.AddField(
            model_name='campground',
            name='price_level',
            field=models.SmallIntegerField(choices=[(0, 'Campground level'), (1, 'Campsite Class level'), (2, 'Campsite level')], default=0),
        ),
    ]
