# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0007_auto_20160922_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='ratis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
