# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0008_auto_20161007_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.District'),
        ),
    ]
