# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0008_auto_20161114_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgroundbookingrange',
            name='campground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ranges', to='parkstay.Campground'),
        ),
    ]
