# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0009_auto_20161115_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.CustomerContact'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='promo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.PromoArea'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
