# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0010_auto_20161007_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='bookable_per_site',
            field=models.BooleanField(default=False),
        ),
    ]
