# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0010_auto_20161115_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsiteStayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('min_days', models.SmallIntegerField(default=1)),
                ('max_days', models.SmallIntegerField(default=28)),
                ('min_dba', models.SmallIntegerField(default=0)),
                ('max_dba', models.SmallIntegerField(default=180)),
                ('details', models.TextField(blank=True, null=True)),
                ('range_start', models.DateField(blank=True, null=True)),
                ('range_end', models.DateField(blank=True, null=True)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_history', to='parkstay.Campsite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='campgroundbookingrange',
            name='max_days',
        ),
        migrations.RemoveField(
            model_name='campgroundbookingrange',
            name='max_dba',
        ),
        migrations.RemoveField(
            model_name='campgroundbookingrange',
            name='min_days',
        ),
        migrations.RemoveField(
            model_name='campgroundbookingrange',
            name='min_dba',
        ),
        migrations.RemoveField(
            model_name='campsitebookingrange',
            name='max_days',
        ),
        migrations.RemoveField(
            model_name='campsitebookingrange',
            name='max_dba',
        ),
        migrations.RemoveField(
            model_name='campsitebookingrange',
            name='min_days',
        ),
        migrations.RemoveField(
            model_name='campsitebookingrange',
            name='min_dba',
        ),
    ]
