# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-22 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0012_campsiterate_update_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundPriceHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('rate_id', models.IntegerField()),
                ('adult', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concession', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'parkstay_campground_pricehistory_v',
                'managed': False,
            },
        ),
    ]
