# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-22 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0013_campgroundpricehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campsiterate',
            unique_together=set([('campsite', 'rate', 'date_start', 'date_end')]),
        ),
    ]
