# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0015_auto_20161125_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsiteclass',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
