# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0016_campsiteclass_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='cs_dimensions',
            field=models.CharField(default='6x4', max_length=12),
        ),
        migrations.AddField(
            model_name='campsite',
            name='cs_max_people',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='campsite',
            name='cs_min_people',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campsite',
            name='cs_number_vehicles',
            field=models.SmallIntegerField(choices=[(0, 'One vehicle'), (1, 'Two vehicles'), (2, 'One vehicle + small trailer'), (3, 'One vehicle + small trailer/large vehicle')], default=0),
        ),
        migrations.AddField(
            model_name='campsite',
            name='cs_parking_spaces',
            field=models.SmallIntegerField(choices=[(0, 'Parking within site.'), (1, 'Parking for exclusive use of site occupiers next to site, but separated from tent space.'), (2, 'Parking for exclusive use of occupiers, short walk from tent space.'), (3, 'Shared parking (not allocated), short walk from tent space.')], default=0),
        ),
        migrations.AddField(
            model_name='campsite',
            name='cs_tents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='campsite_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.CampsiteClass'),
        ),
    ]
