# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0017_auto_20161130_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='campsite_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campsites', to='parkstay.CampsiteClass'),
        ),
    ]
