# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0021_campgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgroundimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='/home/corporateict.domain/briank/apps/work/ledger-parkstay/media/Parkstay/CampgroudImages'),
        ),
    ]
