# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0022_auto_20161206_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campgroundimage',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='campgroundimage',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
