# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0024_closurereason_maximumstayreason_pricereason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closurereason',
            options={'ordering': ('id',), 'verbose_name': 'Availability Reason', 'verbose_name_plural': 'Availability Reasons'},
        ),
        migrations.AddField(
            model_name='closurereason',
            name='deletable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='maximumstayreason',
            name='deletable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='pricereason',
            name='deletable',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
