# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 03:03
from __future__ import unicode_literals
import os
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0025_auto_20161208_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closurereason',
            old_name='deletable',
            new_name='editable',
        ),
        migrations.RenameField(
            model_name='maximumstayreason',
            old_name='deletable',
            new_name='editable',
        ),
        migrations.RenameField(
            model_name='pricereason',
            old_name='deletable',
            new_name='editable',
        )
    ]
