# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 04:33
from __future__ import unicode_literals
import os

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))

def load_fixture(apps, schema_editor):
    call_command('loaddata', os.path.join(fixture_dir, 'closure_reasons.json'))
    call_command('loaddata', os.path.join(fixture_dir, 'open_reasons.json'))
    call_command('loaddata', os.path.join(fixture_dir, 'price_reasons.json'))
    call_command('loaddata', os.path.join(fixture_dir, 'max_stay_reasons.json'))


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0026_auto_20161208_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('editable', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='closurereason',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='campgroundbookingrange',
            name='closure_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkstay.ClosureReason'),
        ),
        migrations.AddField(
            model_name='campsitebookingrange',
            name='closure_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkstay.ClosureReason'),
        ),
        migrations.AlterField(
            model_name='campgroundbookingrange',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='campsitebookingrange',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
        migrations.AddField(
            model_name='campgroundbookingrange',
            name='open_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkstay.OpenReason'),
        ),
        migrations.AddField(
            model_name='campsitebookingrange',
            name='open_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkstay.OpenReason'),
        ),
        migrations.RunPython(load_fixture)
    ]
