# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0027_auto_20161208_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsiterate',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campsiterate',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkstay.PriceReason'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campsitestayhistory',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkstay.MaximumStayReason'),
            preserve_default=False,
        ),
    ]
