# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0029_auto_20161212_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Campground'), (1, 'Campsite'), (2, 'Not Linked')], default=2, help_text='Set the model where the feature is located.'),
        ),
    ]
