# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parkstay.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0032_updateviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='campground_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Online'), (1, 'Not Bookable Online'), (2, 'Other Accomodation')], default=0),
        ),
        migrations.AlterField(
            model_name='campground',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campgrounds', to='parkstay.Park'),
        ),
        migrations.AlterField(
            model_name='campgroundimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=parkstay.models.campground_image_path),
        ),
    ]
