# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0033_auto_20161219_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_campervan',
            new_name='campervan',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_caravan',
            new_name='caravan',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_max_people',
            new_name='max_people',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_min_people',
            new_name='min_people',
        ),
        migrations.RenameField(
            model_name='campsite',
            old_name='cs_tent',
            new_name='tent',
        ),
    ]
