# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0034_auto_20161222_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='tent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campsiteclass',
            name='tent',
            field=models.BooleanField(default=True),
        ),
    ]
