# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0036_parkstay_rebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
