# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 06:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0037_auto_20171011_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
