# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0038_auto_20171019_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
