# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0038_auto_20170118_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='info_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
