# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 00:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0039_booking_cancelation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cost_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('confirmation_sent', models.BooleanField()),
                ('campground', models.CharField(max_length=100)),
                ('campsites', django.contrib.postgres.fields.jsonb.JSONField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parkstay.Booking')),
            ],
        ),
    ]
