# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0039_campground_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campsitebooking',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkstay.Booking'),
        ),
        migrations.AlterField(
            model_name='campsitebooking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Reception booking'), (1, 'Internet booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0),
        ),
    ]
