# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0039_campground_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='max_advance_booking',
            field=models.IntegerField(default=180),
        ),
    ]
