# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0040_campground_max_advance_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVehicleRego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rego', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regos', to='parkstay.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
