# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 01:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0041_bookinghistory_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='vehicles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
