# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0040_auto_20170120_1557'),
        ('parkstay', '0042_campgroundstayhistory'),
    ]

    operations = [
    ]
