# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0043_merge_20170131_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkEntryRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('concession', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('motorbike', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkstay.PriceReason')),
            ],
        ),
    ]
