# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkstay', '0043_bookinghistory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
