# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0044_auto_20171108_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
