# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0044_parkentryrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='entry_fee',
        ),
    ]
