# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0045_campground_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campgroundbookingrange',
            name='open_reason',
        ),
        migrations.RemoveField(
            model_name='campsitebookingrange',
            name='open_reason',
        ),
        migrations.DeleteModel(
            name='OpenReason',
        ),
    ]
