# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0047_auto_20170224_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginvoice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='parkstay.Booking'),
        ),
    ]
