# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0048_auto_20180429_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
