# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0048_auto_20170224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkentryrate',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
