# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0049_auto_20170224_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
