# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-17 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0049_auto_20180517_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='override_price',
        ),
    ]
