# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0050_booking_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('activity_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('line_item', models.TextField(blank=True, null=True)),
                ('status_date', models.DateField()),
            ],
        ),
    ]
