# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0050_remove_bookinghistory_override_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='max_vehicles',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
