# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0051_oracleinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('motorbike', 'Motorcycle'), ('concession', 'Vehicle (concession)')], max_length=10),
        ),
    ]
