# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0052_booking_override_reason_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='send_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
