# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0053_delete_oracleinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
