# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0054_campground_oracle_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='legacy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
