# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0054_auto_20180803_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='send_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
