# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 08:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0055_auto_20170404_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
