# Generated by Django 2.1.7 on 2019-04-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0055_auto_20181220_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='campground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.Campground'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='parkstay.Booking'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoice'),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parkstay.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regos', to='parkstay.Booking'),
        ),
    ]
