# Generated by Django 2.1.7 on 2019-05-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0056_auto_20190424_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regos', to='parkstay.Booking'),
        ),
    ]
