# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0057_auto_20170407_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='campground_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Online'), (1, 'Not Bookable Online'), (2, 'Other Accomodation'), (3, 'Unpublished')], default=3),
        ),
        #migrations.AddField(
        #    model_name='campsiteclass',
        #    name='max_vehicles',
        #    field=models.PositiveIntegerField(default=1),
        #),
    ]
