# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0059_auto_20170410_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
