# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0060_park_oracle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvehiclerego',
            name='entry_fee',
            field=models.BooleanField(default=False),
        ),
    ]
