# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0061_bookingvehiclerego_entry_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
