# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:57
from __future__ import unicode_literals

from django.db import migrations, models

def forward_func(apps, schema_editor):
    Booking = apps.get_model('parkstay','Booking')

    for b in Booking.objects.all():
        b.confirmation_sent = True
        b.save()

def reverse_func(apps, schema_editor):
    Booking = apps.get_model('parkstay','Booking')

    for b in Booking.objects.all():
        b.confirmation_sent = False 
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0062_booking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forward_func, reverse_func)
    ]
