# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0063_booking_confirmation_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingBookingRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
