# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0064_outstandingbookingrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
