# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0066_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingvehiclerego',
            unique_together=set([('booking', 'rego')]),
        ),
    ]
