# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import parkstay.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0067_auto_20170830_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='campground_map',
            field=models.FileField(blank=True, null=True, upload_to=parkstay.models.update_campground_map_filename),
        ),
    ]
