# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkstay', '0068_campground_campground_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campgrounds', models.ManyToManyField(blank=True, to='parkstay.Campground')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
