# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0069_campgroundgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvehiclerego',
            name='park_entry_fee',
            field=models.BooleanField(default=False),
        ),
    ]
