# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_useraddress_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='profile_address',
        ),
    ]
