# Generated by Django 5.2.14 on 2026-05-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_useraddress_country_alter_useraddress_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together=set(),
        ),
    ]
