# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('payment', 'payment'), ('refund', 'refund')], max_length=7)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='invoice.Invoice', to_field='reference')),
                ('original_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.CashTransaction')),
            ],
        ),
    ]
