# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='source',
            field=models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('money_order', 'money_order')], default='cash', max_length=11),
            preserve_default=False,
        ),
    ]
