# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20160727_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='receipt_number',
            new_name='receipt',
        ),
    ]
