# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20160728_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('reversal', 'reversal')], max_length=8),
        ),
    ]
