# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:31
from __future__ import unicode_literals

from django.db import migrations

def update_contenttypes(apps, schema_editor):
    """
    Updates content types.
    We want to have the same content type id, when the model is moved and renamed.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    #Cash
    cash_qs = ContentType.objects.using(db_alias).filter(app_label='cash')
    cash_qs.update(app_label='payments')

class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_auto_20170206_0841'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='CashTransaction',
            table='payments_cashtransaction'
        ),
        migrations.AlterModelTable(
            name='Region',
            table='payments_region'
        ),
        migrations.AlterModelTable(
            name='District',
            table='payments_district'
        ),
        migrations.RunPython(update_contenttypes),
    ]

