# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models

def content_forward(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    cash_qs = ContentType.objects.using(db_alias).filter(app_label='cash', model__in=('cashtransaction', 'region', 'district'))
    cash_qs.update(app_label='payments')


def content_reverse(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    cash_qs = ContentType.objects.using(db_alias).filter(app_label='payments', model__in=('cashtransaction', 'region', 'district'))
    cash_qs.update(app_label='cash')


def rename_eft(apps, schema_editor):
    CashTransaction = apps.get_model('cash','CashTransaction')
    try:
        for c in CashTransaction.objects.all():
            if c.source == 'eft':
                c.source = 'eftpos'
                c.save()
    except Exception as e:
        raise e



class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_auto_20170206_0841'),
    ]

    operations = [
        migrations.RunPython(
            code=rename_eft,
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='type',
            field=models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('reversal', 'reversal'), ('move_in', 'Move Funds In'), ('move_out', 'Move Funds out')], max_length=8),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='movement_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

        migrations.AlterModelTable(
            name='CashTransaction',
            table='payments_cashtransaction',
        ),
        migrations.AlterModelTable(
            name='Region',
            table='payments_region',
        ),
        migrations.AlterModelTable(
            name='District',
            table='payments_district',
        ),
        #migrations.RunPython(
        #    code=content_forward,
        #    reverse_code=content_reverse,
        #),
    ]
