# Generated by Django 2.1.7 on 2019-04-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_parkstay_rebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='invoice.Invoice', to_field='reference'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='original_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.CashTransaction'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='cash.Region'),
        ),
    ]
