# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_make_wildlife_licence_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='identification_required',
            field=models.BooleanField(default=False),
        ),
    ]
