# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0004_wildlifelicencetype_application_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='locations',
            field=models.TextField(blank=True),
        ),
    ]
