# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wildlifelicencetype_identification_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='default_conditions',
            field=models.ManyToManyField(blank=True, to='main.Condition'),
        ),
    ]
