# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0005_wildlifelicence_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='code_slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
