# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0006_auto_20160801_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceCategory'),
        ),
    ]
