# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0007_auto_20160801_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
    ]
