# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160414_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessordepartment',
            name='default_conditions',
            field=models.ManyToManyField(blank=True, to='main.Condition'),
        ),
    ]
