# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_assessordepartment_default_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessordepartment',
            name='default_conditions',
        ),
        migrations.AddField(
            model_name='assessordepartment',
            name='suggested_conditions',
            field=models.ManyToManyField(blank=True, to='main.Condition'),
        ),
    ]
