# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0009_auto_20160815_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
    ]
