# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160414_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Condition')),
            ],
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='default_conditions',
        ),
        migrations.AddField(
            model_name='defaultcondition',
            name='wildlife_licence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WildlifeLicenceType'),
        ),
    ]
