# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0010_auto_20160817_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationslogentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
