# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160418_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='default_conditions',
            field=models.ManyToManyField(blank=True, through='main.DefaultCondition', to='main.Condition'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultcondition',
            unique_together=set([('condition', 'wildlife_licence_type', 'order')]),
        ),
    ]
