# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160418_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
