# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0011_communicationslogentry_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicence',
            name='regions',
            field=models.ManyToManyField(to='wl_main.Region'),
        ),
    ]
