# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160419_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
