# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('wl_main', '0012_auto_20160824_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationslogentry',
            name='document',
        ),
        migrations.AddField(
            model_name='communicationslogentry',
            name='documents',
            field=models.ManyToManyField(blank=True, to='accounts.Document'),
        ),
    ]
