# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0013_auto_20160824_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationslogentry',
            name='cc',
            field=models.CharField(blank=True, max_length=200, verbose_name='cc'),
        ),
    ]
