# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge'),
        ('main', '0015_auto_20160503_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Document'),
        ),
    ]
