# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0015_auto_20160901_1436'),
        ('wl_main', '0015_wildlifelicencetype_senior_applicable'),
    ]

    operations = [
    ]
