# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0016_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wildlifelicencecategory',
            options={'verbose_name_plural': 'Wildlife licence categories'},
        ),
    ]
