# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0017_auto_20160902_1158'),
        ('wl_main', '0016_auto_20160905_1118'),
    ]

    operations = [
    ]
