# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160525_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='return_frequency',
            field=models.IntegerField(default=-1),
        ),
    ]
