# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
