# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0019_auto_20160905_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildlifelicence',
            old_name='previous_licence',
            new_name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='sequence_number',
        ),
        migrations.AddField(
            model_name='wildlifelicence',
            name='renewal_sent',
            field=models.BooleanField(default=False),
        ),
    ]
