# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160531_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='code_slug',
            field=models.SlugField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
