# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 05:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0020_auto_20161011_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='extracted_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
