# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0020_auto_20161011_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='help_text',
            field=models.TextField(blank=True),
        ),
    ]
