# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0021_wildlifelicence_extracted_fields'),
        ('wl_main', '0021_auto_20161018_1741'),
    ]

    operations = [
    ]
