# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0022_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product_code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='product_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
