# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0024_auto_20161104_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='default_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Licence Period (days)'),
        ),
    ]
