# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField(help_text=b'Unique species reference', verbose_name=b'Name ID')),
                ('species_name', models.CharField(db_index=True, max_length=256)),
                ('consv_code', models.CharField(blank=True, help_text=b'', max_length=10, null=True, verbose_name=b'Conservation status')),
                ('source', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['species_name'],
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False, help_text=b'True if every species name in the file has been validated against Herbie', verbose_name=b'Validated')),
                ('comments', models.TextField(blank=True, help_text=b'', verbose_name=b'Comments')),
                ('file', models.FileField(upload_to=b'%Y/%m/%d')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
