# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 07:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wildlifecompliance.components.applications.models
import wildlifecompliance.components.licences.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20180207_1210'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('new_licence', 'New Licence'), ('amendment', 'Amendment'), ('renewal', 'Renewal')], default='new_licence', max_length=40, verbose_name='Application Type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('assessor_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('comment_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('proposed_issuance_licence', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('customer_status', models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='temp', max_length=40, verbose_name='Customer Status')),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('lodgement_sequence', models.IntegerField(blank=True, default=0)),
                ('lodgement_date', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_assessor_conditions', 'With Assessor (Conditions)'), ('with_approver', 'With Approver'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='temp', max_length=30, verbose_name='Processing Status')),
                ('id_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_update', 'Awaiting Update'), ('updated', 'Updated'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Identification Check Status')),
                ('return_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_returns', 'Awaiting Returns'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Return Check Status')),
                ('character_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Character Check Status')),
                ('review_status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status')),
                ('proposed_decline_status', models.BooleanField(default=False)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tenure', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationApproverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssessorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('free_condition', models.TextField(blank=True, null=True)),
                ('standard', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.BooleanField(default=False)),
                ('recurrence_pattern', models.SmallIntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')], default=1)),
                ('recurrence_schedule', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='wildlifecompliance.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('cc_email', models.TextField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Application')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.applications.models.update_application_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.applications.models.update_application_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStandardCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activities', taggit.managers.TaggableManager(help_text='A comma-separated list of activities.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Activities')),
                ('site', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='wildlifecompliance.Application')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='CommunicationsLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=200, verbose_name='To')),
                ('fromm', models.CharField(blank=True, max_length=200, verbose_name='From')),
                ('cc', models.CharField(blank=True, max_length=200, verbose_name='cc')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('main', 'Mail'), ('person', 'In Person')], default='email', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject / Description')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended')], default='current', max_length=40)),
                ('activity', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('tenure', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('renewal_sent', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('original_issue_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('surrender_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('suspension_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extracted_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.licences.models.update_licence_doc_filename)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.Licence')),
            ],
        ),
        migrations.CreateModel(
            name='LicenceUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='wildlifecompliance.Licence')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_one', models.CharField(blank=True, max_length=50)),
                ('pin_two', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationAccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='wildlifecompliance.Organisation')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128, verbose_name='Given name(s)')),
                ('last_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number')),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='fax number')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wildlifecompliance.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ABN')),
                ('identification', models.FileField(blank=True, null=True, upload_to='organisation/requests/%Y/%m/%d')),
                ('status', models.CharField(choices=[('with_assessor', 'With Assessor'), ('approved', 'Approved'), ('declined', 'Declined')], default='with_assessor', max_length=100)),
                ('lodgement_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_request_assignee', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.OrganisationRequest')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='wildlifecompliance.OrganisationRequest')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_referral', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='wildlifecompliance.Application')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_referalls', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_assessor_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('processing_status', models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'With Assessor'), ('approved', 'Approved')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='wildlifecompliance.Application')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_return_assignments', to=settings.AUTH_USER_MODEL)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='wildlifecompliance.Licence')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedApplicationApproverGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_taggedapplicationapprovergroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedApplicationApproverGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_taggedapplicationapprovergroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedApplicationAssessorGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_taggedapplicationassessorgroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedApplicationAssessorGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_taggedapplicationassessorgroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentRequest',
            fields=[
                ('applicationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.ApplicationRequest')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('reason', models.CharField(choices=[('insufficient_detail', 'The information provided was insufficient'), ('missing_information', 'There was missing information'), ('other', 'Other')], default='insufficient_detail', max_length=30, verbose_name='Reason')),
            ],
            bases=('wildlifecompliance.applicationrequest',),
        ),
        migrations.CreateModel(
            name='ApplicationLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('applicationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.ApplicationRequest')),
                ('status', models.CharField(choices=[('awaiting_assessment', 'Awaiting Assessment'), ('assessed', 'Assessed'), ('assessment_expired', 'Assessment Period Expired')], default='awaiting_assessment', max_length=20, verbose_name='Status')),
                ('date_last_reminded', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('assigned_assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wildlifecompliance.applicationrequest',),
        ),
        migrations.CreateModel(
            name='LicenceLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='OrganisationLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='OrganisationRequestLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.OrganisationRequest')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('applicationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.ApplicationRequest')),
                ('reason', models.CharField(choices=[('outstanding', 'There are currently outstanding returns for the previous licence'), ('other', 'Other')], default='outstanding', max_length=30, verbose_name='Reason')),
            ],
            bases=('wildlifecompliance.applicationrequest',),
        ),
        migrations.AddField(
            model_name='organisation',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='wildlifecompliance_organisations', through='wildlifecompliance.UserDelegation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organisation'),
        ),
        migrations.AddField(
            model_name='licence',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wildlifecompliance_licences', to='wildlifecompliance.Organisation'),
        ),
        migrations.AddField(
            model_name='licence',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_document', to='wildlifecompliance.LicenceDocument'),
        ),
        migrations.AddField(
            model_name='licence',
            name='current_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wildlifecompliance.Application'),
        ),
        migrations.AddField(
            model_name='licence',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence_document', to='wildlifecompliance.LicenceDocument'),
        ),
        migrations.AddField(
            model_name='licence',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Licence'),
        ),
        migrations.AddField(
            model_name='communicationslogentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Application'),
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationcondition',
            name='standard_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationStandardCondition'),
        ),
        migrations.AddField(
            model_name='applicationassessorgroup',
            name='activities',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of activities.', through='wildlifecompliance.TaggedApplicationAssessorGroupActivities', to='taggit.Tag', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='applicationassessorgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationassessorgroup',
            name='regions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of regions.', through='wildlifecompliance.TaggedApplicationAssessorGroupRegions', to='taggit.Tag', verbose_name='Regions'),
        ),
        migrations.AddField(
            model_name='applicationapprovergroup',
            name='activities',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of activities.', through='wildlifecompliance.TaggedApplicationApproverGroupActivities', to='taggit.Tag', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='applicationapprovergroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationapprovergroup',
            name='regions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of regions.', through='wildlifecompliance.TaggedApplicationApproverGroupRegions', to='taggit.Tag', verbose_name='Regions'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='wildlifecompliance.Organisation'),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_applications_licences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_applications_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Licence'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.Application'),
        ),
        migrations.AddField(
            model_name='application',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_proxy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildlifecompliance_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdelegation',
            unique_together=set([('organisation', 'user')]),
        ),
        migrations.AddField(
            model_name='organisationlogentry',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationcontact',
            unique_together=set([('organisation', 'email')]),
        ),
        migrations.AddField(
            model_name='licencelogentry',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.Licence'),
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.Application'),
        ),
        migrations.AddField(
            model_name='applicationlogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.ApplicationLogEntry'),
        ),
    ]
