# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='pin_one',
            new_name='admin_pin_one',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='pin_two',
            new_name='admin_pin_two',
        ),
        migrations.AddField(
            model_name='organisation',
            name='user_pin_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='user_pin_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisationcontact',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationcontact',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
