# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-19 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0002_auto_20180216_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationcontact',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='organisationcontact',
            name='role',
        ),
    ]
