# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0003_auto_20180219_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcontact',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationcontact',
            name='user_role',
            field=models.CharField(choices=[('company_admin', 'Company Admin'), ('company_user', 'Company User')], default='company_admin', max_length=40, verbose_name='Role'),
        ),
    ]
