# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0004_auto_20180220_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcontact',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organisationcontact',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationcontact',
            name='user_role',
            field=models.CharField(choices=[('company_admin', 'Company Admin'), ('company_user', 'Company User')], default='company_user', max_length=40, verbose_name='Role'),
        ),
    ]
