# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0005_auto_20180220_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationContactDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='organisationcontact',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('decline', 'Decline'), ('suspended', 'Suspended')], default='pending', max_length=40, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='organisationcontactdeclineddetails',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.OrganisationContact'),
        ),
    ]
