# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-26 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0008_auto_20180223_1256'),
        ('wildlifecompliance', '0002_auto_20180223_1127'),
    ]

    operations = [
    ]
