# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0009_merge_20180226_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontact',
            name='user_role',
            field=models.CharField(choices=[('organisation_admin', 'Organisation Admin'), ('organisation_user', 'Organisation User')], default='organisation_user', max_length=40, verbose_name='Role'),
        ),
    ]
