# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0010_auto_20180307_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationrequestlogentry',
            options={'ordering': ['-created']},
        ),
    ]
