# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0012_auto_20180307_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='role',
            field=models.CharField(
                choices=[
                    ('employee',
                     'Employee'),
                    ('auth_agent',
                     'Authorised Agent')],
                default='employee',
                max_length=100),
        ),
    ]
