# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0014_auto_20180308_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontact',
            name='user_role',
            field=models.CharField(choices=[('organisation_admin', 'Organisation Admin'), ('organisation_user', 'Organisation User'), ('consultant', 'Consultant')], default='organisation_user', max_length=40, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('consultant', 'Consultant')], default='employee', max_length=100),
        ),
    ]
