# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_auto_20160802_0859'),
        ('wildlifecompliance', '0015_auto_20180308_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceCategory',
            fields=[
                ('licencetype_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='licence.LicenceType')),
                ('licence_category_status',
                 models.CharField(
                     choices=[
                         ('current',
                          'Current'),
                         ('expired',
                          'Expired'),
                         ('cancelled',
                          'Cancelled'),
                         ('surrendered',
                          'Surrendered'),
                         ('suspended',
                          'Suspended')],
                     default='current',
                     max_length=40)),
            ],
            bases=(
                'licence.licencetype',
            ),
        ),
    ]
