# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0016_wildlifelicencecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceActivityType',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100)),
            ],
        ),
    ]
