# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0017_wildlifelicenceactivitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencecategory',
            name='activity',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
