# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0018_wildlifelicencecategory_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicencecategory',
            name='activity',
        ),
        migrations.AddField(
            model_name='wildlifelicenceactivitytype',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceCategory'),
        ),
    ]
