# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0019_auto_20180321_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicenceactivitytype',
            name='category',
        ),
        migrations.AddField(
            model_name='wildlifelicenceactivitytype',
            name='category',
            field=models.ManyToManyField(null=True, to='wildlifecompliance.WildlifeLicenceCategory'),
        ),
    ]
