# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0020_auto_20180321_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicenceactivitytype',
            name='category',
            field=models.ManyToManyField(to='wildlifecompliance.WildlifeLicenceCategory'),
        ),
    ]
