# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0023_auto_20180321_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultActivity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('activity_type',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='wildlifecompliance.WildlifeLicenceActivityType')),
                ('category',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='wildlifecompliance.WildlifeLicenceCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='defaultactivity',
            unique_together=set(
                [
                    ('category',
                     'activity_type')]),
        ),
    ]
