# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0024_auto_20180321_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicencecategory',
            name='activity',            
        ),
         migrations.AddField(
            model_name='wildlifelicencecategory',
            name='activity',
            field=models.ManyToManyField(blank=True, through='wildlifecompliance.DefaultActivity', to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
        
    ]
