# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0025_auto_20180321_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicencecategory',
            name='activity',
        ),
    ]
