# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0026_remove_wildlifelicencecategory_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencecategory',
            name='activity',
            field=models.ManyToManyField(blank=True, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
