# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0030_auto_20180321_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
