# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0032_auto_20180326_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicenceactivitytype',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='wildlifecompliance_activity', through='wildlifecompliance.DefaultActivity', to='wildlifecompliance.WildlifeLicenceActivity'),
        ),
    ]
