# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0033_wildlifelicenceactivitytype_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivity'),
        ),
        migrations.AddField(
            model_name='application',
            name='licence_activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
        migrations.AddField(
            model_name='application',
            name='licence_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceCategory'),
        ),
    ]
