# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0034_auto_20180326_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicenceactivitytype',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
