# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0038_auto_20180404_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildlifeLicenceCategory',
            new_name='WildlifeLicenceClass',
        ),
        migrations.RenameField(
            model_name='defaultactivitytype',
            old_name='category',
            new_name='licence_class',
        ),
        migrations.RenameField(
            model_name='wildlifelicenceclass',
            old_name='licence_category_status',
            new_name='licence_class_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='licence_category',
        ),
        migrations.AlterUniqueTogether(
            name='defaultactivitytype',
            unique_together=set([('licence_class', 'activity_type')]),
        ),
    ]
