# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-27 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0039_auto_20180426_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_type_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                null=True),
        ),
    ]
