# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0039_auto_20180424_1459'),
        ('wildlifecompliance', '0041_auto_20180427_1955'),
    ]

    operations = [
    ]
