# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-03 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance',
         '0042_merge_20180430_1546'),
        ('wildlifecompliance',
         '0043_wildlifelicenceactivitytype_licence_activity_status'),
    ]

    operations = [
    ]
