# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0044_merge_20180503_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('with_assessor',
                     'With Assessor'),
                    ('amendment_requested',
                     'Amendment Requested'),
                    ('approved',
                     'Approved'),
                    ('declined',
                     'Declined')],
                default='with_assessor',
                max_length=100),
        ),
    ]
