# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0046_auto_20180531_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('licence_activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType')),
                ('licence_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceClass')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
