# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0047_applicationgrouptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='activity_type',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
