# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance',
         '0048_applicationdeclineddetails_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdeclineddetails',
            name='activity_type',
            field=models.ForeignKey(
                default=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
