# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0049_auto_20180619_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeclineddetails',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='activity_type',
            field=models.ManyToManyField(
                default=False,
                null=True,
                to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
