# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0050_auto_20180619_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdeclineddetails',
            name='activity_type',
            field=models.ManyToManyField(default=False, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
