# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0051_auto_20180619_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeclineddetails',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='activity_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
