# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0048_auto_20180621_1413'),
        ('wildlifecompliance', '0052_auto_20180619_1440'),
    ]

    operations = [
    ]
