# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-29 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0052_auto_20180619_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessor_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ApplicationGroupType'),
        ),
    ]
