# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0054_assessment_licence_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgrouptype',
            name='name',
            field=models.CharField(
                choices=[
                    ('officer',
                     'Officer'),
                    ('assessor',
                     'Assessor')],
                default='officer',
                max_length=40,
                verbose_name='Group Type'),
        ),
    ]
