# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0054_auto_20180622_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='org_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_applications', to='wildlifecompliance.Organisation'),
        ),
    ]
