# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 00:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0055_auto_20180704_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='licence_activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
