# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0056_auto_20180704_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='licence_activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
