# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0056_auto_20180628_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicenceactivity',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
