# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 00:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0058_remove_assessment_licence_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='activity_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                null=True),
        ),
    ]
