# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-06 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0059_assessment_activity_type'),
        ('wildlifecompliance', '0057_wildlifelicenceactivity_short_name'),
    ]

    operations = [
    ]
