# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-10 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0060_auto_20180709_0858'),
        ('wildlifecompliance', '0060_merge_20180706_1027'),
    ]

    operations = [
    ]
