# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0061_merge_20180710_0932'),
        ('wildlifecompliance', '0061_amendmentrequest_licence_activity_type'),
    ]

    operations = [
    ]
