# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0062_merge_20180711_0921'),
        ('wildlifecompliance', '0062_merge_20180710_1254'),
    ]

    operations = [
    ]
