# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0062_merge_20180711_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_fee',
            field=models.DecimalField(
                decimal_places=2,
                default='0',
                max_digits=8),
        ),
    ]
