# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0064_wildlifelicenceactivity_base_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
