# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0063_merge_20180711_1003'),
        ('wildlifecompliance', '0065_application_licence_type_name'),
    ]

    operations = [
    ]
