# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0066_merge_20180730_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInvoice',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('invoice_reference',
                 models.CharField(
                     blank=True,
                     default='',
                     max_length=50,
                     null=True)),
                ('application',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='invoices',
                     to='wildlifecompliance.Application')),
            ],
        ),
    ]
