# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0068_assessment_licence_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationgrouptype',
            name='display_name',
            field=models.CharField(
                default='Assessor test',
                max_length=40,
                verbose_name='Display Group Name'),
            preserve_default=False,
        ),
    ]
