# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0067_applicationinvoice'),
        ('wildlifecompliance', '0069_applicationgrouptype_display_name'),
    ]

    operations = [
    ]
