# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0070_merge_20180803_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicenceactivity',
            name='short_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='wildlifelicenceactivitytype',
            name='short_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
