# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0071_auto_20180816_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildlifelicenceactivity',
            old_name='base_fee',
            new_name='base_application_fee',
        ),
        migrations.AddField(
            model_name='wildlifelicenceactivity',
            name='base_licence_fee',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
