# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0072_auto_20180816_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_fee',
            field=models.DecimalField(
                decimal_places=2,
                default='0',
                max_digits=8),
        ),
    ]
