# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0075_wildlifelicenceactivitytype_not_for_organisation'),
        ('wildlifecompliance', '0072_applicationcondition_licence_activity_type'),
    ]

    operations = [
    ]
