# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-07 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0076_merge_20180905_1225'),
        ('wildlifecompliance', '0074_applicationcondition_is_default'),
    ]

    operations = [
    ]
