# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0077_merge_20180907_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='is_activity_renewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='licence_activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdeclineddetails',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('propose_decline', 'Propose Decline'), ('declined', 'Declined'), ('propose_issue', 'Propose Issue'), ('issued', 'Issued')], default='default', max_length=20, verbose_name='Status'),
        ),
    ]
