# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0079_applicationdecisionpropose'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationdecisionpropose',
            unique_together=set([('application', 'licence_activity_type')]),
        ),
    ]
