# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0083_auto_20180924_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdecisionpropose',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='wildlifecompliance.Application'),
        ),
    ]
