# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0085_wildlifelicence_parent_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='licence_activity_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceActivityType'),
        ),
    ]
