# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0086_wildlifelicence_licence_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='applicant',
        ),
    ]
