# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0087_remove_wildlifelicence_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='org_applicant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wildlifecompliance_org_applicant',
                to='wildlifecompliance.Organisation'),
        ),
        migrations.AddField(
            model_name='wildlifelicence',
            name='proxy_applicant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wildlifecompliance_proxy_applicant',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wildlifelicence',
            name='submitter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wildlifecompliance_submitter',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
