# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0088_auto_20180927_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicence',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
