# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0089_auto_20180927_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdecisionpropose',
            name='action',
        ),
        migrations.AddField(
            model_name='applicationdecisionpropose',
            name='decision_action',
            field=models.CharField(choices=[('default', 'Default'), ('declined', 'Declined'), ('issued', 'Issued')], default='default', max_length=20, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='applicationdecisionpropose',
            name='proposed_action',
            field=models.CharField(choices=[('default', 'Default'), ('propose_decline', 'Propose Decline'), ('propose_issue', 'Propose Issue')], default='default', max_length=20, verbose_name='Action'),
        ),
    ]
