# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0090_auto_20181011_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
