# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0092_auto_20181023_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='customer_status',
            field=models.CharField(
                choices=[
                    ('due',
                     'Due'),
                    ('future',
                     'Future'),
                    ('with_assessor',
                     'Under Review'),
                    ('approved',
                     'Approved'),
                    ('discarded',
                     'Discarded')],
                default='future',
                max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='lodgement_date',
            field=models.DateTimeField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='lodgement_number',
            field=models.CharField(
                blank=True,
                default='',
                max_length=9),
        ),
        migrations.AddField(
            model_name='return',
            name='post_reminder_sent',
            field=models.BooleanField(
                default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='reminder_sent',
            field=models.BooleanField(
                default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='submitter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='disturbance_compliances',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
