# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0094_remove_returntype_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
