# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0095_returntype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntype',
            name='Name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
