# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 01:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0097_return_return_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRow',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('data',
                 django.contrib.postgres.fields.jsonb.JSONField(
                     blank=True,
                     null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnTable',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=50)),
                ('ret',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='wildlifecompliance.Return')),
            ],
        ),
        migrations.AddField(
            model_name='returnrow',
            name='return_table',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.ReturnTable'),
        ),
    ]
