# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-08 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0091_applicationdocument_can_delete'),
        ('wildlifecompliance', '0097_return_return_type'),
    ]

    operations = [
    ]
