# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0098_auto_20181114_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='nil_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='return',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('under_review', 'Under Review'), ('accepted', 'Accepted')], default='overdue', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('with_curator', 'With Curator'), ('accepted', 'Accepted')], max_length=20),
        ),
    ]
