# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0098_merge_20181108_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
