# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 11:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0099_application_licence_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=24)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issued', models.NullBooleanField(default=None)),
                ('processed', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_applications', to='wildlifecompliance.Application')),
            ],
        ),
        migrations.AddField(
            model_name='excelactivitytype',
            name='excel_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_activity_types', to='wildlifecompliance.ExcelApplication'),
        ),
        migrations.AlterUniqueTogether(
            name='excelactivitytype',
            unique_together=set([('excel_app', 'short_name')]),
        ),
    ]
