# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0100_auto_20181128_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelactivitytype',
            name='name',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
