# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0101_excelactivitytype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicenceactivity',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
