# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0102_wildlifelicenceactivity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelactivitytype',
            name='activity_name',
            field=models.CharField(blank=True, max_length=68),
        ),
        migrations.AlterField(
            model_name='excelactivitytype',
            name='name',
            field=models.CharField(blank=True, max_length=68),
        ),
    ]
