# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0103_auto_20181130_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='licence_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wildlifelicence',
            name='licence_sequence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='wildlifelicence',
            unique_together=set([('licence_number', 'licence_sequence')]),
        ),
    ]
