# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0105_wildlifelicence_licence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicence',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='licence_sequence',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='tenure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
