# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-11 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0099_auto_20181210_0826'),
        ('wildlifecompliance', '0106_auto_20181207_2342'),
    ]

    operations = [
    ]
