# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0107_merge_20181211_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelactivitytype',
            name='short_name',
            field=models.CharField(blank=True, max_length=68),
        ),
    ]
