# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-11 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0109_returnlogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnlogentry',
            old_name='returns',
            new_name='return_obj',
        ),
    ]
