# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0109_auto_20181219_1048'),
        ('wildlifecompliance', '0109_merge_20181218_1558'),
    ]

    operations = [
    ]
