# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0108_auto_20181213_1432'),
        ('wildlifecompliance', '0108_auto_20181217_2300'),
        ('wildlifecompliance', '0110_auto_20181212_0139'),
    ]

    operations = [
    ]
