# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0110_merge_20181219_1524'),
        ('wildlifecompliance', '0110_auto_20181212_0139'),
    ]

    operations = [
    ]
