# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-23 07:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0111_merge_20181221_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=68)),
                ('name', models.CharField(max_length=68)),
                ('short_name', models.CharField(max_length=68)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('advanced', models.NullBooleanField(default=None, verbose_name='Standard/Advanced')),
                ('conditions', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('to_be_issued', models.NullBooleanField(default=None)),
                ('processed', models.NullBooleanField(default=None)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activity_types', to='wildlifecompliance.Application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicationactivitytype',
            unique_together=set([('application', 'short_name')]),
        ),
    ]
