# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0111_merge_20181221_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='wildlifecompliance/organisation/requests/%Y/%m/%d'),
        ),
    ]
