# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0112_auto_20181223_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationactivitytype',
            name='code',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
    ]
