# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-03 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0112_auto_20181224_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationgrouptype',
            options={'verbose_name': 'Licence activity group', 'verbose_name_plural': 'Licence activity groups'},
        ),
    ]
