# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-03 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0113_applicationactivitytype_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wildlifelicence',
            unique_together=set([('licence_number', 'licence_sequence', 'licence_class', 'licence_type')]),
        ),
    ]
