# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-04 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0113_auto_20190103_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationaccessgroup',
            options={'verbose_name_plural': 'Organisation Access Group'},
        ),
    ]
