# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0114_auto_20190103_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf_licence',
            field=models.FileField(default=1, upload_to=wildlifecompliance.components.applications.models.update_pdf_licence_filename),
            preserve_default=False,
        ),
    ]
