# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-11 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0114_auto_20190104_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationType',
        ),
    ]
