# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-18 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0115_auto_20190111_0943'),
        ('wildlifecompliance', '0111_merge_20181219_1050'),
    ]

    operations = [
    ]
