# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0115_application_pdf_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pdf_licence',
            field=models.FileField(blank=True, null=True, upload_to=wildlifecompliance.components.applications.models.update_pdf_licence_filename),
        ),
    ]
