# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0118_auto_20190121_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='licence_activities',
            field=models.ManyToManyField(blank=True, to='wildlifecompliance.WildlifeLicenceActivity'),
        ),
        migrations.AddField(
            model_name='wildlifelicenceactivity',
            name='licence_activity_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceActivityType'
            ),
        ),
        migrations.AddField(
            model_name='wildlifelicenceactivity',
            name='licence_class',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wildlifecompliance.WildlifeLicenceClass'
            ),
        ),
        migrations.RunSQL("""
            UPDATE wildlifecompliance_wildlifelicenceactivity AS activity
                SET licence_activity_type_id = da.activity_type_id
            FROM
                wildlifecompliance_defaultactivity AS da
            WHERE
                activity.ID = da.activity_id;
        """, reverse_sql=""),
        migrations.RunSQL("""
            UPDATE wildlifecompliance_wildlifelicenceactivity AS activity
                SET licence_class_id = da.licence_class_id
            FROM
                wildlifecompliance_defaultactivitytype AS da
            WHERE
                activity.licence_activity_type_id = da.activity_type_id;
        """, reverse_sql=""),
    ]
