# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-26 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0119_auto_20190222_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='licence_category',
        ),
        migrations.RemoveField(
            model_name='application',
            name='licence_type_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='licence_type_name',
        ),
    ]
