# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-27 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0120_auto_20190226_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationapprovergroup',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='applicationapprovergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='applicationapprovergroup',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='applicationassessorgroup',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='applicationassessorgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='applicationassessorgroup',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationapprovergroupactivities',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationapprovergroupactivities',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationapprovergroupregions',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationapprovergroupregions',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationassessorgroupactivities',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationassessorgroupactivities',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationassessorgroupregions',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedapplicationassessorgroupregions',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ApplicationApproverGroup',
        ),
        migrations.DeleteModel(
            name='ApplicationAssessorGroup',
        ),
        migrations.DeleteModel(
            name='TaggedApplicationApproverGroupActivities',
        ),
        migrations.DeleteModel(
            name='TaggedApplicationApproverGroupRegions',
        ),
        migrations.DeleteModel(
            name='TaggedApplicationAssessorGroupActivities',
        ),
        migrations.DeleteModel(
            name='TaggedApplicationAssessorGroupRegions',
        ),
    ]
