# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-27 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0116_auto_20190104_1119'),
        ('wildlifecompliance', '0120_auto_20190226_1118'),
    ]

    operations = [
    ]
