# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-27 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0121_merge_20190227_1421'),
        ('wildlifecompliance', '0121_auto_20190227_1314'),
    ]

    operations = [
    ]
