# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0122_merge_20190227_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('amendment_required', 'Amendment Required'), ('accepted', 'Accepted'), ('partially_approved', 'Partially Approved'), ('declined', 'Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_officer', 'With Officer'), ('with_assessor', 'With Assessor'), ('with_assessor_conditions', 'With Assessor (Conditions)'), ('with_approver', 'With Approver'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('under_review', 'Under Review')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
