# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0123_auto_20190227_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='application',
            name='region',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tenure',
        ),
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
    ]
