# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0125_auto_20190228_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildlifeLicenceActivity',
            new_name='LicencePurpose',
        ),
    ]
