# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0128_auto_20190228_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultActivity',
            new_name='DefaultPurpose',
        ),
    ]
