# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0130_auto_20190228_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='licence_activities',
            new_name='licence_purposes',
        ),
        migrations.RenameField(
            model_name='defaultpurpose',
            old_name='activity',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='licenceactivity',
            old_name='activity',
            new_name='purpose',
        ),
        migrations.AlterUniqueTogether(
            name='defaultpurpose',
            unique_together=set([('activity_type', 'purpose')]),
        ),
    ]
