# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0131_auto_20190301_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencepurpose',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='licencepurpose',
            old_name='licence_class',
            new_name='licence_category',
        ),
    ]
