# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0132_auto_20190301_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amendmentrequest',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='applicationcondition',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='applicationdecisionpropose',
            old_name='activity_type',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='applicationdecisionpropose',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='applicationdeclineddetails',
            old_name='activity_type',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='applicationdeclineddetails',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='applicationgrouptype',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='activity_type',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='defaultactivity',
            old_name='activity_type',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='defaultcondition',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RenameField(
            model_name='defaultpurpose',
            old_name='activity_type',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='wildlifelicence',
            old_name='licence_activity_type',
            new_name='licence_activity',
        ),
        migrations.RemoveField(
            model_name='licencecategory',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='licencecategory',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='wildlifecompliance_activities', through='wildlifecompliance.DefaultActivity', to='wildlifecompliance.LicenceActivity'),
        ),
        migrations.AlterField(
            model_name='applicationactivitytype',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activities', to='wildlifecompliance.Application'),
        ),
        migrations.AlterField(
            model_name='excelactivitytype',
            name='excel_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_activities', to='wildlifecompliance.ExcelApplication'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultactivity',
            unique_together=set([('licence_class', 'activity')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultpurpose',
            unique_together=set([('activity', 'purpose')]),
        ),
    ]
