# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0133_auto_20190301_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationActivityType',
            new_name='ApplicationActivity',
        ),
    ]
