# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0134_auto_20190301_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelActivityType',
            new_name='ExcelActivity',
        ),
    ]
