# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0135_auto_20190301_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationgrouptype',
            old_name='licence_class',
            new_name='licence_category',
        ),
        migrations.RenameField(
            model_name='defaultactivity',
            old_name='licence_class',
            new_name='licence_category',
        ),
        migrations.RenameField(
            model_name='licencecategory',
            old_name='licence_class_status',
            new_name='licence_category_status',
        ),
        migrations.RenameField(
            model_name='wildlifelicence',
            old_name='licence_class',
            new_name='licence_category',
        ),
        migrations.AlterUniqueTogether(
            name='defaultactivity',
            unique_together=set([('licence_category', 'activity')]),
        ),
        migrations.AlterUniqueTogether(
            name='wildlifelicence',
            unique_together=set([('licence_number', 'licence_sequence', 'licence_category', 'licence_type')]),
        ),
    ]
