# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0138_auto_20190301_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='applicationactivity',
            name='application',
        ),
        migrations.DeleteModel(
            name='ApplicationActivity',
        ),
    ]
