# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-06 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0139_auto_20190301_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excelactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='excelactivity',
            name='excel_app',
        ),
        migrations.RemoveField(
            model_name='excelapplication',
            name='application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='assigned_approver',
        ),
        migrations.DeleteModel(
            name='ExcelActivity',
        ),
        migrations.DeleteModel(
            name='ExcelApplication',
        ),
    ]
