# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-06 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0139_auto_20190301_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationGroupType',
            new_name='ActivityPermissionGroup',
        ),
    ]
