# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-06 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0140_auto_20190306_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypermissiongroup',
            old_name='type',
            new_name='group_type',
        ),
    ]
