# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('wildlifecompliance', '0141_auto_20190306_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaccessgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='organisationaccessgroup',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='activitypermissiongroup',
            options={'verbose_name': 'Activity permission group', 'verbose_name_plural': 'Activity permission groups'},
        ),
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='licence_activity',
        ),
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='licence_category',
        ),
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='name',
        ),
        migrations.AddField(
            model_name='activitypermissiongroup',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitypermissiongroup',
            name='licence_activities',
            field=models.ManyToManyField(blank=True, to='wildlifecompliance.LicenceActivity'),
        ),
        migrations.DeleteModel(
            name='OrganisationAccessGroup',
        ),
    ]
