# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-06 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0142_auto_20190306_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypermissiongroup',
            name='group_type',
        ),
    ]
