# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-07 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0140_auto_20190306_1623'),
        ('wildlifecompliance', '0143_remove_activitypermissiongroup_group_type'),
    ]

    operations = [
    ]
