# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-08 08:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0144_merge_20190307_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('open_followup', 'Open (follow-up)'), ('open_inspection', 'Open (Inspection)'), ('open_case', 'Open (Case)'), ('closed', 'Closed')], default='draft', max_length=40)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Call/Email',
                'verbose_name_plural': 'Calls/Emails',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='callemail',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='wildlifecompliance.Classification'),
        ),
    ]
