# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0145_licenceactivity_licence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='cc',
            field=models.TextField(blank=True, verbose_name='cc'),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='to',
            field=models.TextField(blank=True, verbose_name='To'),
        ),
    ]
