# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-14 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0145_auto_20190308_1606'),
        ('wildlifecompliance', '0146_auto_20190308_1626'),
    ]

    operations = [
    ]
