# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0146_auto_20190308_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntype',
            name='return_type',
            field=models.CharField(choices=[('sheet', 'Sheet'), ('question', 'Question'), ('data', 'Data')], default='sheet', max_length=30, verbose_name='Type'),
        ),
    ]
