# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-19 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0147_returntype_return_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wildlifelicence',
            unique_together=set([('licence_number', 'licence_sequence', 'licence_category')]),
        ),
        migrations.RemoveField(
            model_name='licenceactivity',
            name='licence_activity_status',
        ),
        migrations.RemoveField(
            model_name='licencecategory',
            name='licence_category_status',
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='activity_status',
            field=models.CharField(choices=[('default', 'Default'), ('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended')], default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='original_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='renewal_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='current_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Application'),
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='licence_activity',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='licence_type',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='org_applicant',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='original_issue_date',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='parent_licence',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='proxy_applicant',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='region',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='renewal_sent',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='surrender_details',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='suspension_details',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='tenure',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='title',
        ),
    ]
