# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0148_auto_20190321_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='lodged_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
