# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0148_auto_20190319_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='assessor_data',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assigned_assessor',
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_activities', to='wildlifecompliance.Application'),
        ),
    ]
