# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0149_auto_20190320_1535'),
        ('wildlifecompliance', '0149_auto_20190320_1708'),
    ]

    operations = [
    ]
