# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-21 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0150_merge_20190320_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='processing_status',
        ),
    ]
