# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-26 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0149_auto_20190322_1207'),
        ('wildlifecompliance', '0151_remove_application_processing_status'),
    ]

    operations = [
    ]
