# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0152_auto_20190326_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeclineddetails',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationdeclineddetails',
            name='licence_activity',
        ),
        migrations.RemoveField(
            model_name='applicationdeclineddetails',
            name='officer',
        ),
        migrations.RenameField(
            model_name='communicationslogentry',
            old_name='type',
            new_name='log_type'
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='log_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationcondition',
            name='recurrence_pattern',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('under_review', 'Under Review'), ('accepted', 'Accepted')], default='future', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('with_curator', 'With Curator'), ('accepted', 'Accepted')], default='future', max_length=20),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='data_format',
            field=models.CharField(choices=[('sheet', 'Sheet'), ('question', 'Question'), ('data', 'Data')], default='sheet', max_length=30, verbose_name='Data format'),
        ),
        migrations.DeleteModel(
            name='ApplicationDeclinedDetails',
        ),
    ]
