# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0147_merge_20190314_1451'),
        ('wildlifecompliance', '0152_auto_20190326_1328'),
    ]

    operations = [
    ]
