# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0153_auto_20190401_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
