# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0152_auto_20190326_1328'),
        ('wildlifecompliance', '0153_auto_20190328_1635'),
    ]

    operations = [
    ]
