# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0153_auto_20190401_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=512, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=256, null=True)),
                ('instance_name', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data_records', to='wildlifecompliance.Application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicationformdatarecord',
            unique_together=set([('application', 'field_name')]),
        ),
    ]
