# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 05:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0153_auto_20190401_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=512, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=256, null=True)),
                ('instance_name', models.CharField(blank=True, max_length=256, null=True)),
                ('component_type', models.CharField(choices=[('text', 'Text'), ('tab', 'Tab'), ('section', 'Section'), ('group', 'Group'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('multi-select', 'Multi-Select'), ('text_area', 'Text Area'), ('table', 'Table'), ('expander_table', 'Expander Table'), ('label', 'Label'), ('radiobuttons', 'Radio'), ('checkbox', 'Checkbox'), ('declaration', 'Declaration'), ('file', 'File'), ('date', 'Date')], default='text', max_length=64)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('deficiency', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='data',
        ),
        migrations.AddField(
            model_name='applicationformdatarecord',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data_records', to='wildlifecompliance.Application'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationformdatarecord',
            unique_together=set([('application', 'field_name')]),
        ),
    ]
