# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0154_auto_20190409_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to=wildlifecompliance.components.applications.models.update_assessment_inspection_report_filename),
        ),
    ]
