# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0153_merge_20190329_1056'),
        ('wildlifecompliance', '0154_merge_20190329_0935'),
    ]

    operations = [
    ]
