# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0155_auto_20190409_1729'),
        ('wildlifecompliance', '0155_auto_20190412_1545'),
    ]

    operations = [
    ]
