# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-11 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0155_auto_20190409_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='customer_status',
        ),
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_officer', 'With Officer'), ('with_assessor', 'With Assessor'), ('with_officer_conditions', 'With Officer-Conditions'), ('with_officer_finalisation', 'With Officer-Finalisation'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='return',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('draft', 'Draft'), ('future', 'Future'), ('with_curator', 'With Curator'), ('accepted', 'Accepted'), ('payment', 'Awaiting Payment')], default='future', max_length=20),
        ),
    ]
