# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-04 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0155_merge_20190329_1202'),
        ('wildlifecompliance', '0153_auto_20190401_1535'),
    ]

    operations = [
    ]
