# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-15 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0156_merge_20190412_1626'),
        ('wildlifecompliance', '0156_auto_20190411_1013'),
    ]

    operations = [
    ]
