# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-25 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0157_merge_20190415_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returntype',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='returntype',
            unique_together=set([('name', 'version')]),
        ),
    ]
