# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-08 07:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0157_auto_20190405_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=100)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('age', models.CharField(choices=[('baby', 'Baby'), ('juvenile', 'Juvenile'), ('adult', 'Adult')], default='baby', max_length=20)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('advice_given', models.BooleanField(default=False)),
                ('advice_details', models.CharField(blank=True, max_length=500)),
                ('referred_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Referrers')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_type', models.CharField(choices=[('bird', 'Bird'), ('mammal', 'Mammal'), ('snake', 'Snake'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('non-wildlife', 'Non-Wildlife'), ('other', 'Other')], default='bird', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='callemail',
            name='occurrence_date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='callemail',
            name='occurrence_date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='callemail',
            name='occurrence_time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='callemail',
            name='occurrence_time_to',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.SpeciesType'),
        ),
        migrations.AddField(
            model_name='report',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Species'),
        ),
        migrations.AddField(
            model_name='report',
            name='species_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.SpeciesType'),
        ),
        migrations.AddField(
            model_name='callemail',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Report'),
        ),
    ]
