# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-26 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0158_auto_20190423_1830'),
        ('wildlifecompliance', '0158_auto_20190425_1605'),
    ]

    operations = [
    ]
