# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-26 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0159_returntype_data_template'),
        ('wildlifecompliance', '0159_merge_20190426_1042'),
    ]

    operations = [
    ]
