# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0160_merge_20190426_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
