# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-11 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0160_auto_20190409_1118'),
        ('wildlifecompliance', '0155_auto_20190409_1729'),
    ]

    operations = [
    ]
