# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-30 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0160_merge_20190426_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='purpose',
        ),
    ]
