# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-11 04:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0161_merge_20190411_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_type', models.CharField(choices=[('bird', 'Bird'), ('mammal', 'Mammal'), ('snake', 'Snake'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('non-wildlife', 'Non-Wildlife'), ('other', 'Other')], default='bird', max_length=50)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='referred_to',
        ),
        migrations.RemoveField(
            model_name='report',
            name='species',
        ),
        migrations.RemoveField(
            model_name='report',
            name='species_type',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_type',
        ),
        migrations.RemoveField(
            model_name='callemail',
            name='report',
        ),
        migrations.AddField(
            model_name='callemail',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='SpeciesType',
        ),
        migrations.AddField(
            model_name='callemail',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ReportType'),
        ),
    ]
