# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-30 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0161_remove_applicationselectedactivity_purpose'),
        ('wildlifecompliance', '0161_organisationrequest_lodgement_number'),
    ]

    operations = [
    ]
