# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.returns.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0162_merge_20190430_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='comment',
            new_name='final_comment',
        ),
        migrations.AddField(
            model_name='applicationselectedactivity',
            name='is_inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='inspection_comment',
            field=models.TextField(blank=True),
        ),
    ]
