# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-11 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0162_auto_20190411_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='species_type',
            new_name='report_type',
        ),
    ]
