# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-02 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0163_auto_20190502_1008'),
        ('wildlifecompliance', '0163_auto_20190501_1429'),
    ]

    operations = [
    ]
