# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-18 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0163_auto_20190411_1235'),
        ('wildlifecompliance', '0157_merge_20190415_1103'),
    ]

    operations = [
    ]
