# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-23 06:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0164_merge_20190415_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callemail',
            options={'verbose_name': 'CM_Call/Email', 'verbose_name_plural': 'CM_Calls/Emails'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'CM_Classification', 'verbose_name_plural': 'CM_Classifications'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'CM_Location', 'verbose_name_plural': 'CM_Locations'},
        ),
        migrations.AlterModelOptions(
            name='referrer',
            options={'verbose_name': 'CM_Referrer', 'verbose_name_plural': 'CM_Referrers'},
        ),
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name': 'CM_ReportType', 'verbose_name_plural': 'CM_ReportTypes'},
        ),
        migrations.AddField(
            model_name='location',
            name='wkb_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='report_type',
            field=models.CharField(max_length=50),
        ),
    ]
