# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-03 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0164_merge_20190502_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='activity',
        ),
        migrations.AddField(
            model_name='assessment',
            name='actioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
