# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-17 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0165_auto_20190416_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callemail',
            old_name='data',
            new_name='stored_renderer_data',
        ),
    ]
