# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-17 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0166_auto_20190417_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callemail',
            old_name='stored_renderer_data',
            new_name='data',
        ),
    ]
