# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0167_auto_20190515_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('new_licence', 'New'), ('new_activity', 'New Activity'), ('amend_activity', 'Amendment'), ('renew_activity', 'Renewal')], default='new_licence', max_length=40, verbose_name='Application Type'),
        ),
    ]
