# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-18 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0167_auto_20190417_1601'),
        ('wildlifecompliance', '0164_merge_20190418_0908'),
    ]

    operations = [
    ]
