# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-17 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0168_auto_20190515_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationselectedactivity',
            old_name='officer',
            new_name='updated_by',
        ),
    ]
