# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-17 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0169_auto_20190517_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pdf_licence',
        ),
    ]
