# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0170_compliancedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='version_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
