# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-17 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0170_remove_application_pdf_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lodgement_sequence',
        ),
        migrations.RemoveField(
            model_name='licencedocument',
            name='licence',
        ),
    ]
