# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-22 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0171_auto_20190517_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='is_activity_renewable',
        ),
    ]
