# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-22 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0172_remove_applicationselectedactivity_is_activity_renewable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationselectedactivity',
            name='renewal_sent',
        ),
    ]
