# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0174_auto_20190524_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('under_review', 'Under Review'), ('amendment_required', 'Amendment Required'), ('accepted', 'Accepted'), ('partially_approved', 'Partially Approved'), ('declined', 'Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
    ]
