# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-27 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0174_merge_20190426_1731'),
        ('wildlifecompliance', '0165_auto_20190423_1424'),
    ]

    operations = [
    ]
