# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-29 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0175_merge_20190427_1257'),
        ('wildlifecompliance', '0174_merge_20190426_1804'),
    ]

    operations = [
    ]
