# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0176_merge_20190429_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_call', to='wildlifecompliance.Classification'),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_call', to='wildlifecompliance.Location'),
        ),
    ]
