# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0176_auto_20190528_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationselectedactivity',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_officer', 'With Officer'), ('with_assessor', 'With Assessor'), ('with_officer_conditions', 'With Officer-Conditions'), ('with_officer_finalisation', 'With Officer-Finalisation'), ('awaiting_licence_fee_payment', 'Awaiting Licence Fee Payment'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterUniqueTogether(
            name='activityinvoice',
            unique_together=set([('activity', 'invoice_reference')]),
        ),
    ]
