# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0177_auto_20190530_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformdatarecord',
            name='licence_purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_records', to='wildlifecompliance.LicencePurpose'),
            preserve_default=False,
        ),
    ]
