# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0177_auto_20190429_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
