# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0177_auto_20190429_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
