# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-04 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0178_auto_20190504_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, choices=[('WA', 'Western Australia'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('NSW', 'New South Wales'), ('TAS', 'Tasmania'), ('NT', 'Northern Territory'), ('ACT', 'Australian Capital Territory')], default='WA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='town_suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
