# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-04 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0178_applicationformdatarecord_licence_purpose'),
        ('wildlifecompliance', '0177_auto_20190531_1034'),
    ]

    operations = [
    ]
