# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0179_auto_20190504_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='callemail',
            name='caller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
