# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-05 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0183_remove_location_call_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_call', to='wildlifecompliance.Location'),
        ),
    ]
