# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-25 06:18
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0183_auto_20190624_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntable',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
