# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-04 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0184_returntable_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='wildlifecompliance.Application'),
        ),
    ]
