# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-06 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0184_callemail_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='number',
        ),
    ]
