# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0185_remove_callemail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_call', to='wildlifecompliance.Classification'),
        ),
    ]
