# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0186_auto_20190506_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
