# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-09 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0178_location_details'),
        ('wildlifecompliance', '0190_auto_20190508_2050'),
    ]

    operations = [
    ]
