# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0194_auto_20190510_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='advice_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complianceformdatarecord',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complianceformdatarecord',
            name='deficiency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
