# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-16 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0166_auto_20190507_1143'),
        ('wildlifecompliance', '0195_auto_20190510_1642'),
    ]

    operations = [
    ]
