# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-21 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0196_merge_20190516_1931'),
        ('wildlifecompliance', '0196_maplayer'),
    ]

    operations = [
    ]
