# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('wildlifecompliance', '0196_merge_20190516_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePermissionGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Activity permission group',
                'verbose_name_plural': 'Activity permission groups',
            },
            bases=('auth.group',),
        ),
    ]
