# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-22 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0197_merge_20190521_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='email_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
