# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0198_callemail_email_user'),
        ('wildlifecompliance', '0197_compliancepermissiongroup'),
    ]

    operations = [
    ]
