# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0199_merge_20190523_1446'),
        ('wildlifecompliance', '0171_auto_20190517_1352'),
    ]

    operations = [
    ]
