# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0200_merge_20190523_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancepermissiongroup',
            options={'verbose_name': 'Compliance permission group', 'verbose_name_plural': 'Compliance permission groups'},
        ),
    ]
