# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-28 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0203_auto_20190528_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancepermissiongroup',
            options={'verbose_name': 'CM_Compliance Permission group', 'verbose_name_plural': 'CM_Compliance permission groups'},
        ),
    ]
