# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-28 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0204_auto_20190528_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondistrict',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='wildlifecompliance.RegionDistrict'),
        ),
    ]
