# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0206_auto_20190530_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceworkflowdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_documents', to='wildlifecompliance.ComplianceWorkflowLogEntry'),
        ),
    ]
