# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0207_auto_20190530_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceworkflowlogentry',
            name='call_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='wildlifecompliance.CallEmail'),
        ),
        migrations.AlterField(
            model_name='complianceworkflowlogentry',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_region', to='wildlifecompliance.RegionDistrict'),
        ),
    ]
