# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0208_auto_20190530_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceworkflowlogentry',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_district', to='wildlifecompliance.RegionDistrict'),
        ),
    ]
