# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0209_auto_20190530_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceworkflowdocument',
            name='log_entry',
        ),
        migrations.AddField(
            model_name='complianceworkflowlogentry',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ComplianceWorkflowLogEntry'),
        ),
    ]
