# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0210_auto_20190530_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceworkflowlogentry',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.ComplianceWorkflowDocument'),
        ),
    ]
