# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0211_auto_20190530_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceworkflowlogentry',
            name='documents',
        ),
        migrations.AddField(
            model_name='complianceworkflowdocument',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_documents', to='wildlifecompliance.ComplianceWorkflowLogEntry'),
        ),
    ]
