# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-05 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0214_auto_20190605_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='allocated_to',
            field=models.ManyToManyField(blank=True, related_name='callemail_allocated_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
