# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-05 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0216_auto_20190605_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='callemail',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
