# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0217_auto_20190605_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'open', b'Open'), (b'closing', b'Closing'), (b'closed', b'Closed')], default=b'draft', max_length=40)),
                ('occurrence_from_to', models.BooleanField(default=False)),
                ('occurrence_date_from', models.DateField(null=True)),
                ('occurrence_time_from', models.TimeField(null=True)),
                ('occurrence_date_to', models.DateField(null=True)),
                ('occurrence_time_to', models.TimeField(null=True)),
                ('call_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_call_eamil', to='wildlifecompliance.CallEmail')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_location', to='wildlifecompliance.Location')),
            ],
            options={
                'verbose_name': 'CM_Offence',
                'verbose_name_plural': 'CM_Offences',
            },
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_removal', models.TextField(blank=True)),
                ('removed', models.BooleanField(default=False)),
                ('offence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wildlifecompliance.Offence')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_person', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_removed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CM_Offender',
                'verbose_name_plural': 'CM_Offenders',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=b'0.00', max_digits=8)),
            ],
            options={
                'verbose_name': 'CM_Penalty',
                'verbose_name_plural': 'CM_Penalties',
            },
        ),
        migrations.CreateModel(
            name='SectionRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('act', models.CharField(blank=True, max_length=100)),
                ('offence_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('act', 'name'),
                'verbose_name': 'CM_Section/Regulation',
                'verbose_name_plural': 'CM_Sections/Regulations',
            },
        ),
        migrations.AddField(
            model_name='penalty',
            name='section_regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_section_regulation', to='wildlifecompliance.SectionRegulation'),
        ),
    ]
