# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0217_auto_20190605_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_allocated_group', to='wildlifecompliance.CompliancePermissionGroup'),
        ),
    ]
