# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0218_callemail_allocated_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='allocated_to',
        ),
    ]
