# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0218_auto_20190611_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllegedOffence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alleged_offence_offence', to='wildlifecompliance.Offence')),
                ('section_regulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alleged_offence_section_regulation', to='wildlifecompliance.SectionRegulation')),
            ],
            options={
                'verbose_name': 'CM_Alleged_Offence',
                'verbose_name_plural': 'CM_Alleged_Offences',
            },
        ),
        migrations.AddField(
            model_name='offence',
            name='alleged_offences',
            field=models.ManyToManyField(through='wildlifecompliance.AllegedOffence', to='wildlifecompliance.SectionRegulation'),
        ),
    ]
