# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0219_auto_20190611_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegedoffence',
            name='offence',
        ),
        migrations.RemoveField(
            model_name='allegedoffence',
            name='section_regulation',
        ),
        migrations.RemoveField(
            model_name='offence',
            name='alleged_offences',
        ),
        migrations.AlterField(
            model_name='offence',
            name='occurrence_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='occurrence_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='occurrence_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='occurrence_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AllegedOffence',
        ),
    ]
