# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0221_offence_alleged_offences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='section_regulation',
        ),
        migrations.AddField(
            model_name='offence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
