# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0222_auto_20190611_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionregulation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=b'0.00', max_digits=8),
        ),
    ]
