# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0223_sectionregulation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
