# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-12 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0224_offence_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='description',
        ),
    ]
