# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-13 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0220_auto_20190611_1659'),
        ('wildlifecompliance', '0225_remove_offence_description'),
    ]

    operations = [
    ]
