# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0226_merge_20190613_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='callemail',
            name='case_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_case_priority', to='wildlifecompliance.CasePriority'),
        ),
        migrations.AddField(
            model_name='callemail',
            name='inspection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_case_priority', to='wildlifecompliance.InspectionType'),
        ),
    ]
