# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-13 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0227_auto_20190613_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casepriority',
            options={'verbose_name': 'CM_CasePriority', 'verbose_name_plural': 'CM_CasePriorities'},
        ),
        migrations.AlterModelOptions(
            name='inspectiontype',
            options={'verbose_name': 'CM_InspectionType', 'verbose_name_plural': 'CM_InspectionTypes'},
        ),
    ]
