# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0228_auto_20190613_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'CM_ExternalOrganisation',
                'verbose_name_plural': 'CM_ExternalOrganisations',
            },
        ),
        migrations.AlterField(
            model_name='callemail',
            name='inspection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_inspection_type', to='wildlifecompliance.InspectionType'),
        ),
        migrations.AddField(
            model_name='callemail',
            name='external_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_external_organisation', to='wildlifecompliance.ExternalOrganisation'),
        ),
    ]
