# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-17 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0229_auto_20190613_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='external_organisation',
        ),
        migrations.DeleteModel(
            name='ExternalOrganisation',
        ),
    ]
