# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-19 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0180_auto_20190605_1309'),
        ('wildlifecompliance', '0230_auto_20190617_1010'),
    ]

    operations = [
    ]
