# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-21 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0231_merge_20190619_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='occurrence_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callemail',
            name='occurrence_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
