# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20181116_1115'),
        ('wildlifecompliance', '0234_auto_20190624_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='offender',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_organisation', to='accounts.Organisation'),
        ),
    ]
