# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-28 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0235_offender_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionregulation',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Regulation'),
        ),
    ]
