# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0236_auto_20190628_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CM_RemediationAction',
                'verbose_name_plural': 'CM_RemediationActions',
            },
        ),
        migrations.CreateModel(
            name='SanctionOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'infringement_notice', b'Infringement Notice'), (b'caution_notice', b'Caution Notice'), (b'letter_of_advice', b'Letter of Advice'), (b'remediation_notice', b'Remediation Notice')], max_length=30)),
                ('identifier', models.CharField(blank=True, max_length=50)),
                ('issued_on_paper', models.BooleanField(default=False)),
                ('paper_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('time_of_issue', models.TimeField(blank=True, null=True)),
                ('alleged_offences', models.ManyToManyField(blank=True, related_name='sanction_outcome_alleged_offences', to='wildlifecompliance.SectionRegulation')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_district', to='wildlifecompliance.RegionDistrict')),
                ('offence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_outcome_offence', to='wildlifecompliance.Offence')),
                ('offender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_outcome_offender', to='wildlifecompliance.Offender')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_region', to='wildlifecompliance.RegionDistrict')),
            ],
            options={
                'verbose_name': 'CM_SanctionOutcome',
                'verbose_name_plural': 'CM_SanctionOutcomes',
            },
        ),
        migrations.AddField(
            model_name='remediationaction',
            name='sanction_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_action_sanction_outcome', to='wildlifecompliance.SanctionOutcome'),
        ),
    ]
