# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-04 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.inspection.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0236_auto_20190628_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_for_date', models.DateField(null=True)),
                ('planned_for_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'CM_Inspection',
                'verbose_name_plural': 'CM_Inspections',
            },
        ),
        migrations.CreateModel(
            name='InspectionCommsLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.inspection.models.update_inspection_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCommsLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.Inspection')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='InspectionUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='wildlifecompliance.Inspection')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.AddField(
            model_name='inspectioncommslogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.InspectionCommsLogEntry'),
        ),
    ]
