# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.sanction_outcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0237_auto_20190702_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionOutcomeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.sanction_outcome.models.update_compliance_doc_filename)),
                ('sanction_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.SanctionOutcome')),
            ],
            options={
                'verbose_name': 'CM_SanctionOutcomeDocument',
                'verbose_name_plural': 'CM_SanctionOutcomeDocuments',
            },
        ),
    ]
