# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-05 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0238_sanctionoutcomedocument'),
        ('wildlifecompliance', '0237_auto_20190704_1524'),
    ]

    operations = [
    ]
