# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-05 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0239_merge_20190705_1108'),
        ('wildlifecompliance', '0239_auto_20190705_1446'),
    ]

    operations = [
    ]
