# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.call_email.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0242_auto_20190708_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEmailDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.call_email.models.update_call_email_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('version_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('call_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.CallEmail')),
            ],
        ),
        migrations.CreateModel(
            name='CollEmailLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=wildlifecompliance.components.call_email.models.update_call_email_comms_log_filename)),
            ],
        ),
        migrations.RenameModel(
            old_name='ComplianceLogEntry',
            new_name='CallEmailLogEntry',
        ),
        migrations.RenameModel(
            old_name='ComplianceUserAction',
            new_name='CallEmailUserAction',
        ),
        migrations.RemoveField(
            model_name='compliancedocument',
            name='call_email',
        ),
        migrations.RemoveField(
            model_name='compliancelogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='complianceworkflowdocument',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='complianceworkflowlogentry',
            name='call_email',
        ),
        migrations.RemoveField(
            model_name='complianceworkflowlogentry',
            name='district',
        ),
        migrations.RemoveField(
            model_name='complianceworkflowlogentry',
            name='region',
        ),
        migrations.DeleteModel(
            name='ComplianceDocument',
        ),
        migrations.DeleteModel(
            name='ComplianceLogDocument',
        ),
        migrations.DeleteModel(
            name='ComplianceWorkflowDocument',
        ),
        migrations.DeleteModel(
            name='ComplianceWorkflowLogEntry',
        ),
        migrations.AddField(
            model_name='collemaillogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wildlifecompliance.CallEmailLogEntry'),
        ),
    ]
