# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-10 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0243_auto_20190708_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollEmailLogDocument',
            new_name='CallEmailLogDocument',
        ),
    ]
