# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-10 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0245_auto_20190710_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemaillogdocument',
            name='input_name',
        ),
        migrations.RemoveField(
            model_name='callemaillogdocument',
            name='version_comment',
        ),
    ]
