# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.call_email.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0247_auto_20190711_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemaildocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=wildlifecompliance.components.call_email.models.update_call_email_doc_filename),
        ),
        migrations.AlterField(
            model_name='callemaillogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=wildlifecompliance.components.call_email.models.update_call_email_comms_log_filename),
        ),
    ]
