# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-12 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0248_auto_20190711_1117'),
        ('wildlifecompliance', '0240_auto_20190710_1515'),
    ]

    operations = [
    ]
