# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0249_merge_20190712_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
