# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0250_inspection_party_inspected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='party_inspected',
            field=models.CharField(choices=[('person', 'person'), ('organisation', 'organisation')], default='person', max_length=30),
        ),
    ]
