# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-15 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0252_auto_20190715_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_allocated_group', to='wildlifecompliance.CompliancePermissionGroup'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
