# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import wildlifecompliance.components.inspection.models
import wildlifecompliance.components.sanction_outcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0253_auto_20190715_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectioncommslogdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=wildlifecompliance.components.inspection.models.update_inspection_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='sanctionoutcomedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=wildlifecompliance.components.sanction_outcome.models.update_compliance_doc_filename),
        ),
    ]
