# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0254_auto_20190716_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_type', to='wildlifecompliance.InspectionType'),
        ),
    ]
