# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0257_auto_20190717_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='planned_for_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
