# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0258_auto_20190717_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_team', to='wildlifecompliance.CompliancePermissionGroup'),
        ),
    ]
