# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-18 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0259_inspection_inspection_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_team',
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_team',
            field=models.ManyToManyField(blank=True, related_name='inspection_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
