# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-19 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0260_auto_20190718_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_team_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
