# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-22 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0261_inspection_inspection_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='individual_inspected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_inspected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='organisation_inspected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_inspected', to='wildlifecompliance.Organisation'),
        ),
    ]
