# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-26 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0250_sanctionoutcome_lodgement_number'),
        ('wildlifecompliance', '0263_offence_inspection'),
    ]

    operations = [
    ]
