# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0265_offence_lodgement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'open', b'Open'), (b'closed', b'Closed'), (b'discarded', b'Discarded')], default=b'draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'open', b'Open'), (b'closing', b'Closing'), (b'closed', b'Closed'), (b'discarded', b'Discarded')], default=b'draft', max_length=40),
        ),
    ]
