# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-29 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0265_auto_20190729_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='callemail',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callemail_volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
