# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-29 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0266_callemail_volunteer'),
        ('wildlifecompliance', '0266_auto_20190729_1322'),
    ]

    operations = [
    ]
