# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0267_merge_20190729_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inform_party_being_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
