# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-30 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0269_auto_20190730_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='call_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_call_email', to='wildlifecompliance.CallEmail'),
        ),
    ]
