# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0270_inspection_call_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='advice_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
