# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-06 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0271_auto_20190806_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='advice_url',
            field=models.CharField(blank=True, help_text='Should start with http://', max_length=255, null=True),
        ),
    ]
