# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-06 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0185_auto_20190704_0906'),
        ('wildlifecompliance', '0272_auto_20190806_1152'),
    ]

    operations = [
    ]
