# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-08 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0186_auto_20190808_1052'),
        ('wildlifecompliance', '0274_auto_20190808_0922'),
    ]

    operations = [
    ]
