# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wildlifecompliance.components.inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0275_merge_20190808_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to=wildlifecompliance.components.inspection.models.update_inspection_report_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='wildlifecompliance.Inspection')),
            ],
        ),
    ]
