# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 05:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0276_inspectionreportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='inspection_type',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wildlifecompliance.InspectionType'),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_inspection_type', to='wildlifecompliance.InspectionType'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectiontype',
            unique_together=set([('inspection_type', 'version')]),
        ),
    ]
