# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0277_auto_20190809_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype',
            name='inspection_type',
            field=models.CharField(max_length=50),
        ),
    ]
