# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0278_auto_20190809_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callemail',
            name='inspection_type',
        ),
    ]
