# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0281_inspectiontypeapprovaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('open_followup', 'Open (follow-up)'), ('open_followup', 'Open (Inspection)'), ('open_case', 'Open (Case)'), ('closed', 'Closed')], default='draft', max_length=40),
        ),
    ]
