# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0282_auto_20190813_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontypeapprovaldocument',
            name='log_entry',
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='approval_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_type', to='wildlifecompliance.InspectionTypeApprovalDocument'),
        ),
    ]
