# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-14 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0284_auto_20190814_1416'),
        ('wildlifecompliance', '0280_auto_20190814_1414'),
    ]

    operations = [
    ]
