# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0284_auto_20190814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('with_manager', 'With Manager'), ('request_amendment', 'Request Amendment'), ('endorsement', 'Awaiting Endorsement'), ('sanction_outcome', 'Awaiting Sanction Outcomes'), ('discarded', 'Discarded'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
