# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-19 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0286_merge_20190815_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionOutcomeCommsLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildlifecompliance.CommunicationsLogEntry')),
                ('sanction_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='wildlifecompliance.SanctionOutcome')),
            ],
            bases=('wildlifecompliance.communicationslogentry',),
        ),
    ]
