# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-16 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0286_merge_20190815_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceManagementUserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_preference', models.CharField(choices=[('compliance_management', 'Compliance Management'), ('wildlife_licencing', 'Wildlife Licencing')], default='wildlife_licencing', max_length=30)),
                ('email_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CM_Compliance Management User Preferences',
            },
        ),
    ]
