# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-17 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0287_compliancemanagementuserpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancemanagementuserpreferences',
            name='system_preference',
        ),
        migrations.AddField(
            model_name='compliancemanagementuserpreferences',
            name='prefer_compliance_management',
            field=models.BooleanField(default=False),
        ),
    ]
