# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-19 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0288_auto_20190817_0930'),
        ('wildlifecompliance', '0288_sanctionoutcomecommslogdocument'),
    ]

    operations = [
    ]
