# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wildlifecompliance', '0288_auto_20190817_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeakLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_object_id', models.PositiveIntegerField()),
                ('second_object_id', models.PositiveIntegerField()),
                ('first_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_content_type', to='contenttypes.ContentType')),
                ('second_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_content_type', to='contenttypes.ContentType')),
            ],
        ),
    ]
