# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-21 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0289_merge_20190819_1159'),
        ('wildlifecompliance', '0289_weaklinks'),
    ]

    operations = [
    ]
