# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0290_merge_20190821_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'with_manager', b'With Manager'), (b'with_officer', b'With Officer'), (b'closed', b'Closed'), (b'closed_issued', b'Closed (Issued)'), (b'closed_withdrawn', b'Closed (Withdrawn)'), (b'awaiting_payment', b'Awaiting Payment'), (b'awaiting_payment_extended', b'Awaiting Payment Extended)'), (b'issued', b'Issued'), (b'overdue', b'Overdue')], default=b'draft', max_length=40),
        ),
    ]
