# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-03 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0290_auto_20190823_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_district', to='wildlifecompliance.RegionDistrict'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_region', to='wildlifecompliance.RegionDistrict'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('await_endorsement', 'Awaiting Endorsement'), ('discarded', 'Discarded'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
