# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-26 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0291_auto_20190821_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='allocated_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_allocated_group', to='wildlifecompliance.CompliancePermissionGroup'),
        ),
        migrations.AddField(
            model_name='offence',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sanctionoutcome',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'awaiting_endorsement', b'Awaiting Endorsement'), (b'awaiting_payment', b'Awaiting Payment'), (b'awaiting_review', b'Awaiting Review'), (b'awaiting_amendment', b'Awaiting Amendment'), (b'declined', b'Declined'), (b'withdrawn', b'Withdrawn'), (b'closed', b'closed')], default=b'draft', max_length=40),
        ),
    ]
