# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0292_auto_20190826_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_district', to='wildlifecompliance.RegionDistrict'),
        ),
        migrations.AddField(
            model_name='offence',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offence_region', to='wildlifecompliance.RegionDistrict'),
        ),
    ]
