# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-03 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0293_auto_20190826_1622'),
        ('wildlifecompliance', '0291_auto_20190903_1440'),
    ]

    operations = [
    ]
