# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0295_auto_20190905_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllegedOffence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CM_AllegedOffence',
                'verbose_name_plural': 'CM_AllegedOffences',
            },
        ),
        migrations.AlterField(
            model_name='offence',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'open', b'Open'), (b'closing', b'Closing'), (b'closed', b'Closed'), (b'discarded', b'Discarded')], default=b'open', max_length=40),
        ),
        migrations.AddField(
            model_name='allegedoffence',
            name='offence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.Offence'),
        ),
        migrations.AddField(
            model_name='allegedoffence',
            name='section_regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildlifecompliance.SectionRegulation'),
        ),
    ]
