# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0296_auto_20190906_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offence',
            name='alleged_offences',
        ),
        migrations.AddField(
            model_name='offence',
            name='alleged_offences',
            field=models.ManyToManyField(blank=True, through='wildlifecompliance.AllegedOffence', to='wildlifecompliance.SectionRegulation'),
        ),
    ]
