# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-12 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildlifecompliance', '0298_auto_20190906_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionoutcome',
            options={'ordering': ['-id'], 'verbose_name': 'CM_SanctionOutcome', 'verbose_name_plural': 'CM_SanctionOutcomes'},
        ),
        migrations.AddField(
            model_name='sanctionoutcome',
            name='responsible_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanction_outcome_responsible_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
