# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-13 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0299_auto_20190912_1441'),
        ('wildlifecompliance', '0297_auto_20190911_0903'),
    ]

    operations = [
    ]
