# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0300_merge_20190913_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offender',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offender_organisation', to='wildlifecompliance.Organisation'),
        ),
    ]
