# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0301_auto_20190913_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaklinks',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
