# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160111_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Oracle Code'),
        ),
    ]
