# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='partner_line_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Partner Notes'),
        ),
        migrations.AlterField(
            model_name='line',
            name='partner_line_reference',
            field=models.CharField(blank=True, help_text='This is the item number that the partner uses within their system', max_length=128, null=True, verbose_name='Partner reference'),
        ),
        migrations.AlterField(
            model_name='line',
            name='partner_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Partner name'),
        ),
        migrations.AlterField(
            model_name='line',
            name='partner_sku',
            field=models.CharField(max_length=128, null=True, verbose_name='Partner SKU'),
        ),
    ]
