# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 04:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170220_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='payment_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'bpay': {}, b'card': {}, b'cash': {}}),
        ),
        migrations.AddField(
            model_name='line',
            name='refund_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'bpay': {}, b'card': {}, b'cash': {}}),
        ),
    ]
