# Generated by Django 2.1.7 on 2019-04-24 00:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import ledger.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20171129_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='deduction_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=ledger.order.models.Line.get_default_data),
        ),
        migrations.AlterField(
            model_name='line',
            name='payment_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=ledger.order.models.Line.get_default_data),
        ),
        migrations.AlterField(
            model_name='line',
            name='refund_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=ledger.order.models.Line.get_default_data),
        ),
    ]
