# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_line_line_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_status',
            field=models.SmallIntegerField(choices=[(1, b'New'), (2, b'Existing'), (3, b'Removed')], default=1, null=True),
        ),
    ]
