# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190507_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Existing'), (3, 'Removed')], default=1, null=True),
        ),
    ]
