# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210901_1359'),
        ('order', '0012_auto_20210104_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='accounts.Organisation'),
        ),
    ]
