# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_organisation', to='accounts.Organisation'),
        ),
    ]
