# Generated by Django 5.2.9 on 2026-05-23 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_address_id_and_more'),
        ('address', '0006_alter_useraddress_country_alter_useraddress_id_and_more'),
        ('customer', '0005_alter_communicationeventtype_id_alter_email_id_and_more'),
        ('order', '0014_auto_20230105_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_token',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Order Token'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.communicationeventtype', verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_events', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='line',
            name='deduction_details',
            field=models.JSONField(db_index=True, default={'bpay': {}, 'card': {}, 'cash': {}}),
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='line',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='line',
            name='payment_details',
            field=models.JSONField(db_index=True, default={'bpay': {}, 'card': {}, 'cash': {}}),
        ),
        migrations.AlterField(
            model_name='line',
            name='refund_details',
            field=models.JSONField(db_index=True, default={'bpay': {}, 'card': {}, 'cash': {}}),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='order.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='lineprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineprice',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='order.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='lineprice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_prices', to='order.order', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_organisation', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.paymenteventtype', verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='shipping_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='order.shippingevent'),
        ),
        migrations.AlterField(
            model_name='paymenteventquantity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_quantities', to='order.paymentevent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='paymenteventquantity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenteventquantity',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_event_quantities', to='order.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='paymenteventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shippingeventtype', verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='shippingevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_events', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='shippingeventquantity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_quantities', to='order.shippingevent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='shippingeventquantity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingeventquantity',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_event_quantities', to='order.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='shippingeventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
