# Generated by Django 5.2.9 on 2026-05-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_order_token_alter_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_token',
        ),
    ]
