# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-29 02:25
from __future__ import unicode_literals

import ckeditor.fields
import commercialoperator.components.approvals.models
import commercialoperator.components.compliances.models
import commercialoperator.components.organisations.models
import commercialoperator.components.proposals.models
import dirtyfields.dirtyfields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_emailuser_position_title'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Activity Type')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Activity Categories',
            },
        ),
        migrations.CreateModel(
            name='ActivityMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Commercial Operator', 'Commercial Operator')], default='Commercial Operator', max_length=24, verbose_name='Activity matrix name')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('version', models.SmallIntegerField(default=1)),
                ('ordered', models.BooleanField(default=False, verbose_name='Activities Ordered Alphabetically')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercialoperator.ActivityMatrix')),
            ],
            options={
                'verbose_name_plural': 'Activity matrix',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Activity Type')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='AmendmentReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=125, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Application Amendment Reason',
                'verbose_name_plural': 'Application Amendment Reasons',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invoice', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.SmallIntegerField(choices=[(0, 'Internet booking'), (1, 'Reception booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_application_fee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFeeInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('application_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_fee_invoices', to='commercialoperator.ApplicationFee')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('max_renewals', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum number of times an Approval can be renewed')),
                ('max_renewal_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum period of each Approval renewal (Years)')),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oracle_code', models.CharField(max_length=50)),
                ('is_gst_exempt', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('status', models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'extended')], default='current', max_length=40)),
                ('renewal_sent', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField()),
                ('original_issue_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('surrender_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('suspension_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extracted_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cancellation_details', models.TextField(blank=True)),
                ('extend_details', models.TextField(blank=True)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('set_to_cancel', models.BooleanField(default=False)),
                ('set_to_suspend', models.BooleanField(default=False)),
                ('set_to_surrender', models.BooleanField(default=False)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0, verbose_name='Number of times an Approval has been renewed')),
                ('migrated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.approvals.models.update_approval_doc_filename)),
                ('can_delete', models.BooleanField(default=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.Approval')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(null=True, upload_to=commercialoperator.components.approvals.models.update_approval_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='commercialoperator.Approval')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invoice', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('booking_type', models.SmallIntegerField(choices=[(0, 'Internet booking'), (1, 'Reception booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0)),
                ('admission_number', models.CharField(blank=True, default='', max_length=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='commercialoperator.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('list_type', models.CharField(choices=[('assessor_list', 'Assessor Checklist'), ('referral_list', 'Referral Checklist')], default='assessor_list', max_length=30, verbose_name='Checklist type')),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationsLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, verbose_name='To')),
                ('fromm', models.CharField(blank=True, max_length=200, verbose_name='From')),
                ('cc', models.TextField(blank=True, verbose_name='cc')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('onhold', 'On Hold'), ('onhold_remove', 'Remove On Hold'), ('with_qaofficer', 'With QA Officer'), ('with_qaofficer_completed', 'QA Officer Completed')], default='email', max_length=35)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject / Description')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('due_date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'With Assessor'), ('approved', 'Approved'), ('discarded', 'Discarded')], max_length=20)),
                ('customer_status', models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded')], default='future', max_length=20)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('post_reminder_sent', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='commercialoperator.Approval')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_compliance_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceAmendmentReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=125, verbose_name='Reason')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename)),
                ('can_delete', models.BooleanField(default=True)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.Compliance')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.compliances.models.update_compliance_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='commercialoperator.Compliance')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('archive_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('credit_facility_link', 'Credit Facility Link'), ('deed_poll', 'Deed poll'), ('online_training_document', 'Online Training Document')], max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('help_type', models.SmallIntegerField(choices=[(1, 'External'), (2, 'Internal')], default=1, verbose_name='Help Type')),
                ('version', models.SmallIntegerField(default=1)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType')),
            ],
        ),
        migrations.CreateModel(
            name='OnHoldDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_onhold_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_pin_one', models.CharField(blank=True, max_length=50)),
                ('admin_pin_two', models.CharField(blank=True, max_length=50)),
                ('user_pin_one', models.CharField(blank=True, max_length=50)),
                ('user_pin_two', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationAccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Organisation access group',
            },
        ),
        migrations.CreateModel(
            name='OrganisationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='commercialoperator.Organisation')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('unlinked', 'Unlinked'), ('suspended', 'Suspended')], default='draft', max_length=40, verbose_name='Status')),
                ('user_role', models.CharField(choices=[('organisation_admin', 'Organisation Admin'), ('organisation_user', 'Organisation User'), ('consultant', 'Consultant')], default='organisation_user', max_length=40, verbose_name='Role')),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128, verbose_name='Given name(s)')),
                ('last_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number')),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='fax number')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commercialoperator.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.organisations.models.update_organisation_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ABN')),
                ('identification', models.FileField(blank=True, null=True, upload_to='organisation/requests/%Y/%m/%d')),
                ('status', models.CharField(choices=[('with_assessor', 'With Assessor'), ('approved', 'Approved'), ('declined', 'Declined')], default='with_assessor', max_length=100)),
                ('lodgement_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('consultant', 'Consultant')], default='employee', max_length=100)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_request_assignee', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.OrganisationRequest')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.organisations.models.update_organisation_request_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='commercialoperator.OrganisationRequest')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('park_type', models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Park Type')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Adult (price per adult)')),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Child (price per child)')),
                ('oracle_code', models.CharField(max_length=50)),
                ('is_gst_exempt', models.BooleanField(default=False)),
                ('allowed_access', models.ManyToManyField(blank=True, to='commercialoperator.AccessType')),
                ('allowed_activities', models.ManyToManyField(blank=True, to='commercialoperator.Activity')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='commercialoperator.District')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
                ('no_adults', models.SmallIntegerField(default=0)),
                ('no_children', models.SmallIntegerField(default=0)),
                ('no_free_of_charge', models.SmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='park_bookings', to='commercialoperator.Booking')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='commercialoperator.Park')),
            ],
        ),
        migrations.CreateModel(
            name='ParkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('number_adults', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Adults')),
                ('number_children', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Children')),
                ('number_seniors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Senior Citizens')),
                ('number_free_of_charge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Individuals Free of Charge')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_entries', to='commercialoperator.Park')),
            ],
            options={
                'ordering': ['park__name'],
                'verbose_name': 'Park Entry',
                'verbose_name_plural': 'Park Entries',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('new_proposal', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Application Status Type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('assessor_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('comment_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('proposed_issuance_approval', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('customer_status', models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=40, verbose_name='Customer Status')),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('lodgement_sequence', models.IntegerField(blank=True, default=0)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('on_hold', 'On Hold'), ('with_qa_officer', 'With QA Officer'), ('with_referral', 'With Referral'), ('with_assessor_requirements', 'With Assessor (Requirements)'), ('with_approver', 'With Approver'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=30, verbose_name='Processing Status')),
                ('prev_processing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('id_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_update', 'Awaiting Update'), ('updated', 'Updated'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Identification Check Status')),
                ('compliance_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('awaiting_returns', 'Awaiting Returns'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Return Check Status')),
                ('character_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('accepted', 'Accepted')], default='not_checked', max_length=30, verbose_name='Character Check Status')),
                ('review_status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status')),
                ('proposed_decline_status', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('tenure', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity matrix approval level')),
                ('approval_comment', models.TextField(blank=True)),
                ('migrated', models.BooleanField(default=False)),
                ('training_completed', models.BooleanField(default=False)),
                ('fee_invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProposalAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_type', models.CharField(choices=[('no', 'No'), ('atap', 'ATAP'), ('eco_certification', 'Eco Certification'), ('narta', 'NARTA'), ('other', 'Other')], default='no', max_length=40, verbose_name='Accreditation')),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalActivitiesLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_land', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'verbose_name': 'Application Activity (Land)',
                'verbose_name_plural': 'Application Activities (Land)',
            },
        ),
        migrations.CreateModel(
            name='ProposalActivitiesMarine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_marine', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'verbose_name': 'Application Activity (Marine)',
                'verbose_name_plural': 'Application Activities (Marine)',
            },
        ),
        migrations.CreateModel(
            name='ProposalApplicantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalApproverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Approver Group',
                'verbose_name_plural': 'Application Approver Group',
            },
        ),
        migrations.CreateModel(
            name='ProposalAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('referral_assessment', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalAssessmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField()),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='commercialoperator.ProposalAssessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='commercialoperator.ChecklistQuestion')),
            ],
            options={
                'verbose_name': 'Assessment answer',
                'verbose_name_plural': 'Assessment answers',
            },
        ),
        migrations.CreateModel(
            name='ProposalAssessorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Assessor Group',
                'verbose_name_plural': 'Application Assessor Group',
            },
        ),
        migrations.CreateModel(
            name='ProposalDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('cc_email', models.TextField(null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.Proposal')),
            ],
            options={
                'verbose_name': 'Application Document',
            },
        ),
        migrations.CreateModel(
            name='ProposalLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_proposal_comms_log_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalOnHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onhold_documents', to='commercialoperator.ProposalDocument')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalOtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_licence_period', models.CharField(blank=True, choices=[('2_months', '2 months'), ('1_year', '1 Year'), ('3_year', '3 Years'), ('5_year', '5 Years'), ('7_year', '7 Years'), ('10_year', '10 Years')], max_length=40, null=True, verbose_name='Preferred licence period')),
                ('nominated_start_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('other_comments', models.TextField(blank=True)),
                ('mooring', django.contrib.postgres.fields.jsonb.JSONField(default=[''])),
                ('credit_fees', models.BooleanField(default=False)),
                ('credit_docket_books', models.BooleanField(default=False)),
                ('docket_books_number', models.CharField(blank=True, max_length=20, verbose_name='Docket books number')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_details', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercialoperator.Park')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalParkAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.AccessType')),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_types', to='commercialoperator.ProposalPark')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalParkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='commercialoperator.ProposalPark')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalParkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_point', models.CharField(blank=True, max_length=200)),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='commercialoperator.ProposalPark')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalParkZoneActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('park_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='park_activities', to='commercialoperator.ProposalParkZone')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_proposal_required_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('free_requirement', models.TextField(blank=True, null=True)),
                ('standard', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.BooleanField(default=False)),
                ('recurrence_pattern', models.SmallIntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')], default=1)),
                ('recurrence_schedule', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercialoperator.ProposalRequirement')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalStandardRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Application Standard Requirement',
                'verbose_name_plural': 'Application Standard Requirements',
            },
        ),
        migrations.CreateModel(
            name='ProposalTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTrailSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='commercialoperator.ProposalTrail')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTrailSectionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('trail_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_activities', to='commercialoperator.ProposalTrailSection')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)')),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=[{}])),
                ('version', models.SmallIntegerField(default=1)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercialoperator.ProposalType')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='commercialoperator.Proposal')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='QAOfficerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_qaofficer_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_documents', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='QAOfficerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QA group',
                'verbose_name_plural': 'QA group',
            },
        ),
        migrations.CreateModel(
            name='QAOfficerReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_qaofficer', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_qaofficer', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('qaofficer_text', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_referral_document', to='commercialoperator.QAOfficerDocument')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_referrals', to='commercialoperator.Proposal')),
                ('qaofficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficers', to=settings.AUTH_USER_MODEL)),
                ('qaofficer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_groups', to='commercialoperator.QAOfficerGroup')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_qaofficer_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_one', models.CharField(blank=True, max_length=200)),
                ('answer_two', models.CharField(blank=True, max_length=200)),
                ('answer_three', models.CharField(blank=True, max_length=200)),
                ('answer_four', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.CharField(choices=[('answer_one', 'Answer one'), ('answer_two', 'Answer two'), ('answer_three', 'Answer three'), ('answer_four', 'Answer four')], default='answer_one', max_length=40, verbose_name='Correct Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_referral', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('referral_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_referral_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_documents', to='commercialoperator.Referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRecipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral group',
                'verbose_name_plural': 'Referral groups',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('forest_region', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Park')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_requirement_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to='commercialoperator.ProposalRequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('doc_url', models.CharField(blank=True, max_length=255, verbose_name='Document URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'System maintenance',
            },
        ),
        migrations.CreateModel(
            name='TaggedProposalApproverGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_taggedproposalapprovergroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalApproverGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_taggedproposalapprovergroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalAssessorGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_taggedproposalassessorgroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalAssessorGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_taggedproposalassessorgroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_app_types', to='commercialoperator.ApplicationType')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('allowed_activities', models.ManyToManyField(blank=True, to='commercialoperator.Activity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(blank=True, max_length=200)),
                ('rego', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('rego_expiry', models.DateField(blank=True, null=True)),
                ('access_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='commercialoperator.AccessType')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated_vessel', models.CharField(blank=True, max_length=200)),
                ('spv_no', models.CharField(blank=True, max_length=200)),
                ('hire_rego', models.CharField(blank=True, max_length=200)),
                ('craft_no', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('allowed_activities', models.ManyToManyField(blank=True, to='commercialoperator.Activity')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='commercialoperator.Park')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AmendmentRequest',
            fields=[
                ('proposalrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.ProposalRequest')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.AmendmentReason')),
            ],
            bases=('commercialoperator.proposalrequest',),
        ),
        migrations.CreateModel(
            name='ApprovalLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CommunicationsLogEntry')),
            ],
            bases=('commercialoperator.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('proposalrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.ProposalRequest')),
                ('status', models.CharField(choices=[('awaiting_assessment', 'Awaiting Assessment'), ('assessed', 'Assessed'), ('assessment_expired', 'Assessment Period Expired')], default='awaiting_assessment', max_length=20, verbose_name='Status')),
                ('date_last_reminded', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('assigned_assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('commercialoperator.proposalrequest',),
        ),
        migrations.CreateModel(
            name='ComplianceAmendmentRequest',
            fields=[
                ('comprequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CompRequest')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ComplianceAmendmentReason')),
            ],
            bases=('commercialoperator.comprequest',),
        ),
        migrations.CreateModel(
            name='ComplianceLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CommunicationsLogEntry')),
            ],
            bases=('commercialoperator.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='ComplianceRequest',
            fields=[
                ('proposalrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.ProposalRequest')),
                ('reason', models.CharField(choices=[('outstanding', 'There are currently outstanding returns for the previous licence'), ('other', 'Other')], default='outstanding', max_length=30, verbose_name='Reason')),
            ],
            bases=('commercialoperator.proposalrequest',),
        ),
        migrations.CreateModel(
            name='OrganisationLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CommunicationsLogEntry')),
            ],
            bases=('commercialoperator.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='OrganisationRequestLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CommunicationsLogEntry')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='commercialoperator.OrganisationRequest')),
            ],
            bases=('commercialoperator.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='ProposalLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.CommunicationsLogEntry')),
            ],
            bases=('commercialoperator.communicationslogentry',),
        ),
        migrations.AddField(
            model_name='section',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='commercialoperator.Trail'),
        ),
        migrations.AddField(
            model_name='referral',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_document', to='commercialoperator.ReferralDocument'),
        ),
        migrations.AddField(
            model_name='referral',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_referalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_referral_groups', to='commercialoperator.ReferralRecipientGroup'),
        ),
        migrations.AddField(
            model_name='referral',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_assessor_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltrailsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_trails', to='commercialoperator.Section'),
        ),
        migrations.AddField(
            model_name='proposaltrail',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercialoperator.Trail'),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_referral_groups', to='commercialoperator.ReferralRecipientGroup'),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='standard_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalStandardRequirement'),
        ),
        migrations.AddField(
            model_name='proposalrequireddocument',
            name='required_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercialoperator.RequiredDocument'),
        ),
        migrations.AddField(
            model_name='proposalrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalrequest',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalrequest_set', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='proposalparkzone',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_zones', to='commercialoperator.Zone'),
        ),
        migrations.AddField(
            model_name='proposalassessorgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Region'),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='commercialoperator.Referral'),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_assessment', to='commercialoperator.ReferralRecipientGroup'),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapprovergroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Region'),
        ),
        migrations.AddField(
            model_name='proposalaccreditation',
            name='proposal_other_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='commercialoperator.ProposalOtherDetails'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='activities_land',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalActivitiesLand'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='activities_marine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalActivitiesMarine'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Approval'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='approval_level_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_document', to='commercialoperator.ProposalDocument'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercialoperator_proposals_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercialoperator_proposals_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.District'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='org_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_applications', to='commercialoperator.Organisation'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_proxy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Region'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkentry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_entries', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='commercialoperator_organisations', through='commercialoperator.UserDelegation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organisation'),
        ),
        migrations.AddField(
            model_name='onholddocument',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onhold_documents', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='commercialoperator.Region'),
        ),
        migrations.AddField(
            model_name='comprequest',
            name='compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Compliance'),
        ),
        migrations.AddField(
            model_name='comprequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_requirement', to='commercialoperator.ProposalRequirement'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_compliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationslogentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='approval',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_document', to='commercialoperator.ApprovalDocument'),
        ),
        migrations.AddField(
            model_name='approval',
            name='current_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='approval',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence_document', to='commercialoperator.ApprovalDocument'),
        ),
        migrations.AddField(
            model_name='approval',
            name='org_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_approvals', to='commercialoperator.Organisation'),
        ),
        migrations.AddField(
            model_name='approval',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='renewal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_document', to='commercialoperator.ApprovalDocument'),
        ),
        migrations.AddField(
            model_name='approval',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Approval'),
        ),
        migrations.AddField(
            model_name='approval',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercialoperator_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_fees', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='commercialoperator.ActivityCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='userdelegation',
            unique_together=set([('organisation', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltype',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrailsectionactivity',
            unique_together=set([('trail_section', 'activity')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrailsection',
            unique_together=set([('section', 'proposal_trail')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrail',
            unique_together=set([('trail', 'proposal')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkzoneactivity',
            unique_together=set([('park_zone', 'activity')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkzone',
            unique_together=set([('zone', 'proposal_park')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkactivity',
            unique_together=set([('proposal_park', 'activity')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkaccess',
            unique_together=set([('proposal_park', 'access_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposalpark',
            unique_together=set([('park', 'proposal')]),
        ),
        migrations.AddField(
            model_name='proposallogentry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='commercialoperator.Proposal'),
        ),
        migrations.AddField(
            model_name='proposallogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.ProposalLogEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalassessment',
            unique_together=set([('proposal', 'referral_group')]),
        ),
        migrations.AddField(
            model_name='organisationrequestlogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.OrganisationRequestLogEntry'),
        ),
        migrations.AddField(
            model_name='organisationlogentry',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='commercialoperator.Organisation'),
        ),
        migrations.AddField(
            model_name='organisationlogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.OrganisationLogEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationcontact',
            unique_together=set([('organisation', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together=set([('application_type', 'help_type', 'version')]),
        ),
        migrations.AddField(
            model_name='compliancelogentry',
            name='compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='commercialoperator.Compliance'),
        ),
        migrations.AddField(
            model_name='compliancelogdocument',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.ComplianceLogEntry'),
        ),
        migrations.AddField(
            model_name='approvallogentry',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='commercialoperator.Approval'),
        ),
        migrations.AddField(
            model_name='approvallogdocument',
            name='log_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.ApprovalLogEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set([('lodgement_number', 'issue_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='activitymatrix',
            unique_together=set([('name', 'version')]),
        ),
    ]
