# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0002_checklistquestion_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalassessmentanswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
