# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-07 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0003_auto_20190807_1103'),
        ('commercialoperator', '0003_proposalassessmentanswer_text_answer'),
    ]

    operations = [
    ]
