# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-07 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0003_proposalassessmentanswer_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOfficerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Officer Group',
                'verbose_name_plural': 'Payment Officer group',
            },
        ),
    ]
