# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0004_merge_20190807_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewTempApproval',
            fields=[
                ('approval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commercialoperator.Approval')),
            ],
            bases=('commercialoperator.approval',),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class'), ('Filming', 'Filming'), ('Event', 'Event')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
