# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0004_paymentofficergroup'),
        ('commercialoperator', '0004_merge_20190807_1117'),
    ]

    operations = [
    ]
