# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-18 15:55
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0004_auto_20181018_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalActivitiesLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_land', models.CharField(blank=True, default='', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalActivitiesMarine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_marine', models.CharField(blank=True, default='', max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AddField(
            model_name='proposal',
            name='activities_land',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalActivitiesLand'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='activities_marine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ProposalActivitiesMarine'),
        ),
    ]
