# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0005_auto_20190808_0037'),
        ('commercialoperator', '0005_merge_20190809_1023'),
    ]

    operations = [
    ]
