# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0006_merge_20190809_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentofficergroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
        migrations.DeleteModel(
            name='PaymentOfficerGroup',
        ),
    ]
