# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0007_auto_20190813_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginvoice',
            name='deferred_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bpay_allowed',
            field=models.BooleanField(default=False, verbose_name='BPAY Allowed'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='monthly_invoicing_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='monthly_invoicing_period',
            field=models.SmallIntegerField(default=0),
        ),
    ]
