# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-01 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0008_auto_20190927_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginvoice',
            name='payment_due_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 15, 22, 3, 711771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 15, 52, 3, 711799, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 15, 22, 3, 711771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 15, 52, 3, 711799, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='parkbooking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 15, 22, 3, 713031, tzinfo=utc)),
        ),
    ]
