# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 05:29
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0008_auto_20181022_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='admin_pin_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='admin_pin_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='user_pin_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='user_pin_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        # migrations.AlterField(
        #     model_name='compliancedocument',
        #     name='_file',
        #     field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        # ),
        # migrations.AlterField(
        #     model_name='proposal',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(),
        # ),
        # migrations.AlterField(
        #     model_name='proposaltype',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        # ),
    ]
