# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0008_auto_20190920_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginvoice',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Credit Card'), (1, 'BPAY'), (2, 'Monthly Invoicing')], default=0),
        ),
    ]
