# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-23 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0009_bookinginvoice_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginvoice',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Credit Card'), (1, 'BPAY'), (2, 'Monthly Invoicing')], default=0),
        ),
    ]
