# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0009_auto_20191001_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 7, 19, 47, 600292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 7, 49, 47, 600321, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 7, 19, 47, 600292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 7, 49, 47, 600321, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='parkbooking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 7, 19, 47, 601641, tzinfo=utc)),
        ),
    ]
