# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0010_auto_20190923_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='park_bookings', to='commercialoperator.Booking'),
        ),
    ]
