# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 00:26
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0010_auto_20181023_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcontact',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationcontact',
            name='user_role',
            field=models.CharField(choices=[('organisation_admin', 'Organisation Admin'), ('organisation_user', 'Organisation User'), ('consultant', 'Consultant')], default='organisation_user', max_length=40, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='organisationcontact',
            name='user_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('unlinked', 'Unlinked'), ('suspended', 'Suspended')], default='draft', max_length=40, verbose_name='Status'),
        ),
        # migrations.AlterField(
        #     model_name='compliancedocument',
        #     name='_file',
        #     field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        # ),
        # migrations.AlterField(
        #     model_name='proposal',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(),
        # ),
        # migrations.AlterField(
        #     model_name='proposaltype',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        # ),
    ]
