# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-30 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0010_auto_20191003_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkbooking',
            name='no_adults_same_tour',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkbooking',
            name='no_children_same_tour',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkbooking',
            name='no_free_of_charge_same_tour',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkbooking',
            name='same_tour_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 6, 41, 29, 880743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 30, 7, 11, 29, 880771, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 6, 41, 29, 880743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 30, 7, 11, 29, 880771, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Credit Card'), (1, 'BPAY'), (2, 'Monthly Invoicing'), (3, 'Other (Cash/Cheque)')], default=0),
        ),
        migrations.AlterField(
            model_name='parkbooking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 6, 41, 29, 882016, tzinfo=utc)),
        ),
    ]
