# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-09 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0011_auto_20191130_1441'),
        ('commercialoperator', '0011_auto_20191206_1413'),
    ]

    operations = [
    ]
