# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 05:02
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0011_auto_20181024_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('consultant', 'Consultant')], default='employee', max_length=100),
        ),
        # migrations.AlterField(
        #     model_name='compliancedocument',
        #     name='_file',
        #     field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        # ),
        # migrations.AlterField(
        #     model_name='proposal',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(),
        # ),
        # migrations.AlterField(
        #     model_name='proposaltype',
        #     name='schema',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        # ),
    ]
