# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-23 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0012_auto_20190923_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 9, 34, 0, 665804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 10, 4, 0, 665831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 9, 34, 0, 665804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 10, 4, 0, 665831, tzinfo=utc)),
        ),
    ]
