# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-16 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0013_auto_20191212_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
