# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-24 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0014_auto_20190923_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkbooking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 5, 54, 38, 445496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 5, 54, 38, 444216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 24, 6, 24, 38, 444244, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 5, 54, 38, 444216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 24, 6, 24, 38, 444244, tzinfo=utc), null=True),
        ),
    ]
