# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-17 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0014_auto_20191216_1056'),
        ('commercialoperator', '0014_auto_20191213_1452'),
    ]

    operations = [
    ]
