# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-16 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0015_merge_20191217_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='can_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        
    ]
