# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-25 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0015_auto_20190924_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='monthly_payment_due_period',
            field=models.SmallIntegerField(default=20, verbose_name='Monthly Payment Due Period (in #days from Invoicing Date)'),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 6, 56, 21, 382902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 25, 7, 26, 21, 382933, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 6, 56, 21, 382902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 25, 7, 26, 21, 382933, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='monthly_invoicing_period',
            field=models.SmallIntegerField(default=0, verbose_name='Monthly Invoicing Period (in #days from beginning of the following month)'),
        ),
        migrations.AlterField(
            model_name='parkbooking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 6, 56, 21, 384809, tzinfo=utc)),
        ),
    ]
