# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 05:52
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0015_auto_20181121_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_district', to='commercialoperator.District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_region', to='commercialoperator.Region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
