# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-05 08:45
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0016_auto_20181130_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='region',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
