# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-16 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0016_auto_20200116_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequireddocument',
            name='can_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalrequireddocument',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
