# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-22 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0017_auto_20200116_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='expiry_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
