# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-22 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0016_auto_20200122_1357'),
        ('commercialoperator', '0017_auto_20200116_1849'),
    ]

    operations = [
    ]
