# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-07 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0019_auto_20200122_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalaccreditation',
            name='accreditation_type',
            field=models.CharField(choices=[('no', 'None'), ('atap', 'QTA'), ('eco_certification', 'Eco Certification'), ('narta', 'NARTA'), ('other', 'Other')], default='no', max_length=40, verbose_name='Accreditation'),
        ),
    ]
