# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-13 03:28
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0021_auto_20181212_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='access_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='commercialoperator.AccessType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rego_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
