# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 08:23
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0025_auto_20181214_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='commercialoperator.ActivityCategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
