# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 09:31
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0026_auto_20181214_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalParkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='commercialoperator.Activity')),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercialoperator.ProposalPark')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkactivity',
            unique_together=set([('proposal_park', 'activity')]),
        ),
    ]
