# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 03:48
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0028_auto_20181217_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['type_name']},
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='name',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='type_name',
            field=models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
