# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 04:00
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0029_auto_20181218_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycategory',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
