# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 05:03
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0030_auto_20181218_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='activity_type',
            field=models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
