# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-02 05:41
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0035_auto_20190102_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='proposal',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='commercialoperator.Proposal'),
            preserve_default=False,
        ),
    ]
