# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-07 02:11
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0036_auto_20190102_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated_vessel', models.CharField(blank=True, max_length=200)),
                ('spv_no', models.CharField(blank=True, max_length=200)),
                ('hire_rego', models.CharField(blank=True, max_length=200)),
                ('craft_no', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
