# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-09 05:16
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0037_auto_20190107_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='commercialoperator.Proposal')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercialoperator.Trail')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrail',
            unique_together=set([('trail', 'proposal')]),
        ),
    ]
