# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-28 08:00
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0038_auto_20190109_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='park_type',
            field=models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film')], default='land', max_length=40, verbose_name='Park Type'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
