# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 07:18
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0039_auto_20190228_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalParkAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.AccessType')),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_types', to='commercialoperator.ProposalPark')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkaccess',
            unique_together=set([('proposal_park', 'access_type')]),
        ),
    ]
