# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-01 03:49
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0041_auto_20190227_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_referral_groups', to='commercialoperator.ReferralRecipientGroup'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
