# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-07 02:15
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0043_auto_20190307_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='parkactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='parkactivity',
            name='park',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.DeleteModel(
            name='ParkActivity',
        ),
    ]
