# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-07 02:36
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0044_auto_20190307_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='park',
            name='allowed_activities',
            field=models.ManyToManyField(blank=True, to='commercialoperator.Activity'),
        ),
    ]
