# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 23:51
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0044_auto_20190318_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='prev_processing_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
