# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 05:49
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import commercialoperator.components.proposals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0045_auto_20190321_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnHoldDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.proposals.models.update_onhold_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onhold_documents', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('onhold', 'On Hold'), ('onhold_remove', 'Remove On Hold')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class'), ('Filming', 'Filming'), ('Event', 'Event')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event)'),
        ),
    ]
