# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-11 05:44
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0045_auto_20190307_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrailActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('proposal_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_activities', to='commercialoperator.ProposalTrail')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrailactivity',
            unique_together=set([('proposal_trail', 'activity')]),
        ),
    ]
