# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-14 01:24
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0047_auto_20190313_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrailSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='commercialoperator.ProposalTrail')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_trails', to='commercialoperator.Section')),
            ],
        ),
        migrations.AddField(
            model_name='proposaltrailactivity',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Section'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrailsection',
            unique_together=set([('section', 'proposal_trail')]),
        ),
    ]
