# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 07:10
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0047_auto_20190329_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaofficergroup',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
