# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-14 02:41
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0048_auto_20190314_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrailSectionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('trail_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_activities', to='commercialoperator.ProposalTrailSection')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltrailsectionactivity',
            unique_together=set([('trail_section', 'activity')]),
        ),
    ]
