# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-03 03:07
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0050_auto_20190401_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='qaofficer_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
