# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 06:07
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0051_auto_20190322_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposaltrailactivity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='proposaltrailactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='proposaltrailactivity',
            name='proposal_trail',
        ),
        migrations.RemoveField(
            model_name='proposaltrailactivity',
            name='section',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.DeleteModel(
            name='ProposalTrailActivity',
        ),
    ]
