# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-10 02:58
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0051_auto_20190403_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAOfficerReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_qaofficer', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_qaofficer', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('qaofficer_text', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_referral_document', to='commercialoperator.QAOfficerDocument')),
                ('qaofficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficers', to=settings.AUTH_USER_MODEL)),
                ('qaofficer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_groups', to='commercialoperator.QAOfficerGroup')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_qaofficer_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='qaofficer_referral',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
