# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-10 03:00
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0052_auto_20190410_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='qaofficer_referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.QAOfficerReferral'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
