# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 08:01
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0052_auto_20190322_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalParkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='commercialoperator.ProposalPark')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_zones', to='commercialoperator.Zone')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkzone',
            unique_together=set([('zone', 'proposal_park')]),
        ),
    ]
