# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 08:03
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0053_auto_20190322_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalParkZoneActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('park_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_activities', to='commercialoperator.ProposalParkZone')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposalparkzoneactivity',
            unique_together=set([('park_zone', 'activity')]),
        ),
    ]
