# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-10 03:22
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0053_auto_20190410_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='qaofficer_referral',
        ),
        migrations.AddField(
            model_name='qaofficerreferral',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qaofficer_referrals', to='commercialoperator.Proposal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
