# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-25 13:27
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0056_auto_20190325_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalparkzone',
            name='access_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
