# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-26 08:45
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0057_auto_20190325_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Activity')),
                ('park', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.Park')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
