# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-01 03:03
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0061_auto_20190329_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalotherdetails',
            name='preferred_license_period',
        ),
        migrations.AddField(
            model_name='proposalotherdetails',
            name='preferred_licence_period',
            field=models.CharField(choices=[('2_months', '2 months'), ('1_year', '1 Year'), ('3_year', '3 Years'), ('5_year', '5 Years'), ('7_year', '7 Years'), ('10_year', '10 Years')], default='2_months', max_length=40, verbose_name='Preferred licence period'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
