# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-03 04:00
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0066_auto_20190401_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='accreditation_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='nominated_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
