# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-04 05:30
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0067_auto_20190403_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_one', models.CharField(blank=True, max_length=200)),
                ('answer_two', models.CharField(blank=True, max_length=200)),
                ('answer_three', models.CharField(blank=True, max_length=200)),
                ('answer_four', models.CharField(blank=True, max_length=200)),
                ('answer_five', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
