# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-09 05:20
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0072_auto_20190409_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_type', models.CharField(choices=[('no', 'No'), ('atap', 'ATAP'), ('eco_certification', 'Eco Certification'), ('narta', 'NARTA')], default='no', max_length=40, verbose_name='Accreditation')),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('proposal_other_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='commercialoperator.ProposalOtherDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
