# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-09 05:30
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0073_auto_20190409_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalotherdetails',
            name='accreditation_expiry',
        ),
        migrations.RemoveField(
            model_name='proposalotherdetails',
            name='accreditation_type',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
