# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-11 06:45
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0074_auto_20190409_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposalaccreditation',
            name='accreditation_type',
            field=models.CharField(choices=[('no', 'No'), ('atap', 'ATAP'), ('eco_certification', 'Eco Certification'), ('narta', 'NARTA'), ('other', 'Other')], default='no', max_length=40, verbose_name='Accreditation'),
        ),
    ]
