# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-17 07:35
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0075_auto_20190411_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalotherdetails',
            name='docket_books_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Docket books number'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
