# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-15 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0054_auto_20190410_1122'),
        ('commercialoperator', '0075_auto_20190411_1445'),
    ]

    operations = [
    ]
