# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-16 08:45
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0076_merge_20190415_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='max_renewal_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum period of each Approval renewal (Years)'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='max_renewals',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum number of times an Approval can be renewed'),
        ),
        migrations.AddField(
            model_name='approval',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType'),
        ),
        migrations.AddField(
            model_name='approval',
            name='renewal_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of times an Approval has been renewed'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='current_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='commercialoperator.Proposal'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('new_proposal', 'New Proposal'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Proposal Type'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
