# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-24 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0076_auto_20190417_1535'),
        ('commercialoperator', '0078_auto_20190417_0805'),
    ]

    operations = [
    ]
