# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-24 06:55
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0080_auto_20190424_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='mooring',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['']),
        ),
    ]
