# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-26 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0081_auto_20190424_1455'),
        ('commercialoperator', '0079_auto_20190424_1450'),
    ]

    operations = [
    ]
