# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-05 14:42
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0082_merge_20190426_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='extend_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'extended')], default='current', max_length=40),
        ),
    ]
