# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-07 07:57
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0083_auto_20190505_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_adults', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Adults')),
                ('number_children', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Children')),
                ('number_seniors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Senior Citizens')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_entries', to='commercialoperator.Park')),
            ],
            options={
                'ordering': ['park__name'],
            },
        ),
        migrations.CreateModel(
            name='ParkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adult (price per adult)')),
                ('child', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Child (price per adult)')),
                ('senior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Senior (price per senior)')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_prices', to='commercialoperator.Park')),
            ],
            options={
                'ordering': ['park__name'],
            },
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
