# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-07 10:32
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0084_auto_20190507_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkentry',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 7, 10, 32, 5, 908273, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkentry',
            name='number_free_of_charge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Individuals Free of Charge'),
        ),
        migrations.AddField(
            model_name='parkentry',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parks_entries', to='commercialoperator.Proposal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='parkprice',
            name='child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Child (price per child)'),
        ),
    ]
