# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-03 05:57
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0085_auto_20190502_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='proposalassessment',
            unique_together=set([('proposal', 'referral_group')]),
        ),
    ]
