# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-08 06:11
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0085_auto_20190507_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
