# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-10 01:55
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0086_auto_20190508_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkentry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_entries', to='commercialoperator.Proposal'),
        ),
    ]
