# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-09 06:24
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0088_auto_20190506_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='allowed_access',
            field=models.ManyToManyField(blank=True, to='commercialoperator.AccessType'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
