# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-13 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0087_auto_20190510_0955'),
        ('commercialoperator', '0089_auto_20190509_1424'),
    ]

    operations = [
    ]
