# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-13 13:12
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0090_merge_20190513_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkprice',
            name='park',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AddField(
            model_name='park',
            name='adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adult (price per adult)'),
        ),
        migrations.AddField(
            model_name='park',
            name='child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Child (price per child)'),
        ),
        migrations.AddField(
            model_name='park',
            name='senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Senior (price per senior)'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class'), ('Filming', 'Filming'), ('Event', 'Event')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
        migrations.DeleteModel(
            name='ParkPrice',
        ),
    ]
