# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-15 00:59
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0091_auto_20190513_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='adult',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Adult (price per adult)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='park',
            name='child',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5, verbose_name='Child (price per child)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='park',
            name='senior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Senior (price per senior)'),
            preserve_default=False,
        ),
    ]
