# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-13 09:15
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0091_auto_20190513_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='applicant_details',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
