# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-19 01:36
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0092_auto_20190515_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='adult',
            new_name='adult_price',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='child',
            new_name='child_price',
        ),
        migrations.RemoveField(
            model_name='park',
            name='senior',
        ),
        migrations.AddField(
            model_name='park',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposalassessmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='commercialoperator.ChecklistQuestion'),
        ),
    ]
