# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-20 03:25
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0094_auto_20190519_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
                ('no_adults', models.SmallIntegerField(default=0)),
                ('no_children', models.SmallIntegerField(default=0)),
                ('no_free_of_charge', models.SmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_concessions',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_infants',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='old_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='overridden_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='override_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='override_reason_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='park',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AddField(
            model_name='parkbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='park_bookings', to='commercialoperator.Booking'),
        ),
        migrations.AddField(
            model_name='parkbooking',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='commercialoperator.Park'),
        ),
    ]
