# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0098_auto_20190522_2207'),
        ('commercialoperator', '0093_auto_20190520_1401'),
    ]

    operations = [
    ]
