# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-28 05:53
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0099_merge_20190523_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistquestion',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
