# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 06:32
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0100_auto_20190528_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='doc_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Document URL'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
