# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-12 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0100_auto_20190531_1637'),
        ('commercialoperator', '0103_auto_20190606_1719'),
    ]

    operations = [
    ]
