# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-13 12:45
from __future__ import unicode_literals

import commercialoperator.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0104_merge_20190612_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendmentreason',
            options={'verbose_name': 'Application Amendment Reason', 'verbose_name_plural': 'Application Amendment Reasons'},
        ),
        migrations.AlterModelOptions(
            name='parkentry',
            options={'ordering': ['park__name'], 'verbose_name': 'Park Entry', 'verbose_name_plural': 'Park Entries'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='proposalactivitiesland',
            options={'verbose_name': 'Application Activity (Land)', 'verbose_name_plural': 'Application Activities (Land)'},
        ),
        migrations.AlterModelOptions(
            name='proposalactivitiesmarine',
            options={'verbose_name': 'Application Activity (Marine)', 'verbose_name_plural': 'Application Activities (Marine)'},
        ),
        migrations.AlterModelOptions(
            name='proposalapprovergroup',
            options={'verbose_name': 'Application Approver Group', 'verbose_name_plural': 'Application Approver Group'},
        ),
        migrations.AlterModelOptions(
            name='proposalassessmentanswer',
            options={'verbose_name': 'Assessment answer', 'verbose_name_plural': 'Assessment answers'},
        ),
        migrations.AlterModelOptions(
            name='proposalassessorgroup',
            options={'verbose_name': 'Application Assessor Group', 'verbose_name_plural': 'Application Assessor Group'},
        ),
        migrations.AlterModelOptions(
            name='proposaldocument',
            options={'verbose_name': 'Application Document'},
        ),
        migrations.AlterModelOptions(
            name='proposalstandardrequirement',
            options={'verbose_name': 'Application Standard Requirement', 'verbose_name_plural': 'Application Standard Requirements'},
        ),
        migrations.AlterModelOptions(
            name='qaofficergroup',
            options={'verbose_name': 'QA group', 'verbose_name_plural': 'QA group'},
        ),
        migrations.AlterModelOptions(
            name='referralrecipientgroup',
            options={'verbose_name': 'Referral group', 'verbose_name_plural': 'Referral groups'},
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
