# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-15 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0107_auto_20190711_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_invoice', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.SmallIntegerField(choices=[(0, 'Internet booking'), (1, 'Reception booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_application_fee', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_fees', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFeeInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('application_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_fee_invoices', to='commercialoperator.ApplicationFee')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cost_total',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.SmallIntegerField(choices=[(0, 'Internet booking'), (1, 'Reception booking'), (2, 'Black booking'), (3, 'Temporary reservation')], default=0),
        ),
    ]
