# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0107_auto_20190711_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='preferred_licence_period',
            field=models.CharField(choices=[('2_months', '2 months'), ('1_year', '1 Year'), ('3_year', '3 Years'), ('5_year', '5 Years'), ('7_year', '7 Years'), ('10_year', '10 Years')], max_length=40, verbose_name='Preferred licence period'),
        ),
    ]
