# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0108_auto_20190717_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalotherdetails',
            name='preferred_licence_period',
            field=models.CharField(blank=True, choices=[('2_months', '2 months'), ('1_year', '1 Year'), ('3_year', '3 Years'), ('5_year', '5 Years'), ('7_year', '7 Years'), ('10_year', '10 Years')], max_length=40, null=True, verbose_name='Preferred licence period'),
        ),
    ]
