# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-22 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0109_auto_20190717_1049'),
        ('commercialoperator', '0109_auto_20190716_1951'),
    ]

    operations = [
    ]
