# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_emailuserlogdocument'),
        ('commercialoperator', '0110_merge_20190722_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationlogdocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationlogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='organisationrequestlogdocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationrequestlogdocument',
            name='log_entry',
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
        migrations.DeleteModel(
            name='OrganisationLogDocument',
        ),
        migrations.DeleteModel(
            name='OrganisationRequestLogDocument',
        ),
    ]
