# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-24 09:05
from __future__ import unicode_literals

import commercialoperator.components.organisations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0111_auto_20190724_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.organisations.models.update_organisation_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.OrganisationLogEntry')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequestLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=commercialoperator.components.organisations.models.update_organisation_request_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercialoperator.OrganisationRequestLogEntry')),
            ],
        ),
    ]
