# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-28 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0111_auto_20190724_1538'),
        ('commercialoperator', '0112_organisationlogdocument_organisationrequestlogdocument'),
    ]

    operations = [
    ]
