# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20160801_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system',
            field=models.CharField(default='0369', max_length=4),
            preserve_default=False,
        ),
    ]
