# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0002_auto_20160801_1035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bpaycollection',
            table='bpay_bpaycollection_v',
        ),
    ]
