# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0003_auto_20160801_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpaytransaction',
            name='crn',
            field=models.CharField(help_text=b'Customer Referencer Number', max_length=20),
        ),
    ]
