# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0004_auto_20160909_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpayAccountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_items', models.IntegerField(default=0)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_items', models.IntegerField(default=0)),
                ('cheque_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BpayAccountTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('records', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BpayFileTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('groups', models.IntegerField(default=0)),
                ('records', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BpayGroupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled', models.DateTimeField(help_text=b'File Settlement Date Time')),
                ('modifier', models.IntegerField(choices=[(1, b'interim/previous day'), (2, b'final/previous day'), (3, b'interim/same day'), (4, b'final/same day')], help_text=b'As of Date modifier')),
            ],
        ),
        migrations.CreateModel(
            name='BpayGroupTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accounts', models.IntegerField(default=0)),
                ('records', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='account_records',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='account_total',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='cheque_amount',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='cheque_items',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='credit_items',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='date_modifier',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='debit_items',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='file_groups',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='file_records',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='file_total',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='group_accounts',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='group_records',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='group_total',
        ),
        migrations.RemoveField(
            model_name='bpayfile',
            name='settled',
        ),
        migrations.AddField(
            model_name='bpaygrouptrailer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_trailerrecords', to='bpay.BpayFile'),
        ),
        migrations.AddField(
            model_name='bpaygrouprecord',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_records', to='bpay.BpayFile'),
        ),
        migrations.AddField(
            model_name='bpayfiletrailer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_trailerrecords', to='bpay.BpayFile'),
        ),
        migrations.AddField(
            model_name='bpayaccounttrailer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_trailerrecords', to='bpay.BpayFile'),
        ),
        migrations.AddField(
            model_name='bpayaccountrecord',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_records', to='bpay.BpayFile'),
        ),
    ]
