# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0005_auto_20160912_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpayfiletrailer',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='bpay.BpayFile'),
        ),
    ]
