# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0009_auto_20170203_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billercoderecipient',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='bpay.BillerCodeSystem'),
        ),
    ]
