# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:31
from __future__ import unicode_literals

from django.db import migrations

def update_contenttypes(apps, schema_editor):
    """
    Updates content types.
    We want to have the same content type id, when the model is moved and renamed.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    # Bpay
    bpay_qs = ContentType.objects.using(db_alias).filter(app_label='bpay')
    bpay_qs.update(app_label='payments')

class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20170329_1131'),
        ('bpay', '0010_auto_20170206_0841'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='BpayFile',
            table='payments_bpayfile'
        ),
        migrations.AlterModelTable(
            name='BillerCodeRecipient',
            table='payments_billercoderecipient'
        ),
        migrations.AlterModelTable(
            name='BillerCodeSystem',
            table="payments_billercodesystem"
        ),
        migrations.AlterModelTable(
            name='BpayAccountRecord',
            table='payments_bpayaccountrecord'
        ),
        migrations.AlterModelTable(
            name='BpayAccountTrailer',
            table='payments_bpayaccounttrailer'
        ),
        migrations.AlterModelTable(
            name='BpayFileTrailer',
            table='payments_bpayfiletrailer'
        ),
        migrations.AlterModelTable(
            name='BpayGroupRecord',
            table='payments_bpaygrouprecord'
        ),
        migrations.AlterModelTable(
            name='BpayGroupTrailer',
            table='payments_bpaygrouptrailer'
        ),
        migrations.AlterModelTable(
            name='BpayTransaction',
            table='payments_bpaytransaction'
        ),
        migrations.RunPython(update_contenttypes),
    ]
   
