# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models

def content_forward(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    bpay_qs = ContentType.objects.using(db_alias).filter(app_label='bpay', model__in=('bpayfile', 'billercoderecipient', 'billercodesystem', 'bpayaccountrecord', 'bpayaccounttrailer', 'bpayfiletrailer', 'bpaygrouprecord', 'bpaygrouptrailer', 'bpaytransaction'))
    bpay_qs.update(app_label='payments')


def content_reverse(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias

    bpay_qs = ContentType.objects.using(db_alias).filter(app_label='payments', model__in=('bpayfile', 'billercoderecipient', 'billercodesystem', 'bpayaccountrecord', 'bpayaccounttrailer', 'bpayfiletrailer', 'bpaygrouprecord', 'bpaygrouptrailer', 'bpaytransaction'))
    bpay_qs.update(app_label='bpay')



class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_parkstay_rebase'),
        ('bpay', '0010_auto_20170206_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpaytransaction',
            name='car',
            field=models.CharField(blank=True, help_text='Customer Additional Reference.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bpaytransaction',
            name='country',
            field=models.CharField(blank=True, help_text='Country of payment.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bpaytransaction',
            name='discretionary_data',
            field=models.CharField(blank=True, help_text='Reason for refund or reversal.', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='BpayFile',
            table='payments_bpayfile',
        ),
        migrations.AlterModelTable(
            name='BillerCodeRecipient',
            table='payments_billercoderecipient',
        ),
        migrations.AlterModelTable(
            name='BillerCodeSystem',
            table='payments_billercodesystem',
        ),
        migrations.AlterModelTable(
            name='BpayAccountRecord',
            table='payments_bpayaccountrecord',
        ),
        migrations.AlterModelTable(
            name='BpayAccountTrailer',
            table='payments_bpayaccounttrailer',
        ),
        migrations.AlterModelTable(
            name='BpayFileTrailer',
            table='payments_bpayfiletrailer',
        ),
        migrations.AlterModelTable(
            name='BpayGroupRecord',
            table='payments_bpaygrouprecord',
        ),
        migrations.AlterModelTable(
            name='BpayGroupTrailer',
            table='payments_bpaygrouptrailer',
        ),
        migrations.AlterModelTable(
            name='BpayTransaction',
            table='payments_bpaytransaction',
        ),
        #migrations.RunPython(
        #    code=content_forward,
        #    reverse_code=content_reverse,
        #),

    ]
