# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0012_bpaytransaction_original_crn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpayJobRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'payments_bpayjobrecipient',
            },
        ),
    ]
