# Generated by Django 2.1.7 on 2019-04-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpay', '0014_auto_20180118_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billercoderecipient',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='bpay.BillerCodeSystem'),
        ),
        migrations.AlterField(
            model_name='bpayaccountrecord',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_records', to='bpay.BpayFile'),
        ),
        migrations.AlterField(
            model_name='bpayaccounttrailer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_trailerrecords', to='bpay.BpayFile'),
        ),
        migrations.AlterField(
            model_name='bpayfiletrailer',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trailer', to='bpay.BpayFile'),
        ),
        migrations.AlterField(
            model_name='bpaygrouprecord',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_records', to='bpay.BpayFile'),
        ),
        migrations.AlterField(
            model_name='bpaygrouptrailer',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_trailerrecords', to='bpay.BpayFile'),
        ),
        migrations.AlterField(
            model_name='bpaytransaction',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bpay.BpayFile'),
        ),
    ]
