# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressbook', '0002_auto_20160204_1450'),
        ('rollcall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('emailuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], default='Mr', max_length=100, verbose_name='title')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number')),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='fax number')),
                ('organisation', models.CharField(blank=True, help_text='organisation, institution or company', max_length=300, null=True, verbose_name='organisation')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='addressbook.Address')),
            ],
            options={
                'db_table': 'wl_accounts_customer',
            },
            bases=('rollcall.emailuser',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wl_accounts_document',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='documents',
            field=models.ManyToManyField(to='accounts.Document'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='addressbook.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='residential_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='addressbook.Address'),
        ),
    ]
