# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 07:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.SmallIntegerField(default=1)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApplicationType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together=set([('application_type', 'version')]),
        ),
    ]
