# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-11 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallogdocument',
            name='_file',
        ),
        migrations.RemoveField(
            model_name='approvallogdocument',
            name='log_entry',
        ),
        migrations.AddField(
            model_name='approvallogdocument',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs1', to='disturbance.Approval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helppage',
            name='help_type',
            field=models.SmallIntegerField(choices=[(1, 'External'), (2, 'Internal')], default=1, verbose_name='Help Type'),
        ),
    ]
