# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 03:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
