# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppage',
            name='help_type',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=40, verbose_name='Help Type'),
        ),
    ]
