# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='pin_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='pin_two',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
