# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='cancellation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='cancellation_details',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
