# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 00:49
from __future__ import unicode_literals

import disturbance.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activities', disturbance.fields.CommaSeparatedField()),
            ],
        ),
    ]
