# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendmentreason',
            options={'verbose_name': 'Proposal Amendment Reason', 'verbose_name_plural': 'Proposal Amendment Reasons'},
        ),
        migrations.RemoveField(
            model_name='proposaltype',
            name='activities',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_proposals_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_proposals_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
