# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0002_auto_20180926_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='post_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
