# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-11 03:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0002_auto_20180611_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Disturbance', 'Disturbance')], default='Disturbance', max_length=24, verbose_name='Activity matrix name')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('version', models.SmallIntegerField(default=1)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disturbance.ActivityMatrix')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activitymatrix',
            unique_together=set([('name', 'version')]),
        ),
    ]
