# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0002_auto_20180430_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='cancellation_details',
            field=models.TextField(blank=True),
        ),
    ]
