# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0002_helppage_help_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together=set([('application_type', 'help_type', 'version')]),
        ),
    ]
