# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:25
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('disturbance', '0002_proposaltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaltype',
            name='activities',
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='activities',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
