# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0002_proposal_proposal_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='status',
            field=models.CharField(choices=[('with_assessor', 'With Assessor'), ('approved', 'Approved'), ('declined', 'Declined')], default='with_assessor', max_length=100),
        ),
    ]
