# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-01 01:25
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0003_compliance_post_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='current_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='disturbance.Proposal'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
