# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0003_auto_20180524_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='help_type',
            field=models.SmallIntegerField(choices=[(1, 'External'), (2, 'Internal')], default=1, max_length=40, verbose_name='Help Type'),
        ),
    ]
