# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0003_proposal_assessor_group_fixtures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliance',
            old_name='proccessing_status',
            new_name='processing_status',
        ),
    ]
