# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:39
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0003_auto_20170601_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaltype',
            name='activities',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of activities.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Activities'),
        ),
    ]
