# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0003_compliance_post_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
