# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0004_proposaldocument_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
