# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0004_approvallogdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='set_to_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='set_to_surrender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='set_to_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
