# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0004_auto_20171228_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_compliance_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
