# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0004_remove_proposal_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity matrix approval level'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tenure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
