# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0004_auto_20180524_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirement', to='disturbance.ProposalRequirement'),
        ),
    ]
