# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0005_auto_20171228_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='disturbance.Approval'),
            preserve_default=False,
        ),
    ]
