# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0005_auto_20180502_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='renewal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_document', to='disturbance.ApprovalDocument'),
        ),
    ]
