# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0005_approvaldocument_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallogdocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='current_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='disturbance.Proposal'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Disturbance Lite', 'Disturbance Lite')], default='Disturbance', max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
