# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-29 16:52
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0006_auto_20180930_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallogdocument',
            name='can_delete',
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
