# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0006_auto_20180618_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapprovergroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Region'),
        ),
        migrations.AddField(
            model_name='proposalassessorgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Region'),
        ),
    ]
