# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0006_organisationrequestlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequestlogentry',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='disturbance.OrganisationRequest'),
        ),
    ]
