# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0007_auto_20180618_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapprovergroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
