# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0007_approval_lodgement_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set([('lodgement_number', 'issue_date')]),
        ),
    ]
