# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0008_auto_20180619_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval_level_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_document', to='disturbance.ProposalDocument'),
        ),
    ]
