# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0008_auto_20170614_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='disturbance.Organisation')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='organisationdelegateaction',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisationdelegateaction',
            name='who',
        ),
        migrations.DeleteModel(
            name='OrganisationDelegateAction',
        ),
    ]
