# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0009_auto_20170614_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disturbance.CommunicationsLogEntry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='disturbance.Organisation')),
            ],
            bases=('disturbance.communicationslogentry',),
        ),
    ]
