# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-09 08:32
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0009_auto_20190111_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewTempApproval',
            fields=[
                ('approval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disturbance.Approval')),
            ],
            bases=('disturbance.approval',),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
