# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-18 02:05
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0010_auto_20190909_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='reissued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
