# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0010_organisationlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
