# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 06:35
from __future__ import unicode_literals

import disturbance.components.approvals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0010_auto_20180703_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallogdocument',
            name='approval',
        ),
        migrations.AddField(
            model_name='approvallogdocument',
            name='_file',
            field=models.FileField(null=True, upload_to=disturbance.components.approvals.models.update_approval_comms_log_filename),
        ),
        migrations.AddField(
            model_name='approvallogdocument',
            name='log_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apdocuments', to='disturbance.ApprovalLogEntry'),
        ),
    ]
