# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-28 07:28
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0010_organisationrequestlogdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename)),
            ],
        ),
        migrations.AddField(
            model_name='compliance',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'Under Review'), ('approved', 'Approved')], default='future', max_length=20),
        ),
        migrations.AddField(
            model_name='compliance',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disturbance.Compliance'),
        ),
    ]
