# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-18 05:38
from __future__ import unicode_literals

import disturbance.components.compliances.models
import disturbance.components.proposals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0011_auto_20190918_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentRequestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=disturbance.components.proposals.models.update_amendment_request_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('amendment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_request_documents', to='disturbance.AmendmentRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
