# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-29 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0011_auto_20180328_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
