# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-23 05:32
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0011_auto_20191023_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterUniqueTogether(
            name='globalsettings',
            unique_together=set([('id', 'key')]),
        ),
    ]
