# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 01:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0011_auto_20170616_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='assessor_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='customer_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('under_review', 'Under Review'), ('with_assessor', 'With Assesor'), ('id_required', 'Identification Required'), ('returns_required', 'Returns Completion Required'), ('amendment_required', 'Amendment Required'), ('id_and_amendment_required', 'Identification/Amendments Required'), ('id_and_returns_required', 'Identification/Returns Required'), ('returns_and_amendment_required', 'Returns/Amendments Required'), ('id_and_returns_and_amendment_required', 'Identification/Returns/Amendments Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='temp', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'With Assesor'), ('with_referral', 'With Referral'), ('ready_for_action', 'Ready for Action'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('awaiting_applicant_response', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('issued', 'Issued'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='temp', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='proposallogentry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='disturbance.Proposal'),
        ),
        migrations.AlterField(
            model_name='proposaluseraction',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='disturbance.Proposal'),
        ),
    ]
