# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-06 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0012_compliance_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='lodgement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
