# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0012_auto_20170629_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_referral', 'With Referral'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='disturbance.Proposal')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_referalls', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_assessor_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
