# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-23 05:18
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0012_auto_20190918_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='assessment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
