# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0012_auto_20180703_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
