# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0013_auto_20180711_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
