# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-25 06:06
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0013_auto_20190923_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='can_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
