# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-30 02:37
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0013_auto_20191023_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='pin_one',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='pin_two',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
