# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-09 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0014_remove_compliance_lodgement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_compliances', to=settings.AUTH_USER_MODEL),
        ),
    ]
