# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-27 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0014_referral_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_text',
            field=models.TextField(blank=True),
        ),
    ]
