# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-23 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0015_complianceamendmentreason_complianceamendmentstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplianceAmendmentReason',
            new_name='AmendmentReason',
        ),
        migrations.RenameModel(
            old_name='ComplianceAmendmentStatus',
            new_name='AmendmentStatus',
        ),
    ]
