# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0015_auto_20170704_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAssessorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalAssessorGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_taggedproposalassessorgroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalAssessorGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalAssessorGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_taggedproposalassessorgroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='proposalassessorgroup',
            name='activities',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of activities.', through='disturbance.TaggedProposalAssessorGroupActivities', to='taggit.Tag', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='proposalassessorgroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalassessorgroup',
            name='regions',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of regions.', through='disturbance.TaggedProposalAssessorGroupRegions', to='taggit.Tag', verbose_name='Regions'),
        ),
    ]
