# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0015_referral_referral_text'),
        ('disturbance', '0015_complianceamendmentreason_complianceamendmentstatus'),
    ]

    operations = [
    ]
