# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 03:48
from __future__ import unicode_literals
import os
from django.conf import settings
from django.db import migrations, models
import taggit.managers
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../components/proposals/fixtures'))

def load_fixture(apps, schema_editor):
    call_command('loaddata', os.path.join(fixture_dir, 'default_proposal_assessor_group.json'))

def reverse_add_default_group(apps, schema_editor):
    ProposalAssessorGroup = apps.get_model('disturbance','ProposalAssessorGroup')
    ProposalAssessorGroup.objects.filter(default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0016_auto_20170712_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='activities',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of activities.', through='disturbance.TaggedProposalAssessorGroupActivities', to='taggit.Tag', verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='regions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of regions.', through='disturbance.TaggedProposalAssessorGroupRegions', to='taggit.Tag', verbose_name='Regions'),
        ),
        migrations.RunPython(load_fixture,reverse_add_default_group),
    ]
