# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-30 04:00
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0016_auto_20191030_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('consultant', 'Consultant')], default='employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
