# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0016_merge_20180802_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='to',
            field=models.TextField(blank=True, verbose_name='To'),
        ),
    ]
