# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0016_auto_20180723_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmendmentStatus',
        ),
        migrations.AlterField(
            model_name='amendmentrequest',
            name='reason',
            field=models.CharField(choices=[(1, 'The information provided was insufficient'), (2, 'There was missing information'), (3, 'Some other info ...'), (4, 'Other')], default=1, max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='complianceamendmentrequest',
            name='reason',
            field=models.CharField(choices=[(1, 'The information provided was insufficient'), (2, 'There was missing information'), (3, 'Some other info ...'), (4, 'Other')], default=1, max_length=30, verbose_name='Reason'),
        ),
    ]
