# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-25 08:59
from __future__ import unicode_literals

import disturbance.components.compliances.models
import disturbance.components.proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0016_auto_20190925_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.proposals.models.update_amendment_request_doc_filename),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
