# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0017_auto_20180803_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='cc',
            field=models.TextField(blank=True, verbose_name='cc'),
        ),
    ]
