# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0017_auto_20180723_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
#        migrations.AlterField(
#            model_name='amendmentrequest',
#            name='reason',
#            field=models.CharField(choices=[(0, 'The information provided was insufficient'), (1, 'There was missing information'), (2, 'Other')], default=0, max_length=30, verbose_name='Reason'),
#        ),
#        migrations.AlterField(
#            model_name='complianceamendmentrequest',
#            name='reason',
#            field=models.CharField(choices=[(0, 'The information provided was insufficient'), (1, 'There was missing information'), (2, 'Other')], default=0, max_length=30, verbose_name='Reason'),
#        ),
    ]
