# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-27 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('disturbance', '0014_referral_text'),
        ('disturbance', '0018_systemmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='to',
            field=models.TextField(blank=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='cc',
            field=models.TextField(blank=True, verbose_name='cc'),
        ),

    ]
