# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0018_auto_20170720_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('_file', models.FileField(upload_to='%Y/%m/%d')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='hard_copy',
        ),
        migrations.AlterField(
            model_name='disturbancelicence',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_document', to='disturbance.Document'),
        ),
        migrations.AlterField(
            model_name='disturbancelicence',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence_document', to='disturbance.Document'),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disturbance.Proposal'),
        ),
    ]
