# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_auto_20180814_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymatrix',
            options={'verbose_name_plural': 'Activity matrix'},
        ),
        migrations.AlterModelOptions(
            name='organisationaccessgroup',
            options={'verbose_name_plural': 'Organisation access group'},
        ),
        migrations.AlterModelOptions(
            name='systemmaintenance',
            options={'verbose_name_plural': 'System maintenance'},
        ),
        migrations.AddField(
            model_name='activitymatrix',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Activities Ordered Alphabetically'),
        ),
    ]
