# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_complianceamendmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('archive_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_app_types', to='disturbance.ApplicationType')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='region',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tenure',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Licence'), (2, 'Amendment'), (3, 'Renewal')], default=1, verbose_name='Proposal state'),
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(default=1, max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disturbance.ProposalType'),
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='forest_region',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='proposaltype',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='proposaltype',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='disturbance.Region'),
        ),
        migrations.AddField(
            model_name='activity',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_app_types', to='disturbance.ApplicationType'),
        ),
    ]
