# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_complianceamendmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_type',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Licence'), (2, 'Amendment'), (3, 'Renewal')], default=1, max_length=24, verbose_name='Proposal state'),
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[(1, 'Disturbance'), (2, 'Apiary')], default=1, max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disturbance.ProposalType'),
        ),
        migrations.AddField(
            model_name='proposaltype',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='proposaltype',
            unique_together=set([('name', 'version')]),
        ),
    ]
