# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_complianceamendmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='cancellation_details',
            field=models.TextField(blank=True),
        ),
    ]
