# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 05:08
from __future__ import unicode_literals

import datetime
import disturbance.components.proposals.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_auto_20170720_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 20, 5, 8, 35, 26576, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disturbancelicence',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_document', to='disturbance.ProposalDocument'),
        ),
        migrations.AlterField(
            model_name='disturbancelicence',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence_document', to='disturbance.ProposalDocument'),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='_file',
            field=models.FileField(upload_to=disturbance.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
