# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-20 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0020_auto_20180815_1029'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='amendmentrequest',
        #    name='reason',
        #    field=models.CharField(choices=[(0, 'The information provided was insufficient'), (1, 'There was missing information'), (2, 'Other')], default=0, max_length=30, verbose_name='Reason'),
        #),
        #migrations.AlterField(
        #    model_name='complianceamendmentrequest',
        #    name='reason',
        #    field=models.CharField(choices=[(0, 'The information provided was insufficient'), (1, 'There was missing information'), (2, 'Other')], default=0, max_length=30, verbose_name='Reason'),
        #),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('new_proposal', 'New Proposal'), ('amendment', 'Amendment'), ('renewal', 'Renewal')], default='new_proposal', max_length=40, verbose_name='Proposal Type'),
        ),
    ]
