# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0020_auto_20170720_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
