# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0020_auto_20180426_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='disturbance.ProposalType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Licence'), (2, 'Amendment'), (3, 'Renewal')], default=1, verbose_name='Proposal state'),
        ),
    ]
