# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0021_proposaldocument_input_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalStandardRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assessmentrequirement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='assessmentrequirement',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentrequirement',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='requirements',
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 1, 1, 13, 45581, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='free_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='recurrence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='recurrence_pattern',
            field=models.SmallIntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')], default=1),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='recurrence_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='standard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposalrequirement',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='disturbance.Proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalrequirement',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='AssessmentRequirement',
        ),
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='requirement',
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='standard_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalStandardRequirement'),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
