# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0022_auto_20180426_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltype',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
