# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0022_auto_20180820_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        # migrations.AlterField(
        #     model_name='amendmentrequest',
        #     name='reason',
        #     field=models.CharField(choices=[(1, 'First reason'), (2, 'second reason')], default=1, max_length=30, verbose_name='Reason'),
        # ),
        # migrations.AlterField(
        #     model_name='complianceamendmentrequest',
        #     name='reason',
        #     field=models.CharField(choices=[(1, 'First reason'), (2, 'second reason')], default=1, max_length=30, verbose_name='Reason'),
        # ),
    ]
