# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0022_auto_20170721_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalrequirement',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
