# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0023_auto_20180827_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance')], default='Disturbance', max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
