# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0023_auto_20180426_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaltype',
            name='site',
        ),
    ]
