# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0024_auto_20180905_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='amendmentrequest',
            name='reason',
            field=models.CharField(choices=[(1, 'Not enough information provided'), (2, 'Incorrect details provided'), (3, 'Some Other Reason')], default=1, max_length=30, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='complianceamendmentrequest',
            name='reason',
            field=models.CharField(choices=[(1, 'Not enough information provided'), (2, 'Incorrect details provided'), (3, 'Some Other Reason')], default=1, max_length=30, verbose_name='Reason'),
        ),
    ]
