# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0024_remove_proposalrequirement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
