# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-26 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0024_remove_proposaltype_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_type',
        ),
    ]
