# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0026_auto_20170724_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldeclineddetails',
            name='cc_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proposaldeclineddetails',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decline_details', to='disturbance.Proposal'),
        ),
    ]
