# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0027_auto_20170725_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposed_decline_status',
            field=models.BooleanField(default=False),
        ),
    ]
