# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0027_auto_20180510_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Activity'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.District'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Region'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Tenure'),
        ),
    ]
