# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 02:19
from __future__ import unicode_literals

import os
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../components/proposals/fixtures'))

def load_fixture(apps, schema_editor):
    call_command('loaddata', os.path.join(fixture_dir, 'default_proposal_approver_group.json'))

def reverse_add_default_group(apps, schema_editor):
    ProposalApproverGroup = apps.get_model('disturbance','ProposalApproverGroup')
    ProposalApproverGroup.objects.filter(default=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0028_proposal_proposed_decline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalApproverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalApproverGroupActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_taggedproposalapprovergroupactivities_items', to='taggit.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedProposalApproverGroupRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApproverGroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_taggedproposalapprovergroupregions_items', to='taggit.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_proposals_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapprovergroup',
            name='activities',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of activities.', through='disturbance.TaggedProposalApproverGroupActivities', to='taggit.Tag', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='proposalapprovergroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapprovergroup',
            name='regions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of regions.', through='disturbance.TaggedProposalApproverGroupRegions', to='taggit.Tag', verbose_name='Regions'),
        ),
        migrations.RunPython(load_fixture,reverse_add_default_group),
    ]
