# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0028_auto_20180510_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='application_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApplicationType'),
            preserve_default=False,
        ),
    ]
