# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0030_auto_20180511_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Apiary', 'Apiary')], default=1, max_length=24, verbose_name='Application name (eg. Disturbance, Apiary)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='proposaltype',
            unique_together=set([('name', 'version')]),
        ),
    ]
