# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 06:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0030_auto_20170727_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tenure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposed_issuance_approval',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
