# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0031_auto_20170728_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='cover_letter_document',
        ),
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='licence_document',
        ),
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='licence_ptr',
        ),
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='disturbancelicence',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='idrequest',
            name='proposalrequest_ptr',
        ),
        migrations.DeleteModel(
            name='DisturbanceLicence',
        ),
        migrations.DeleteModel(
            name='IDRequest',
        ),
    ]
