# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 02:27
from __future__ import unicode_literals

import disturbance.components.approvals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0032_auto_20180511_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=disturbance.components.approvals.models.update_approval_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disturbance.ApprovalLogEntry')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='cancellation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='set_to_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='set_to_surrender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='set_to_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
