# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('disturbance', '0006_approval_renewal_document'),
        ('disturbance', '0034_approval_renewal_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
