# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0034_approvaluseraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
