# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0036_auto_20170731_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval'),
        ),
    ]
