# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0037_proposal_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalrequirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
