# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_basket_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='system',
            field=models.CharField(max_length=4),
        ),
    ]
