# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:08
from __future__ import unicode_literals

from django.db import migrations
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20160802_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_reference',
            field=oscar.models.fields.slugfield.SlugField(max_length=128, verbose_name='Line Reference'),
        ),
    ]
