# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20160905_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='catalogue.Product', verbose_name='Product'),
        ),
    ]
