# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20170106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_lines', to='catalogue.Product', verbose_name=b'Product'),
        ),
    ]
