# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20170111_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='custom_ledger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='ledger_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oracle Code'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_reference',
            field=oscar.models.fields.slugfield.SlugField(blank=True, max_length=128, null=True, verbose_name='Line Reference'),
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_lines', to='catalogue.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='line',
            name='stockrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_lines', to='partner.StockRecord'),
        ),
    ]
