# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20170216_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Oracle Code'),
        ),
    ]
