# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_line_oracle_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oracle Code'),
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_lines', to='catalogue.Product', verbose_name='Product'),
        ),
    ]
