# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0015_auto_20190507_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='bpay_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
