# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_basket_bpay_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='monthly_invoicing_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
