# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_auto_20190927_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='bpay_allowed',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='monthly_invoicing_allowed',
        ),
    ]
