# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_auto_20191003_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Existing'), (3, 'Removed')], default=1, null=True),
        ),
    ]
