# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-03 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0018_auto_20200904_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='booking_reference_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
