# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-12 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0020_basket_no_oracle'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='notification_completed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 11, 18, 44, 576329)),
        ),
        migrations.AddField(
            model_name='basket',
            name='notification_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
