# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-30 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0021_auto_20220812_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='notification_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 15, 17, 51, 617472)),
        ),
    ]
