# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-30 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0022_auto_20220830_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 15, 18, 18, 936739), null=True),
        ),
    ]
