# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-05 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210901_1359'),
        ('basket', '0023_auto_20220830_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_organisation', to='accounts.Organisation'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 29, 57, 546486), null=True),
        ),
    ]
