# Generated by Django 5.2.9 on 2026-05-23 13:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_address_id_and_more'),
        ('basket', '0024_auto_20230105_1729'),
        ('catalogue', '0014_auto_20210104_1151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_token',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Basket Token'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='no_oracle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 23, 21, 25, 32, 313008), null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_organisation', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='line',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.basket', verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='basket.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.option', verbose_name='Option'),
        ),
    ]
