# Generated by Django 5.2.14 on 2026-05-25 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0025_basket_basket_token_alter_basket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='invoice_name',
            field=models.CharField(blank=True, default='', help_text='Is used to override the customer account name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='invoice_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 25, 14, 36, 43, 762124), null=True),
        ),
    ]
