# Generated by Django 5.2.9 on 2026-05-25 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0026_basket_invoice_name_basket_invoice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='success_return_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='notification_next',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 25, 22, 28, 54, 145640), null=True),
        ),
    ]
