# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=512)),
                ('system_id', models.CharField(blank=True, max_length=4, null=True)),
                ('api_key', models.CharField(max_length=512)),
                ('allowed_ips', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
