# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgergw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
