# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgergw', '0003_api_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='allowed_ips',
            field=models.TextField(blank=True, default='', help_text='Use network ranges format: eg 1 ip = 10.1.1.1/32 or for a c class block of ips use 192.168.1.0/24 etc', null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Key is auto generated,  Leave blank or blank out to create a new key', max_length=512, null=True),
        ),
    ]
