# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgergw', '0004_auto_20200421_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cmd', models.CharField(blank=True, max_length=1000, null=True)),
                ('system_id', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('processed_dt', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
