# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgergw', '0005_jobqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='parameters_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
