# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgergw', '0006_jobqueue_parameters_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobqueue',
            name='processed_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
