# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgergw', '0007_auto_20230731_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
