# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
