export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const UPDATE_ORIGINAL_APPLICATION = 'UPDATE_ORIGINAL_APPLICATION';
export const UPDATE_APPLICATION_ATTRIBUTE = 'UPDATE_APPLICATION_ATTRIBUTE';
export const UPDATE_ORG_APPLICANT = 'UPDATE_ORG_APPLICANT';
export const UPDATE_PROXY_APPLICANT = 'UPDATE_PROXY_APPLICANT';
