export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const UPDATE_ORIGINAL_APPLICATION = 'UPDATE_ORIGINAL_APPLICATION';
export const UPDATE_APPLICATION_ATTRIBUTE = 'UPDATE_APPLICATION_ATTRIBUTE';
export const UPDATE_ORG_APPLICANT = 'UPDATE_ORG_APPLICANT';
export const UPDATE_PROXY_APPLICANT = 'UPDATE_PROXY_APPLICANT';
export const UPDATE_SELECTED_TAB_ID = 'UPDATE_SELECTED_TAB_ID';
export const UPDATE_SELECTED_TAB_NAME = 'UPDATE_SELECTED_TAB_NAME';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
