# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 08:51
from __future__ import unicode_literals

import os

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', os.path.join(fixture_dir, 'initial_data.json'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
