# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('institution', models.CharField(blank=True, default='', help_text='Company, Tertiary Institution, Government Department, etc', max_length=200, verbose_name='Institution')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.AddField(
            model_name='persona',
            name='postal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address', verbose_name='Postal Address'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
