# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_useraddress_profile_address'),
        ('accounts', '0002_auto_20160830_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to='address.UserAddress'),
            preserve_default=False,
        ),
    ]
