# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160322_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='postal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Address', verbose_name='Postal Address'),
        ),
    ]
