# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160830_1336'),
        ('accounts', '0002_emailuser_senior_card'),
    ]

    operations = [
    ]
