# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ledger.accounts.models import Profile

def update_profile_postal_address_user(apps, schema_editor):
    # Required for updating each postal_address__user_id record
    try:
        for p in Profile.objects.all():
            p.postal_address.user = p.user
            p.postal_address.save()
    except: pass

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_useraddress_profile_address'),
        ('accounts', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hash',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to='address.UserAddress'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_adresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(update_profile_postal_address_user),
    ]

