# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160322_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=255, verbose_name='Suburb / Town'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('NT', 'NT'), ('QLD', 'QLD'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC'), ('WA', 'WA')], max_length=255),
        ),
    ]
