# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_oscar_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to='address.UserAddress'),
        ),
    ]
