# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160323_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='institution',
            field=models.CharField(blank=True, default='', help_text='e.g. Company Name, Tertiary Institution, Government Department, etc', max_length=200, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(help_text='e.g Personal, Work, University, etc', max_length=100, verbose_name='Display Name'),
        ),
    ]
