# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160907_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='hash',
            field=models.CharField(db_index=True, default=0, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_addresses', to='address.UserAddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_adresses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
