# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hash',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
