# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160401_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_document', to='accounts.Document'),
        ),
    ]
