# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailuser_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_document', to='accounts.Document'),
        ),
    ]
