# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160908_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='accounts.Address', verbose_name='Postal Address'),
        ),
    ]
