# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160404_1232'),
        ('accounts', '0005_emailidentity'),
    ]

    operations = [
    ]
