# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160413_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g Personal, Work, University, etc', max_length=100, verbose_name='Display Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('institution', models.CharField(blank=True, default='', help_text='e.g. Company Name, Tertiary Institution, Government Department, etc', max_length=200, verbose_name='Institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
    ]
