# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160413_1355'),
        ('applications', '0015_auto_20160413_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Address', verbose_name='Postal Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
