# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170215_1110'),
        ('accounts', '0010_auto_20170302_0822'),
    ]

    operations = [
    ]
