# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170302_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ABN')),
                ('identification', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_billing_address', to='accounts.Address')),
            ],
        ),
        migrations.RenameField(
            model_name='emailuser',
            old_name='organisation',
            new_name='organisation_name',
        ),
        migrations.AddField(
            model_name='organisation',
            name='delegates',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_postal_address', to='accounts.Address'),
        ),
    ]
