# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170920_1618'),
        #('accounts', '0012_auto_20171228_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='WA', max_length=255),
        ),
    ]
