# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160413_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='character_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
