# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170526_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='WA', max_length=255),
        ),
    ]
