# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_emailuser_character_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='character_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting ledger.accounts.'),
        ),
    ]
