# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160426_0919'),
        ('accounts', '0013_auto_20160426_1133'),
    ]

    operations = [
    ]
