# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_emailuseraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
