# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170612_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Line 2')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Line 3')),
                ('locality', models.CharField(max_length=255, verbose_name='Suburb / Town')),
                ('state', models.CharField(blank=True, default='WA', max_length=255)),
                ('country', django_countries.fields.CountryField(default='AU', max_length=2)),
                ('postcode', models.CharField(max_length=10)),
                ('search_text', models.TextField(editable=False)),
                ('hash', models.CharField(db_index=True, editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'organisation addresses',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_adresses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_billing_address', to='accounts.OrganisationAddress'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_postal_address', to='accounts.OrganisationAddress'),
        ),
        migrations.AddField(
            model_name='organisationaddress',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='accounts.Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationaddress',
            unique_together=set([('organisation', 'hash')]),
        ),
    ]
