# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181030_1433'),
        ('accounts', '0015_auto_20180706_1328'),
    ]

    operations = [
    ]
