# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170613_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='phone_number',
        ),
    ]
