# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20181116_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='trading_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
