# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20181116_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
