# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-19 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_organisation_email_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='email_contact',
            new_name='email',
        ),
    ]
