# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-23 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_communicationslogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.CommunicationsLogEntry')),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.communicationslogentry',),
        ),
    ]
