# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ledger.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_emailuserlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserLogDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Document')),
                ('_file', models.FileField(upload_to=ledger.accounts.models.update_emailuser_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.EmailUserLogEntry')),
            ],
            bases=('accounts.document',),
        ),
    ]
