# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_emailuserlogdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='position_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='position title'),
        ),
    ]
