# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-30 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_emailuser_position_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationslogentry',
            name='type',
        ),
    ]
