# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_communicationslogentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationslogentry',
            name='log_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('onhold', 'On Hold'), ('onhold_remove', 'Remove On Hold'), ('with_qaofficer', 'With QA Officer'), ('with_qaofficer_completed', 'QA Officer Completed')], default='email', max_length=35),
        ),
    ]
