# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_organisation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='position_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='position title'),
        ),
    ]
