# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210224_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(location='/data/projects/ledger/private-media'), upload_to='uploads/%Y/%m/%d')),
                ('name', models.CharField(max_length=256)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, editable=False, null=True)),
                ('file_group', models.IntegerField(blank=True, choices=[(1, 'identification')], null=True)),
                ('file_group_ref_id', models.IntegerField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
