# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210421_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='billing_same_as_residential',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='postal_same_as_residential',
            field=models.NullBooleanField(default=False),
        ),
    ]
