# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 06:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210423_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/view/', location='/data/projects/ledger-master2/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
    ]
