# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 07:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210507_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='manager_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Manager Email'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='manager_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/view/', location='/data/ledger-master2/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
    ]
