# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210604_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Manager Email'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='manager_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Manager Name'),
        ),
    ]
