# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-05 16:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210901_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationaddress',
            unique_together=set([]),
        ),
    ]
