# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-02 11:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20230506_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='legal_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Legal date of birth'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='legal_first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Legal Given name(s)'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='legal_last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
