# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-14 06:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20240702_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('change_value', models.CharField(blank=True, max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
