# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-14 06:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20240714_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuserchangelog',
            name='change_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_request_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailuserchangelog',
            name='emailuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_email_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
