# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-10-21 02:23
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20240716_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='staff_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='staff mobile number'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='staff_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='staff phone number'),
        ),
    ]
