# Generated by Django 5.2.9 on 2026-05-23 13:23

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_3_remove_parkstay_view'),
    ]
    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS ps_test_view;",
            reverse_sql="""
                -- Put your original CREATE VIEW SQL here 
                -- so rollback (migrate back) works if needed.
                 CREATE VIEW ps_test_view AS   SELECT DISTINCT pd.name AS "District Name",
    pr.name AS "Region",
    pp.name AS "Park Name",
    pc.name AS "Campground Name",
    string_agg(DISTINCT pcs.name::text, ','::text) AS "Campsite",
    pb.details,
    ae.email,
    pb.id::character varying AS confirmationno,
    pb.arrival,
    pb.departure
   FROM parkstay_booking pb
     LEFT JOIN parkstay_campground pc ON pb.campground_id = pc.id
     LEFT JOIN parkstay_park pp ON pc.park_id = pp.id
     LEFT JOIN parkstay_district pd ON pp.district_id = pd.id
     LEFT JOIN parkstay_region pr ON pd.region_id = pr.id
     LEFT JOIN accounts_emailuser ae ON pb.customer_id = ae.id
     LEFT JOIN accounts_emailuser cb ON pb.canceled_by_id = cb.id
     LEFT JOIN parkstay_campsitebooking pcb ON pb.id = pcb.booking_id
     LEFT JOIN parkstay_campsite pcs ON pcb.campsite_id = pcs.id
  WHERE pb.is_canceled = false
  GROUP BY pd.name, pr.name, pp.name, pc.name, ae.email, pb.id, pb.arrival, pb.departure;
            """
        ),
    ]




 