# Generated by Django 5.2.9 on 2026-05-23 13:23

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_1_remove_parkstay_view'),
    ]
    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS parkstay_booking_test_v;",
            reverse_sql="""
                -- Put your original CREATE VIEW SQL here 
                -- so rollback (migrate back) works if needed.
                CREATE VIEW parkstay_booking_test_v AS  SELECT DISTINCT pb.created,
    pd.name AS "District Name",
    pr.name AS "Region",
    pp.name,
    pc.name AS "Campground Name",
    pb.details,
    ae.email,
    ae.mobile_number AS "Account Mobile",
    ae.phone_number AS "Account Phone",
    pb.id::character varying AS confirmationno,
    string_agg(DISTINCT pcs.name::text, ','::text) AS "Campsite",
    pb.arrival,
    pb.departure,
    pb.departure - pb.arrival AS numberofdays,
    pvr.rego,
    pvr.type,
    pvr.entry_fee,
    pvr.park_entry_fee,
    pb.is_canceled AS canceled,
    pb.cancellation_reason,
    pb.cancelation_time
   FROM parkstay_booking pb
     LEFT JOIN parkstay_campground pc ON pb.campground_id = pc.id
     LEFT JOIN parkstay_park pp ON pc.park_id = pp.id
     LEFT JOIN parkstay_district pd ON pp.district_id = pd.id
     LEFT JOIN parkstay_region pr ON pd.region_id = pr.id
     LEFT JOIN accounts_emailuser ae ON pb.customer_id = ae.id
     LEFT JOIN accounts_emailuser cb ON pb.canceled_by_id = cb.id
     LEFT JOIN parkstay_campsitebooking pcb ON pb.id = pcb.booking_id
     LEFT JOIN parkstay_campsite pcs ON pcb.campsite_id = pcs.id
     LEFT JOIN parkstay_discountreason pdr ON pb.override_reason_id = pdr.id
     LEFT JOIN parkstay_bookingvehiclerego pvr ON pb.id = pvr.booking_id
     LEFT JOIN parkstay_bookinginvoice pbi ON pb.id = pbi.booking_id AND (pbi.invoice_reference::text IN ( SELECT payments_invoice.reference
           FROM payments_invoice
          WHERE payments_invoice.voided = false))
     LEFT JOIN payments_invoice pi ON pbi.invoice_reference::text = pi.reference::text AND pi.voided = false
     LEFT JOIN ( SELECT payments_bpointtransaction.crn1,
            sum(
                CASE
                    WHEN payments_bpointtransaction.action::text = ANY (ARRAY['payment'::character varying::text, 'move_in'::character varying::text]) THEN payments_bpointtransaction.amount
                    WHEN payments_bpointtransaction.action::text = ANY (ARRAY['refund'::character varying::text, 'move_out'::character varying::text]) THEN payments_bpointtransaction.amount * '-1'::integer::numeric
                    ELSE payments_bpointtransaction.amount
                END) AS sumamount
           FROM payments_bpointtransaction
          GROUP BY payments_bpointtransaction.crn1) pbt ON pi.reference::text = pbt.crn1::text
     LEFT JOIN ( SELECT payments_cashtransaction.invoice_id,
            sum(
                CASE
                    WHEN payments_cashtransaction.type::text = ANY (ARRAY['payment'::character varying::text, 'move_in'::character varying::text]) THEN payments_cashtransaction.amount
                    WHEN payments_cashtransaction.type::text = ANY (ARRAY['refund'::character varying::text, 'move_out'::character varying::text]) THEN payments_cashtransaction.amount * '-1'::integer::numeric
                    ELSE payments_cashtransaction.amount
                END) AS sumamount
           FROM payments_cashtransaction
          GROUP BY payments_cashtransaction.invoice_id) pct ON pi.reference::text = pct.invoice_id::text
  GROUP BY pb.created, pd.name, pr.name, pp.name, pc.name, pb.details, ae.email, ae.mobile_number, ae.phone_number, pb.arrival, pb.departure, (pb.id::character varying), pvr.rego, pvr.type, pvr.entry_fee, pvr.park_entry_fee, pb.is_canceled, pb.cancellation_reason, pb.cancelation_time;
            """
        ),


    ]




 