# Generated by Django 5.2.14 on 2026-05-28 04:51

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_address_id_and_more'),
        ('address', '0006_alter_useraddress_country_alter_useraddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_addresses', to='address.useraddress'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='residential_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/view/', location='/data/data/projects/legder_django5upgrade/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
    ]
