# Generated by Django 5.2.14 on 2026-05-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_address_oscar_address_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
